import {test,expect} from '@playwright/test';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
import {hashPassword} from '../../apps/api/src/passwords';
const id=randomUUID(),email=`admin-browser-${id}@example.com`,password='Fixture-admin-only!2026';
let pool:pg.Pool;
test.beforeAll(async()=>{if(!process.env.TEST_DATABASE_URL)return;pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});expect((await pool.query('SELECT count(*) FROM "AdminAccess"')).rows[0].count).toBe('0');await pool.query('INSERT INTO "User" (id,email,name) VALUES ($1,$2,$3)',[id,email,'Fixture administrator']);await pool.query('INSERT INTO "PasswordCredential" (id,"userId",email,"passwordHash","updatedAt") VALUES ($1,$2,$3,$4,NOW())',[randomUUID(),id,email,await hashPassword(password)]);await pool.query('INSERT INTO "AdminAccess" (id,"userId","updatedAt") VALUES (1,$1,NOW())',[id]);});
test.afterAll(async()=>{if(!pool)return;await pool.query('DELETE FROM "AdminAccess" WHERE "userId"=$1',[id]);await pool.query('DELETE FROM session WHERE sess->\'passport\'->>\'user\'=$1',[id]);await pool.query('DELETE FROM "User" WHERE id=$1',[id]);await pool.end();});
for(const width of [360,390,768,1024,1440,1920])test(`selected admin navigation, tables and login ${width}px`,async({page})=>{
 test.skip(!process.env.TEST_DATABASE_URL,'Disposable database required');await page.setViewportSize({width,height:900});await page.goto('/admin/login');await expect(page.getByRole('heading',{name:'Log in to Daily Ledger Admin'})).toBeVisible();await page.screenshot({path:`artifacts/admin-login-${width}.png`,fullPage:true});await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Log in',exact:true}).click();await expect(page).toHaveURL(/\/admin$/);for(const route of ['','users','plans','announcements','automations','reports','ai','settings','audit']){await page.goto('/admin'+(route?'/'+route:''));await expect(page.locator('.admin-main h1')).toBeVisible();await expect(page.locator('.admin-card').first()).toHaveCSS('opacity','1');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route).toBe(true);await page.screenshot({path:`artifacts/admin-${route||'overview'}-${width}.png`,fullPage:true});}if(width<800){await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.locator('.sidebar .brand')).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Open navigation'})).toBeFocused();await page.getByRole('button',{name:'Open navigation'}).click();}await page.getByRole('button',{name:'Log out',exact:true}).click();await expect(page).toHaveURL(/\/admin\/login$/);
});
test('ordinary user session cannot enter admin pages',async({page})=>{await page.goto('/admin/users');await expect(page).toHaveURL(/\/admin\/login$/);await expect(page.getByRole('heading',{name:'Log in to Daily Ledger Admin'})).toBeVisible();});
