import { test,expect } from '@playwright/test';
for(const width of [360,390,768,1024,1440,1920])test(`auth layouts ${width}px`,async({page})=>{await page.setViewportSize({width,height:width<800?844:900});await page.route('**/backend/auth/csrf',r=>r.fulfill({json:{csrf:'test-csrf'}}));await page.route('**/backend/auth/me',r=>r.fulfill({status:401,json:{error:'Sign in'}}));await page.route('**/backend/health',r=>r.fulfill({json:{googleConfigured:true,passwordConfigured:true}}));for(const route of ['login','signup']){await page.goto('/'+route);await expect(page.getByRole('heading',{level:1})).toHaveText(route==='login'?'Log in to Daily Ledger':'Create your Daily Ledger account');await expect(page.getByRole('button',{name:'Continue with Google'})).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.locator(".auth-footer")).toHaveCSS("opacity","1");await page.screenshot({path:`artifacts/${route}-${width}.png`,fullPage:true});await expect(page.getByLabel('Full name')).toHaveCount(route==='signup'?1:0);if(route==='signup')await expect(page.getByText('Mix of letters, numbers, and symbols')).toBeVisible();await expect(page.getByLabel('Email',{exact:true})).toBeVisible();await expect(page.getByLabel('Password',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Terms',exact:true})).toHaveAttribute('href','/terms');await expect(page.getByRole('link',{name:'Privacy Policy'})).toHaveAttribute('href','/privacy');}});
test('unconfigured OAuth, failure, retry and reciprocal navigation',async({page})=>{await page.route('**/backend/auth/csrf',r=>r.fulfill({json:{csrf:'test-csrf'}}));await page.route('**/backend/auth/me',r=>r.fulfill({status:401,json:{error:'Sign in'}}));let configured=false;await page.route('**/backend/health',r=>r.fulfill({json:{googleConfigured:configured,passwordConfigured:true}}));await page.goto('/login?auth=failed&returnTo=%2Ftasks');await expect(page.getByText('Google authentication is not configured in this environment.')).toBeVisible();await expect(page.getByRole('button',{name:'Continue with Google'})).toBeDisabled();configured=true;await page.getByRole('button',{name:'Retry Google connection'}).click();await expect(page.getByRole('button',{name:'Continue with Google'})).toBeEnabled();await page.getByRole('link',{name:'Sign up.',exact:true}).click();await expect(page).toHaveURL(/signup\?returnTo=%2Ftasks/);await page.getByRole('link',{name:'Log in.',exact:true}).click();await expect(page).toHaveURL(/login\?returnTo=%2Ftasks/);});
test('Google redirect validates return URL and disables repeat clicks',async({page})=>{await page.route('**/backend/auth/csrf',r=>r.fulfill({json:{csrf:'test-csrf'}}));await page.route('**/backend/auth/me',r=>r.fulfill({status:401,json:{}}));await page.route('**/backend/health',r=>r.fulfill({json:{googleConfigured:true,passwordConfigured:true}}));let destination='';await page.route('**/backend/auth/google?*',async r=>{destination=r.request().url();await r.fulfill({status:200,contentType:'text/html',body:'<h1>OAuth redirect test destination</h1>'});});await page.goto('/login?returnTo=https://evil.example');await page.getByRole('button',{name:'Continue with Google'}).click();await expect(page.getByRole('heading',{name:'OAuth redirect test destination'})).toBeVisible();expect(new URL(destination).searchParams.get('returnTo')).toBe('/');});

test('login retry recovers when the API returns and clears the stale connection error',async({page})=>{
 let available=false;
 await page.route('**/backend/auth/me',r=>r.fulfill({status:available?401:500,json:{error:available?'Sign in':'Backend offline'}}));
 await page.route('**/backend/health',r=>r.fulfill({json:{googleConfigured:false,passwordConfigured:true}}));
 await page.route('**/backend/auth/csrf',r=>r.fulfill({json:{csrf:'fixture-csrf'}}));
 await page.goto('/login');
 await expect(page.getByText('The authentication service could not be reached. Please retry.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Log in',exact:true})).toBeDisabled();
 available=true;await page.getByRole('button',{name:'Retry connection',exact:true}).click();
 await expect(page.getByRole('button',{name:'Log in',exact:true})).toBeEnabled();
 await expect(page.getByText('The authentication service could not be reached. Please retry.',{exact:true})).toHaveCount(0);
 await expect(page.getByText('Google authentication is not configured in this environment.',{exact:true})).toBeVisible();
});
