import {test,expect} from '@playwright/test';
test('banned customers can send support tickets and read replies after reload without workspace access',async({page})=>{
 const ticket={id:'restricted-ticket',subject:'Please review my ban',category:'account',priority:'normal',status:'open',version:1,createdAt:'2026-10-05T00:00:00Z',updatedAt:'2026-10-05T00:00:00Z',messages:[{id:'reply',role:'admin',authorName:'Daily Ledger Support',body:'Your account review is in progress.',createdAt:'2026-10-05T00:00:00Z'}]};let sent=false;
 await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:'Banned fixture',email:'fixture@example.com',status:'suspended'},csrf:'fixture'}}));
 await page.route('**/backend/api/snapshot',r=>r.fulfill({status:403,json:{error:'This account is suspended. Contact support.'}}));
 await page.route('**/backend/api/support**',async r=>{if(r.request().method()==='POST'){sent=true;if(r.request().url().endsWith('/messages'))ticket.messages.push({id:'customer-reply',role:'user',authorName:'Banned fixture',body:r.request().postDataJSON().body,createdAt:'2026-10-05T00:00:00Z'});await r.fulfill({status:201,json:ticket});}else await r.fulfill({json:r.request().url().includes('/restricted-ticket')?ticket:{tickets:sent?[ticket]:[],total:sent?1:0,page:1,limit:20,counts:{open:sent?1:0}}});});
 await page.goto('/');await expect(page).toHaveTitle('Account restricted — Daily Ledger');await expect(page.getByRole('heading',{name:'Your account is banned'})).toBeVisible();await expect(page.locator('.sidebar')).toHaveCount(0);await page.getByRole('button',{name:'New ticket',exact:true}).click();await page.getByRole('dialog').getByLabel('Subject',{exact:true}).fill(ticket.subject);await page.getByRole('dialog').getByLabel('What happened?',{exact:true}).fill('Please review my account restriction.');await page.getByRole('button',{name:'Send ticket',exact:true}).click();await expect(page.locator('.support-messages')).toContainText(ticket.messages[0].body);
 await page.reload();await page.locator('.support-ticket').click();await expect(page.locator('.support-messages')).toContainText(ticket.messages[0].body);await page.getByRole('textbox',{name:'Reply message',exact:true}).fill('plz unban');await page.getByRole('button',{name:'Send reply',exact:true}).click();await expect(page.locator('.support-messages')).toContainText('plz unban');await page.goto('/fitness');await expect(page.getByRole('heading',{name:'Your account is banned'})).toBeVisible();await expect(page.locator('.workout-guide')).toHaveCount(0);
 for(const width of [360,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/banned-support-${width}.png`,fullPage:true});}
});
test('admin initial gate uses the same animated loading line',async({page})=>{
 let release=()=>{};const pending=new Promise<void>(resolve=>release=resolve);await page.route('**/backend/api/admin/me',async r=>{await pending;await r.fulfill({status:401,json:{error:'Fixture signed out'}});});await page.goto('/admin');await expect(page.locator('.account-loading')).toContainText('Checking administrator access');expect(await page.locator('.account-loading-bar').evaluate(el=>getComputedStyle(el,'::after').animationName)).toBe('workspace-loading-sweep');release();
});
