import {test,expect} from '@playwright/test';
test('income and bills create actual transactions only after confirmation',async({page})=>{
 await page.goto('/finance/income');await page.getByRole('button',{name:'Add income source',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Monthly freelance');await dialog.getByLabel('Monthly amount').fill('250');await dialog.getByRole('button',{name:'Save plan'}).click();await expect(dialog).toHaveCount(0);
 const row=page.locator('.finance-plan-row').filter({hasText:'Monthly freelance'});await row.getByRole('button',{name:'Mark received'}).click();await dialog.getByRole('button',{name:'Confirm received'}).click();await expect(dialog).toHaveCount(0);await expect(row).toContainText('Received');await expect(row.getByRole('button',{name:'Mark received'})).toHaveCount(0);
 await page.goto('/finance');await expect(page.locator('.finance-hero').first()).toContainText('$2,970');
 await page.goto('/finance/bills');await page.getByRole('button',{name:'Add bill',exact:true}).click();await dialog.getByLabel('Name',{exact:true}).fill('Internet plan');await dialog.getByLabel('Monthly amount').fill('50');await dialog.getByRole('button',{name:'Save plan'}).click();await expect(dialog).toHaveCount(0);const bill=page.locator('.finance-plan-row').filter({hasText:'Internet plan'});await bill.getByRole('button',{name:'Pause Internet plan'}).click();await expect(bill.getByRole('button',{name:'Mark paid'})).toBeDisabled();await bill.getByRole('button',{name:'Resume Internet plan'}).click();await bill.getByRole('button',{name:'Mark paid'}).click();await dialog.getByRole('button',{name:'Confirm paid'}).click();await expect(dialog).toHaveCount(0);await expect(bill).toContainText('Paid');
 await page.goto('/finance/transactions');await page.getByLabel('Search transactions').fill('Internet plan');await expect(page.locator('tbody tr')).toHaveCount(1);await expect(page.locator('tbody')).toContainText('$50');
});
test('category budgets repeat and calculators handle profit and loss',async({page})=>{
 await page.goto('/finance/budgets');await page.getByRole('button',{name:'Add budget',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Budget name').fill('Food cap');await dialog.getByLabel('Budget',{exact:true}).fill('500');await dialog.getByLabel('Category (leave empty for overall budget)').fill('Food');await dialog.getByRole('button',{name:'Save budget'}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('.finance-budget-row').filter({hasText:'Food'})).toContainText('Repeats monthly');await page.getByLabel('Selected month').fill('2026-10');await expect(page.locator('.finance-budget-row').filter({hasText:'Food'})).toContainText('$500 remaining');
 await page.goto('/finance/calculators/loan');await page.getByLabel('Annual interest rate').fill('0');await page.getByLabel('Loan amount').fill('12000');await page.getByLabel('Term',{exact:true}).fill('1');await expect(page.locator('.finance-calculator-results')).toContainText('$1,000');
 await page.goto('/finance/calculators/profit');await page.getByLabel('Revenue',{exact:true}).fill('100');await page.getByLabel('Total costs').fill('150');await expect(page.locator('.finance-calculator-results .negative').first()).toContainText('-$50');await page.getByRole('link',{name:'Back to calculators'}).click();await expect(page.getByText('Six practical calculators')).toBeVisible();
});
for(const width of [360,390,768,1024,1440,1920])test(`finance tools, assistant and sidebar ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});for(const route of ['income','bills','budgets','savings','transactions','calculators','calculators/profit','recurring']){await page.goto('/finance/'+route);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('.finance-back')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route).toBe(true);await expect(page.locator('.panel').first()).toHaveCSS('opacity','1');await page.screenshot({path:`artifacts/finance-${route.replace('/','-')}-${width}.png`,fullPage:true});}await page.goto('/assistant');await expect(page.getByText('AI Assistant is not configured',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/assistant-${width}.png`,fullPage:true});await expect(page.locator('.sidebar .brand')).toContainText('Daily Ledger');await expect(page.locator('.sidebar .brand img')).toHaveAttribute('src','/daily-ledger-logo.png');if(width<800){await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.locator('.sidebar .brand')).toBeFocused();await page.screenshot({path:`artifacts/sidebar-${width}.png`});await page.keyboard.press('Escape');}
});
