import {test,expect} from '@playwright/test';
import {demoSnapshot,type Snapshot} from '../../packages/shared/src/index';
import {exerciseGuides} from '../../apps/web/lib/exercise-guides';

test('exercise highlights follow the target and saved scheduled streak colours',async({page})=>{
 const s=demoSnapshot();const id='exercise-tracker-fixture';s.records.push({id,kind:'habit',version:1,data:{title:'Lat pulldown practice',days:[0,1,2,3,4,5,6],active:true,startDate:'2026-09-24',exerciseSlug:'lat-pulldown'}});for(let day=24;day<=29;day++)s.records.push({id:`exercise-day-${day}`,kind:'completion',version:1,data:{habitId:id,date:`2026-09-${day}`}});
 await page.addInitScript(snapshot=>{if(!localStorage.getItem('daily-ledger-demo-v1'))localStorage.setItem('daily-ledger-demo-v1',JSON.stringify(snapshot));},s);await page.goto('/fitness/exercises/lat-pulldown');await expect(page.locator('.anatomy-view')).toHaveClass(/anatomy-back/);await expect(page.locator('.anatomy-overlay path')).toHaveAttribute('data-muscle','Back');await expect(page.locator('.anatomy-overlay')).toHaveCSS('color','rgb(128, 228, 189)');
 const tick=page.getByRole('button',{name:'Lat pulldown practice, 2026-09-30, Due today',exact:true});await tick.click();await expect(page.locator('.anatomy-overlay')).toHaveCSS('color','rgb(251, 113, 133)');await expect(page.getByRole('button',{name:'Lat pulldown practice, 2026-09-30, Completed',exact:true})).toBeEnabled();await page.reload();await expect(page.locator('.anatomy-overlay')).toHaveCSS('color','rgb(251, 113, 133)');await page.screenshot({path:'artifacts/exercise-streak-highlight.png'});
 await page.evaluate(()=>{const snapshot=JSON.parse(localStorage.getItem('daily-ledger-demo-v1')!);snapshot.records=snapshot.records.filter((r:any)=>r.id!=='exercise-day-29');localStorage.setItem('daily-ledger-demo-v1',JSON.stringify(snapshot));});await page.reload();await expect(page.locator('.anatomy-overlay')).toHaveCSS('color','rgb(246, 207, 112)');
 await page.goto('/fitness/exercises/biceps-curl');await expect(page.locator('.anatomy-view')).not.toHaveClass(/anatomy-back/);await expect(page.locator('.anatomy-overlay path')).toHaveAttribute('data-muscle','Biceps');await page.getByRole('button',{name:'Start Biceps curl checklist',exact:true}).click();const form=page.getByRole('dialog');await form.getByRole('button',{name:'Create habit',exact:true}).click();await expect(form).toHaveCount(0);await expect(page.locator('.exercise-tracking .weekly-habit')).toHaveCount(1);await page.reload();await expect(page.locator('.exercise-tracking .weekly-habit')).toHaveCount(1);
});

test('exercise and goal guides open inside the persistent workspace',async({page})=>{
 let documents=0;page.on('request',r=>{if(r.isNavigationRequest()&&r.frame()===page.mainFrame())documents++;});await page.goto('/fitness');await expect(page.locator('.workout-guide')).toBeVisible();await page.locator('.sidebar').evaluate(el=>el.setAttribute('data-kept','yes'));
 await page.getByRole('link',{name:'View guide',exact:true}).first().click();await expect(page).toHaveURL(/fitness\/exercises\/incline-push-up$/);await expect(page.getByRole('heading',{name:'Get into position',exact:true})).toBeVisible();await expect(page.locator('.exercise-instructions ol li')).toHaveCount(3);await expect(page.locator('.sidebar')).toHaveAttribute('data-kept','yes');expect(documents).toBe(1);
 await page.getByRole('button',{name:'Log this exercise',exact:true}).click();await expect(page.getByRole('dialog').getByLabel('Workout name',{exact:true})).toHaveValue('Incline push-up');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('link',{name:'Back to Fitness',exact:true}).click();await page.getByRole('link',{name:'Life Goals',exact:true}).click();await page.locator('.actionable-goal h2 a').first().click();await expect(page).toHaveURL(/goals\/[^/]+$/);await expect(page.locator('.goal-detail-layout .actionable-goal')).toHaveCount(1);await expect(page.getByRole('link',{name:'Back to Goals',exact:true})).toBeVisible();expect(documents).toBe(1);
 for(const exercise of exerciseGuides){const response=await page.request.get(`/fitness/exercises/${exercise.slug}`);expect(response.status()).toBe(200);}
 const bad=await page.goto('/fitness/exercises/unknown');expect(bad?.status()).toBe(404);await expect(page.locator('.sidebar')).toHaveCount(0);
});

test('compact assistant has useful prompts, sends a question and remains responsive',async({page})=>{
 const s=demoSnapshot();s.profile.onboardingCompletedAt='2026-09-01T00:00:00Z';await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:'Fixture'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',r=>r.fulfill({json:s}));await page.route('**/backend/api/ai/status',r=>r.fulfill({json:{enabled:true,configured:true,usage:null}}));await page.route('**/backend/api/ai/history',r=>r.fulfill({json:{messages:[]}}));await page.route('**/backend/api/ai/chat',r=>r.fulfill({json:{message:{id:'fixture',question:r.request().postDataJSON().question,answer:'Here is your spending summary.',month:'2026-09',createdAt:new Date().toISOString()}}}));
 await page.goto('/assistant');await page.getByRole('button',{name:'Where did my money go?',exact:true}).click();await expect(page.getByRole('textbox',{name:'Ask the AI Assistant',exact:true})).toHaveValue('Where did my money go?');await page.getByRole('button',{name:'Send',exact:true}).click();await expect(page.locator('.ai-exchange .ai-answer')).toContainText('Here is your spending summary.');
 for(const width of [360,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/assistant-compact-${width}.png`});}
});

test('task and habit ticks update immediately while saving and roll back failed writes',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-09-30T07:00:00Z'));const snapshot:Snapshot=demoSnapshot();snapshot.profile.onboardingCompletedAt='2026-09-01T00:00:00Z';
 await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:'Fixture'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',r=>r.fulfill({json:snapshot}));
 let release=()=>{},started=false;const pending=new Promise<void>(resolve=>release=resolve);
 await page.route('**/backend/api/records/*',async r=>{started=true;await pending;await r.fulfill({status:500,json:{error:'Fixture save failed'}});});
 await page.goto('/tasks');await page.getByRole('button',{name:'Selected month',exact:true}).click();const task=page.getByRole('checkbox',{name:'Complete Finish client proposal',exact:true});
 await task.click();await expect(task).toBeChecked({timeout:500});await expect.poll(()=>started).toBe(true);release();await expect(task).not.toBeChecked();await expect(page.locator('.error-banner')).toContainText('Fixture save failed');
 const reading=page.locator('.weekly-habit').filter({has:page.getByRole('heading',{name:'Reading',exact:true})});let releaseHabit=()=>{};const habitPending=new Promise<void>(resolve=>releaseHabit=resolve);await page.route('**/backend/api/records/*',async r=>{await habitPending;await r.fulfill({status:500,json:{error:'Fixture habit save failed'}});});
 await reading.getByRole('button',{name:'Reading, 2026-09-30, Completed',exact:true}).click();await expect(reading.getByRole('button',{name:'Reading, 2026-09-30, Due today',exact:true})).toHaveAttribute('aria-pressed','false',{timeout:500});releaseHabit();await expect(reading.getByRole('button',{name:'Reading, 2026-09-30, Completed',exact:true})).toHaveAttribute('aria-pressed','true');
});

test('body map filters real exercises and edited workout templates persist in the log',async({page})=>{
 await page.goto('/fitness');const guide=page.locator('.workout-guide');await expect(guide.getByRole('heading',{name:'Train with a clear purpose'})).toBeVisible();
 for(const muscle of ['Chest','Back','Shoulders','Biceps','Triceps','Forearms','Core','Glutes','Quads','Hamstrings','Calves']){await guide.locator('.muscle-buttons').getByRole('button',{name:muscle,exact:true}).click();await expect(guide.locator('.exercise-card')).not.toHaveCount(0);await expect(guide.locator('.exercise-muscle').first()).toHaveText(muscle);}
 await guide.getByRole('button',{name:'Back',exact:true}).first().click();await expect(guide.locator('.anatomy-view')).toHaveAttribute('aria-label',/Back muscle map/);
 await guide.getByRole('button',{name:/Upper body at the gym/}).click();await guide.getByRole('textbox',{name:'Reps for Dumbbell chest press',exact:true}).fill('10');await guide.getByRole('spinbutton',{name:'Sets for Dumbbell chest press',exact:true}).fill('3');await guide.getByRole('button',{name:'Log this routine',exact:true}).click();const form=page.getByRole('dialog');await expect(form.getByLabel('Workout name',{exact:true})).toHaveValue('Upper body at the gym');await expect(form.getByLabel('Notes',{exact:true})).toHaveValue(/Dumbbell chest press: 3 sets × 10/);await form.getByRole('button',{name:'Create workout',exact:true}).click();await expect(form).toHaveCount(0);await page.reload();await expect(page.locator('.workout-log-rows')).toContainText('Dumbbell chest press: 3 sets × 10');
 await page.screenshot({path:'artifacts/workout-guide-desktop.png',fullPage:true});
});

test('weekly meal templates are editable, saved and do not duplicate on retry',async({page})=>{
 await page.goto('/meals');await expect(page.locator('.meal-guide')).toHaveCount(0);await page.getByRole('link',{name:'Build weekly plan',exact:true}).click();const guide=page.locator('.meal-guide');await guide.getByLabel('Your weight',{exact:true}).fill('75');await expect(guide.locator('.nutrition-guidance')).toContainText('60 g/day');await guide.getByLabel('Weekly template',{exact:true}).selectOption('Vegetarian');await guide.getByRole('button',{name:'Preview my week',exact:true}).click();await expect(guide.locator('.meal-preview-days section')).toHaveCount(7);
 const first=guide.locator('.meal-preview-days input').first();await first.fill('My custom breakfast');await guide.getByRole('button',{name:'Save weekly plan',exact:true}).click();await expect(guide.getByRole('status')).toContainText('Your weekly plan is saved');const count=await page.evaluate(()=>JSON.parse(localStorage.getItem('daily-ledger-demo-v1')!).records.filter((r:any)=>r.kind==='meal').length);
 await guide.getByRole('button',{name:'Save weekly plan',exact:true}).click();await expect(guide.getByRole('status')).toContainText('Your weekly plan is saved');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('daily-ledger-demo-v1')!).records.filter((r:any)=>r.kind==='meal').length)).toBe(count);
 await page.getByRole('link',{name:'Open meal calendar',exact:true}).click();await expect(page).toHaveURL(/\/meals(?:\?|$)/);await page.reload();await expect(page.locator('.meal-grid')).toContainText('My custom breakfast');await page.getByRole('link',{name:'Build weekly plan',exact:true}).click();await page.getByRole('button',{name:/Remove generated plan/}).click();await page.getByRole('dialog').getByRole('button',{name:'Remove plan',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('daily-ledger-demo-v1')!).records.filter((r:any)=>r.kind==='meal'&&r.data.generatedPlanId).length)).toBe(0);await page.getByRole('link',{name:'Open meal calendar',exact:true}).click();await expect(page.locator('.meal-grid')).toContainText('Grilled chicken & vegetables');await page.screenshot({path:'artifacts/meal-guide-desktop.png',fullPage:true});
});

test('project goals turn saved next steps into automatic progress',async({page})=>{
 await page.goto('/goals');await page.getByRole('button',{name:/Finish a project/}).click();const form=page.getByRole('dialog');await form.getByLabel('Goal name',{exact:true}).fill('Launch a useful project');await expect(form.getByLabel('Current value',{exact:true})).not.toBeVisible();await form.getByRole('button',{name:'Create goal',exact:true}).click();await expect(form).toHaveCount(0);
 await page.getByRole('button',{name:'all',exact:true}).click();const goal=page.locator('.actionable-goal').filter({has:page.getByRole('heading',{name:'Launch a useful project',exact:true})});
 for(const step of ['Sketch the first screen','Ship the first version']){await goal.getByRole('button',{name:'Add step',exact:true}).click();await form.getByLabel('Milestone',{exact:true}).fill(step);await form.getByRole('button',{name:'Create milestone',exact:true}).click();await expect(form).toHaveCount(0);}
 await expect(goal.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await goal.getByRole('checkbox',{name:'Complete Sketch the first screen',exact:true}).click();await expect(goal.getByRole('progressbar')).toHaveAttribute('aria-valuenow','50');await expect(goal.locator('.goal-next')).toContainText('Ship the first version');await goal.getByRole('checkbox',{name:'Complete Ship the first version',exact:true}).click();await expect(goal.getByRole('progressbar')).toHaveAttribute('aria-valuenow','100');await page.reload();await page.getByRole('button',{name:'completed',exact:true}).click();await expect(goal).toContainText('Achieved');
});

for(const width of [360,768,1440])test(`guides and actionable goals stay responsive ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});for(const path of ['/fitness','/meals','/goals']){await page.goto(path);await expect(page.locator('.page-heading h1')).toBeVisible();await expect(page.locator(path==='/fitness'?'.workout-guide':path==='/meals'?'.meal-health':'.goal-start')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),path).toBe(true);await page.screenshot({path:`artifacts/${path.slice(1)}-guide-${width}.png`,fullPage:true});if(path==='/meals'){await page.getByRole('link',{name:'Build weekly plan',exact:true}).click();await page.getByRole('button',{name:'Preview my week',exact:true}).click();await expect(page.locator('.meal-preview-days>section:visible')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/meal-planner-${width}.png`,fullPage:true});}}
});

test('custom exercises persist their target, notes and daily checklist',async({page})=>{
 await page.goto('/fitness');await page.getByRole('button',{name:'Add custom exercise',exact:true}).click();const form=page.getByRole('dialog');await form.getByLabel('Habit name',{exact:true}).fill('My cable row');await form.getByLabel('Body part',{exact:true}).selectOption('Back');await form.getByLabel('Exercise notes / sets and reps',{exact:true}).fill('3 sets of 10 controlled reps');await form.getByRole('button',{name:'Create habit',exact:true}).click();await expect(form).toHaveCount(0);await page.locator('.custom-exercise-library').getByRole('button',{name:/My cable row/}).click();await expect(page.locator('.anatomy-view')).toHaveClass(/anatomy-back/);await expect(page.locator('.anatomy-overlay path')).toHaveAttribute('data-muscle','Back');const tick=page.getByRole('button',{name:'My cable row, 2026-09-30, Due today',exact:true});await tick.click();await expect(page.getByRole('button',{name:'My cable row, 2026-09-30, Completed',exact:true})).toHaveAttribute('aria-pressed','true',{timeout:500});await page.reload();await expect(page.locator('.custom-exercise-library')).toContainText('3 sets of 10 controlled reps');await expect(page.getByRole('button',{name:'My cable row, 2026-09-30, Completed',exact:true})).toHaveAttribute('aria-pressed','true');
});
test('meal details, nutrition checks and connected groceries persist without duplicates',async({page})=>{
 const s=demoSnapshot();s.records=s.records.filter(r=>r.kind!=='meal');s.records.push({id:'meal-health-fixture',kind:'meal',version:1,data:{title:'Yogurt breakfast',date:'2026-09-30',slot:'Breakfast',notes:'Serve with oats.',ingredients:'Yogurt, Oats, Yogurt',servings:2,nutrition:{calories:300,protein:20}}});await page.addInitScript(snapshot=>{if(!localStorage.getItem('daily-ledger-demo-v1'))localStorage.setItem('daily-ledger-demo-v1',JSON.stringify(snapshot));},s);await page.goto('/meals');await page.locator('.sidebar').evaluate(el=>el.setAttribute('data-kept','meal'));await page.getByRole('checkbox',{name:'Eaten Yogurt breakfast on 2026-09-30',exact:true}).click();await expect(page.locator('.meal-health-stats')).toContainText('300 kcal');await expect(page.locator('.meal-health-stats')).toContainText('20 g');await page.getByRole('link',{name:'Yogurt breakfast',exact:true}).click();await expect(page).toHaveURL('http://localhost:3000/meals/meal-health-fixture');await expect(page.locator('.meal-detail')).toContainText('Serve with oats.');await expect(page.locator('.sidebar')).toHaveAttribute('data-kept','meal');await page.getByRole('link',{name:'Back to your meal plan',exact:false}).click();await page.getByRole('button',{name:'Add missing groceries',exact:true}).click();await expect(page.locator('.meal-grocery-connect [role=status]')).toContainText('2 ingredients added');const count=await page.evaluate(()=>JSON.parse(localStorage.getItem('daily-ledger-demo-v1')!).records.filter((r:any)=>r.kind==='grocery').length);await page.getByRole('button',{name:'Add missing groceries',exact:true}).click();await expect(page.locator('.meal-grocery-connect [role=status]')).toContainText('already includes');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('daily-ledger-demo-v1')!).records.filter((r:any)=>r.kind==='grocery').length)).toBe(count);const purchased=page.getByRole('checkbox',{name:'Purchased Yogurt',exact:true});await purchased.check();await expect(purchased).toBeChecked({timeout:500});await page.reload();await expect(purchased).toBeChecked();await purchased.uncheck();await expect(purchased).not.toBeChecked({timeout:500});await expect(page.getByRole('checkbox',{name:'Eaten Yogurt breakfast on 2026-09-30',exact:true})).toBeChecked();await page.getByRole('checkbox',{name:'Eaten Yogurt breakfast on 2026-09-30',exact:true}).uncheck();await expect(page.getByRole('checkbox',{name:'Eaten Yogurt breakfast on 2026-09-30',exact:true})).not.toBeChecked({timeout:500});await page.reload();await expect(purchased).not.toBeChecked();await expect(page.getByRole('checkbox',{name:'Eaten Yogurt breakfast on 2026-09-30',exact:true})).not.toBeChecked();
});

test('added workouts stay planned until checked and completed minutes persist',async({page})=>{await page.goto('/fitness');await page.getByRole('button',{name:'Plan workout',exact:true}).first().click();const form=page.getByRole('dialog');await form.getByLabel('Workout name',{exact:true}).fill('My planned mobility');await form.getByLabel('Duration (minutes)',{exact:true}).fill('20');await expect(form.getByLabel('Workout completed',{exact:true})).not.toBeChecked();await form.getByRole('button',{name:'Create workout',exact:true}).click();await expect(form).toHaveCount(0);const row=page.locator('.workout-log-rows .detail-row').filter({hasText:'My planned mobility'});await expect(row).toContainText('Planned');const tick=row.getByRole('checkbox');await tick.check();await expect(tick).toBeChecked({timeout:500});await expect(row).toContainText('Completed');await page.reload();await expect(row.getByRole('checkbox')).toBeChecked();await row.getByRole('checkbox').uncheck();await expect(row).toContainText('Planned');const filters=page.getByRole('group',{name:'Filter workout sessions',exact:true});await filters.getByRole('button',{name:/^Planned/}).click();await row.getByRole('checkbox').click();await expect(row).toHaveCount(0);await filters.getByRole('button',{name:/^Completed/}).click();await expect(row).toContainText('Completed');await row.getByRole('checkbox').click();await expect(row).toHaveCount(0);await filters.getByRole('button',{name:/^All sessions/}).click();await expect(row).toContainText('Planned');await page.getByRole('link',{name:'Browse exercises',exact:true}).click();await expect(page).toHaveURL(/#exercise-library$/);await expect(page.locator('.workout-guide')).toBeInViewport();});
