import {test,expect} from '@playwright/test';
import {demoSnapshot} from '../../packages/shared/src/index';
test('admin can choose browser/email channels and all or specific recipients',async({page})=>{
 let payload:any;await page.route('**/backend/api/admin/me',r=>r.fulfill({json:{user:{id:'admin',name:'Fixture admin'},csrf:'fixture'}}));await page.route('**/backend/api/admin/announcements**',r=>r.fulfill({json:{announcements:[]}}));await page.route('**/backend/api/admin/users**',r=>r.fulfill({json:{users:[{id:'fixture',name:'Selected user',email:'fixture@example.com',plan:'Pro',status:'active'}],total:1}}));await page.route('**/backend/api/admin/notifications',async r=>{if(r.request().method()==='POST'){payload=r.request().postDataJSON();await r.fulfill({status:201,json:{browser:1,email:1,skipped:0}});}else await r.fulfill({json:{browserConfigured:true,emailConfigured:true,subscribedBrowsers:1,recent:[]}});});await page.goto('/admin/announcements');await page.getByLabel('Message template').selectOption('Fitness');await expect(page.getByLabel('Notification title')).toHaveValue('Make time for your next workout');await page.getByLabel('Delivery channel').selectOption('both');await page.getByRole('combobox',{name:'Audience',exact:true}).selectOption('Specific');await page.getByRole('checkbox',{name:'Select fixture@example.com'}).check();await expect(page.getByLabel('Recipient emails')).toHaveValue('fixture@example.com');await page.getByLabel('Notification title').fill('Weekly planning reminder');await page.getByRole('textbox',{name:'Message',exact:true}).fill('Plan your week in Daily Ledger.');await page.getByLabel('Reason for sending').fill('Fixture verification');await page.getByRole('button',{name:'Preview notification',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Weekly planning reminder');await page.getByRole('button',{name:'Confirm & send',exact:true}).click();await expect(page.getByRole('status')).toContainText('Queued: 1 browser recipients');expect(payload.channel).toBe('both');expect(payload.emails).toEqual(['fixture@example.com']);expect(payload.audience).toBe('Specific');
});
test('signed-in Settings shows browser notification setup without an automatic permission prompt',async({page})=>{
 const s=demoSnapshot();s.profile.onboardingCompletedAt='2026-10-01T00:00:00Z';let prompt=0;await page.addInitScript(()=>{Notification.requestPermission=async()=>{(window as any).permissionPrompts=((window as any).permissionPrompts||0)+1;return 'denied';};});await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:s.profile.name,email:s.profile.email,status:'active'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',r=>r.fulfill({json:s}));await page.route('**/backend/api/push',r=>r.fulfill({json:{configured:true,publicKey:'fixture',devices:0,subscriptions:[]}}));await page.goto('/settings');await expect(page.getByRole('heading',{name:'Browser notifications',exact:true})).toBeVisible();prompt=await page.evaluate(()=>(window as any).permissionPrompts||0);expect(prompt).toBe(0);await page.getByRole('button',{name:'Enable browser notifications'}).click();await expect(page.locator('.browser-notifications [role=alert]')).toContainText('Allow notifications');expect(await page.evaluate(()=>(window as any).permissionPrompts)).toBe(1);
});

test('zero eligible recipients clearly reports that nothing was sent',async({page})=>{
 await page.route('**/backend/api/admin/me',r=>r.fulfill({json:{user:{id:'admin',name:'Fixture admin'},csrf:'fixture'}}));await page.route('**/backend/api/admin/announcements**',r=>r.fulfill({json:{announcements:[]}}));await page.route('**/backend/api/admin/notifications',r=>r.fulfill({status:r.request().method()==='POST'?201:200,json:r.request().method()==='POST'?{browser:0,email:0,skipped:2,matched:2}:{browserConfigured:true,emailConfigured:false,subscribedBrowsers:0,recent:[]}}));await page.goto('/admin/announcements');await page.getByLabel('Message template').selectOption('Tasks');await page.getByLabel('Reason for sending').fill('Fixture zero recipients');await page.getByRole('button',{name:'Preview notification',exact:true}).click();await page.getByRole('button',{name:'Confirm & send',exact:true}).click();await expect(page.locator('.notification-no-recipients')).toContainText('No notifications were sent.');await expect(page.locator('.notification-no-recipients')).toContainText('Allow in Chrome');await expect(page.getByRole('link',{name:'Enable notifications on this browser'})).toHaveAttribute('href','/settings');
});
