import {test,expect} from '@playwright/test';
import {demoSnapshot} from '../../packages/shared/src/index';
for(const width of [360,390,768,1024,1440,1920])test(`onboarding and honest dashboard reveal ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});let saved=false,snapshots=0;const snapshot=demoSnapshot();snapshot.profile.name='Onboarding fixture';snapshot.profile.onboardingCompletedAt=null;
 await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:snapshot.profile.name,email:snapshot.profile.email},csrf:'fixture-token'}}));await page.route('**/backend/api/snapshot',r=>{snapshots++;return r.fulfill({json:{...snapshot,profile:{...snapshot.profile,onboardingCompletedAt:saved?'2026-10-05T10:00:00Z':null}}});});await page.route('**/backend/api/onboarding',r=>{const body=r.request().postDataJSON();expect(body.name).toBe('Onboarding fixture');expect(body.persona).toBe('Developer');expect(body.focusAreas).toEqual(['finance','tasks']);saved=true;Object.assign(snapshot.profile,body);return r.fulfill({json:{completedAt:'2026-10-05T10:00:00Z',persona:body.persona}});});
 await page.goto('/');for(let step=0;step<4;step++){await expect(page.locator('.onboarding-step-content h1')).toBeVisible();if(step===2)await page.getByRole('checkbox',{name:'Choose more than one focus'}).check();if(step===2){await page.getByRole('button',{name:'Financial Planner',exact:true}).click();await page.getByRole('button',{name:'Tasks & Habits',exact:true}).click();}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/onboarding-${step+1}-${width}.png`,fullPage:true});if(step===0||step===2)await page.getByRole('button',{name:'Continue',exact:true}).click();else if(step===1)await page.getByRole('button',{name:'Developer',exact:true}).click();}
 const start=Date.now();await page.getByRole('button',{name:'Build my dashboard'}).click();await expect(page.getByRole('heading',{name:'Building your dashboard'})).toBeVisible();await expect(page.locator('.building-brand')).toHaveCSS('opacity','1');await expect(page.locator('.building-step').last()).toHaveCSS('opacity','1');await expect.poll(async()=> (await page.locator('.building-brand .project-brand-mark').boundingBox())?.height||0).toBeGreaterThan(40);await page.screenshot({path:`artifacts/building-dashboard-${width}.png`});await expect(page.getByRole('heading',{name:/^(Your life at a glance|Welcome, )/})).toBeVisible();expect(Date.now()-start).toBeGreaterThan(4000);expect(snapshots).toBe(2);await expect(page.locator('.focus-shortcuts')).toContainText('Financial Planner');await page.reload();await expect(page.getByRole('heading',{name:/^(Your life at a glance|Welcome, )/})).toBeVisible();await expect(page.locator('.onboarding-shell')).toHaveCount(0);if(width===1440){const loaded=snapshots;await page.locator('.sidebar').getByRole('link',{name:'Financial Planner',exact:true}).click();await expect(page.getByRole('heading',{name:'Financial Planner',exact:true})).toBeVisible();expect(snapshots).toBe(loaded);}
});
test('reduced motion skips cosmetic delay and slow snapshots cannot tick complete',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});const snapshot=demoSnapshot();snapshot.profile.onboardingCompletedAt=null;let saved=false,release:()=>void=()=>{};const pending=new Promise<void>(resolve=>release=resolve);
 await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:'Fixture'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',async r=>{if(saved)await pending;await r.fulfill({json:{...snapshot,profile:{...snapshot.profile,onboardingCompletedAt:saved?'2026-10-05T10:00:00Z':null}}});});await page.route('**/backend/api/onboarding',r=>{saved=true;return r.fulfill({json:{completedAt:'2026-10-05T10:00:00Z'}});});await page.goto('/');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Use these preferences and skip the rest'}).click();await expect(page.getByRole('heading',{name:'Preparing your dashboard…'})).toBeVisible();await expect(page.getByRole('heading',{name:'Your dashboard is ready'})).toHaveCount(0);release();await expect(page.getByRole('heading',{name:/^(Your life at a glance|Welcome, )/})).toBeVisible({timeout:3000});
});
test('sidebar navigation preserves the shell and snapshot without document reloads',async({page})=>{let documents=0,snapshots=0;page.on('request',r=>{if(r.resourceType()==='document')documents++;if(r.url().endsWith('/api/snapshot'))snapshots++;});await page.goto('/');await expect(page.getByRole('heading',{name:/^(Your life at a glance|Welcome, )/})).toBeVisible();await page.locator('.sidebar').evaluate(el=>el.setAttribute('data-navigation-test','persistent'));const initial=snapshots;for(const label of ['Financial Planner','Tasks & Habits','Life Goals','Overview']){await page.locator('.sidebar').getByRole('link',{name:label,exact:true}).click();await expect(page.locator('.sidebar')).toHaveAttribute('data-navigation-test','persistent');await expect(page.getByRole('status',{name:'Loading your workspace'})).toHaveCount(0);}expect(documents).toBe(1);expect(snapshots).toBe(initial);await expect(page.getByText('Personal workspace',{exact:true})).toHaveCount(0);await expect(page.locator('.sidebar .brand')).toContainText('Daily Ledger');});
test('donut hover stays outside the stable total',async({page})=>{await page.goto('/');await expect(page.locator('.donut-center strong')).toHaveText('$1,280');await page.locator('.spending-legend button').filter({hasText:'Food'}).hover();await expect(page.getByRole('tooltip')).toContainText('Food');await expect(page.getByRole('tooltip')).toContainText('$320');await expect(page.locator('.donut-center strong')).toHaveText('$1,280');const tip=await page.getByRole('tooltip').boundingBox(),ring=await page.locator('.refined-donut').boundingBox();expect(tip!.y).toBeGreaterThanOrEqual(ring!.y+ring!.height-1);await page.getByRole('button',{name:'Quick add',exact:true}).click();await page.getByRole('button',{name:'Transaction',exact:true}).click();const form=page.getByRole('dialog');await form.getByLabel('Description',{exact:true}).fill('Large category fixture');await form.getByLabel('Amount',{exact:true}).fill('30000');await form.getByRole('button',{name:'Create transaction'}).click();await expect(form).toHaveCount(0);await expect(page.locator('.donut-center strong')).toHaveText('$31,280');const center=await page.locator('.donut-center strong').boundingBox(),chart=await page.locator('.refined-donut').boundingBox();expect(Math.abs(center!.y+center!.height/2-(chart!.y+chart!.height/2))).toBeLessThan(15);await expect(page.locator('.metric-content strong').nth(1)).toHaveText('$31,280');await page.screenshot({path:'artifacts/dashboard-large-category.png',fullPage:true});});

test('feature charts reflect task status, workload and recorded activity',async({page})=>{await page.goto('/tasks');await expect(page.getByRole('heading',{name:'Task workload · last 4 weeks'})).toBeVisible();await expect(page.getByRole('heading',{name:'Habit consistency over time'})).toBeVisible();await expect(page.locator('.task-status-center strong')).toHaveText('24');await page.locator('.sidebar').getByRole('link',{name:'Fitness',exact:true}).click();await expect(page.getByRole('heading',{name:'Your activity rhythm'})).toBeVisible();await page.locator('.sidebar').getByRole('link',{name:'Meals & Grocery',exact:true}).click();await expect(page.getByRole('heading',{name:'Your meal planning rhythm'})).toBeVisible();});
