import { test,expect } from '@playwright/test';
test('money entry uses normal currency amounts and links use names',async({page})=>{
 await page.goto('/finance');
 await expect(page.locator('.finance-budget-row')).toContainText('$720');
 await expect(page.locator('.finance-hero')).toContainText('$2,720');
 await page.goto('/goals');
 const goal=page.locator('.two-grid>.panel').filter({hasText:'Emergency fund'});
 await goal.getByRole('button',{name:'Add milestone'}).click();
 const dialog=page.getByRole('dialog');
 expect(await dialog.getByLabel('Goal',{exact:true}).evaluate((element:HTMLSelectElement)=>element.selectedOptions[0].textContent)).toBe('Emergency fund');
 await dialog.getByLabel('Milestone',{exact:true}).fill('Build first buffer');
 await dialog.getByRole('button',{name:'Create milestone'}).click();
 await expect(dialog).toHaveCount(0);
 await expect(goal).toContainText('Build first buffer');
 await expect(page.getByText(/Goal ID:/)).toHaveCount(0);
 await page.goto('/meals');
 await page.locator('.meal-day.outside-month').first().getByRole('button',{name:'Plan meal',exact:true}).first().click();
 await expect(dialog.getByLabel('Date',{exact:true})).toHaveValue('2026-10-01');
 await expect(dialog.getByLabel('Meal',{exact:true})).toHaveValue('Breakfast');
 await dialog.getByLabel('Meal name',{exact:true}).fill('October breakfast');
 await dialog.getByRole('button',{name:'Create meal'}).click();
 await expect(dialog).toHaveCount(0);
 await expect(page.getByText('October breakfast',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Add item',exact:true}).click();
 await dialog.getByLabel('Grocery item',{exact:true}).fill('Test oats');
 await dialog.getByLabel('Estimated cost',{exact:true}).fill('1.99');
 await dialog.getByLabel('Linked meal (optional)').selectOption({label:'October breakfast · 2026-10-01'});
 await dialog.getByRole('button',{name:'Create grocery'}).click();
 await expect(dialog).toHaveCount(0);
 const item=page.locator('.task-detail').filter({hasText:'Test oats'});
 await expect(item).toContainText('$1.99');await expect(item).toContainText('October breakfast');
});
test('transaction paging and category drill-down preserve the selected month',async({page})=>{
 await page.goto('/finance/transactions');await expect(page.locator('tbody tr')).toHaveCount(12);
 await page.getByRole('button',{name:'Next transaction page'}).click();await expect(page.locator('.transaction-pagination')).toContainText('Showing 13–24');
 await page.getByLabel('Transaction category').selectOption('Food');await expect(page.locator('.transaction-pagination')).toContainText('Showing 1–12');
 await page.goto('/');await page.getByLabel('Selected month').fill('2026-08');
 await page.getByRole('button',{name:'Quick add',exact:true}).click();await page.getByRole('button',{name:'Transaction',exact:true}).click();
 await page.getByRole('dialog').getByLabel('Description',{exact:true}).fill('August expense');await page.getByRole('dialog').getByLabel('Amount',{exact:true}).fill('50.00');await page.getByRole('button',{name:'Create transaction'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.locator('.spending-legend button').filter({hasText:'Essentials'}).click();
 await expect(page.getByLabel('Selected month')).toHaveValue('2026-08');await expect(page.getByLabel('Transaction category')).toHaveValue('Essentials');
});
test('mobile transactions use readable rows with working edit controls',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/finance/transactions');await page.getByLabel('Transaction category').selectOption('Food');
 await expect(page.locator('.records-panel .table-scroll')).toBeHidden();await expect(page.locator('.mobile-transaction-list')).toBeVisible();
 const first=page.locator('.mobile-transaction').first();await first.getByRole('button',{name:/^Edit /}).click();
 await page.getByRole('dialog').getByLabel('Amount',{exact:true}).fill('5.25');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(first).toContainText('$5.25');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
