import {test,expect} from '@playwright/test';
import {demoSnapshot,recordsOf,plans,type Snapshot,type Plan} from '../../packages/shared/src/index';
function fixture():Snapshot{const s=demoSnapshot();s.profile={...s.profile,name:'Plan fixture',email:'plan-fixture@example.com',plan:'Free',onboardingCompletedAt:'2026-09-01T00:00:00Z',allowances:{tasks:5,habits:3,goals:3,transactions:100,automations:0,emails:0}};s.records=recordsOf(s.records,'task').slice(0,5).map(r=>({...r,data:{...r.data,done:false,completedAt:null}}));return s;}
test('Free cap prompts on every extra add; completion and saves update remaining allowance',async({page})=>{
 const s=fixture();await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:s.profile.name,email:s.profile.email,status:'active'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',r=>r.fulfill({json:s}));
 await page.route('**/backend/api/records**',async r=>{const input=r.request().postDataJSON();if(r.request().method()==='PATCH'){const id=r.request().url().split('/').at(-1)!;const old=s.records.find(x=>x.id===id)!;const saved={...old,data:input.data,version:old.version+1};s.records=s.records.map(x=>x.id===id?saved:x) as Snapshot['records'];await r.fulfill({json:saved});}else{const saved={id:'new-free-task',kind:'task',data:input.data,version:1};s.records.push(saved as Snapshot['records'][number]);await r.fulfill({status:201,json:saved});}});
 await page.goto('/tasks');await expect(page.getByRole('heading',{name:'Upgrade your Daily Ledger'})).toBeVisible();await expect(page.locator('.desktop-upgrade-cards')).toBeVisible();await page.screenshot({path:'artifacts/compact-upgrade.png'});await page.getByRole('button',{name:'Continue with Free',exact:true}).click();
 for(let i=0;i<2;i++){await page.getByRole('button',{name:'New task',exact:true}).click();await expect(page.getByRole('heading',{name:'Upgrade your Daily Ledger'})).toBeVisible();await expect(page.locator('.desktop-upgrade-cards')).toBeVisible();await page.screenshot({path:'artifacts/compact-upgrade.png'});await page.getByRole('button',{name:'Continue with Free',exact:true}).click();}
 await page.getByRole('checkbox',{name:`Complete ${recordsOf(s.records,'task')[0].data.title}`,exact:true}).first().click();await page.locator('.sidebar').getByRole('link',{name:'Settings',exact:true}).click();const tasks=page.locator('.plan-usage-row').filter({hasText:'Active tasks'});await expect(tasks).toContainText('4 / 5');await expect(tasks).toContainText('1 remaining');
 await page.locator('.sidebar').getByRole('link',{name:'Tasks & Habits',exact:true}).click();await page.getByRole('button',{name:'New task',exact:true}).click();await page.getByRole('dialog').getByLabel('Task title',{exact:true}).fill('My fifth free task');await page.getByRole('button',{name:'Create task',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.locator('.sidebar').getByRole('link',{name:'Settings',exact:true}).click();await expect(tasks).toContainText('5 / 5');await expect(tasks).toContainText('0 remaining');await page.reload();await expect(page.getByRole('heading',{name:'Upgrade your Daily Ledger'})).toHaveCount(0);
});
test('admin plan changes refresh without a page reload; Lifetime switch sends a request without activation',async({page})=>{
 const s=fixture();let billing=0,submitted:any;page.on('request',r=>{if(r.url().includes('/billing/'))billing++;});await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:s.profile.name,email:s.profile.email,status:'active'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',r=>r.fulfill({json:s}));await page.route('**/backend/api/support',r=>{submitted=r.request().postDataJSON();return r.fulfill({status:201,json:{id:'plan-request'}});});
 await page.goto('/settings');await page.getByRole('button',{name:'Continue with Free',exact:true}).click();await page.locator('.sidebar').evaluate(el=>el.setAttribute('data-retained','yes'));
 const setPlan=(plan:Plan)=>{s.profile.plan=plan;s.profile.allowances=Object.fromEntries(['tasks','habits','goals','transactions','automations','emails'].map(k=>[k,Number.isFinite(plans[plan][k as keyof typeof plans.Free] as number)?plans[plan][k as keyof typeof plans.Free]:null])) as Record<string,number|null>;};setPlan('Pro');await expect(page.locator('.plan-summary h2')).toHaveText('Pro plan',{timeout:25000});await expect(page.locator('.sidebar')).toHaveAttribute('data-retained','yes');await expect(page.locator('.account-loading')).toHaveCount(0);
 await page.getByRole('link',{name:'Compare plans & Lifetime',exact:true}).click();await expect(page).toHaveURL(/\/plans$/);await page.getByRole('button',{name:'Switch to Lifetime',exact:true}).click();await page.getByRole('button',{name:'Send plan request',exact:true}).click();await expect(page.getByRole('heading',{name:'Request sent',exact:true})).toBeVisible();expect(submitted.category).toBe('billing');expect(submitted.body).toContain('Pro to Lifetime');expect(billing).toBe(0);expect(s.profile.plan).toBe('Pro');await page.getByRole('button',{name:'Done',exact:true}).click();setPlan('Lifetime');await expect(page.locator('.plan-summary h2')).toHaveText('Lifetime plan',{timeout:25000});
});
test('paid guides are gated while Free tracking remains available; plans and Settings fit mobile',async({page})=>{
 const s=fixture();await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:s.profile.name,email:s.profile.email,status:'active'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',r=>r.fulfill({json:s}));await page.goto('/fitness/exercises/biceps-curl');await page.getByRole('button',{name:'Continue with Free',exact:true}).click();await expect(page.locator('.premium-feature')).toContainText('complete exercise guide');await expect(page.locator('.anatomy-view')).toHaveCount(0);await page.goto('/meals/planner');await expect(page.locator('.premium-feature')).toContainText('weekly meal plan');await page.goto('/goals');await expect(page.getByRole('button',{name:'New goal',exact:true})).toBeVisible();await expect(page.locator('.goal-presets')).toHaveCount(0);
 for(const width of [360,390,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['/plans','/settings']){await page.goto(route);await expect(page.locator('.plan-summary')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/plans-${route.slice(1)}-${width}.png`,fullPage:true});}}
});

test('mobile upgrade prompt stacks both plans and respects reduced motion',async({page})=>{
 const s=fixture();await page.setViewportSize({width:390,height:844});await page.route('**/backend/auth/me',r=>r.fulfill({json:{user:{name:s.profile.name,email:s.profile.email,status:'active'},csrf:'fixture'}}));await page.route('**/backend/api/snapshot',r=>r.fulfill({json:s}));await page.goto('/tasks');await expect(page.getByRole('heading',{name:'Upgrade your Daily Ledger'})).toBeVisible();await expect(page.locator('.compact-upgrade')).toBeHidden();await expect(page.locator('.desktop-upgrade')).toBeVisible();const cards=page.locator('.desktop-upgrade-card');const first=await cards.nth(0).boundingBox(),second=await cards.nth(1).boundingBox();expect(second!.y).toBeGreaterThan(first!.y+first!.height);expect(await page.getByRole('dialog').evaluate(el=>el.getBoundingClientRect().height)).toBeLessThanOrEqual(820);await expect(cards.first()).toHaveCSS('animation-name','desktop-upgrade-in');await page.getByRole('heading',{name:'Upgrade your Daily Ledger',exact:true}).click();await page.screenshot({path:'artifacts/upgrade-mobile-plans.png'});await page.emulateMedia({reducedMotion:'reduce'});await expect(cards.first()).toHaveCSS('animation-name','none');await page.getByRole('button',{name:'Continue with Free',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
});