import {test,expect} from '@playwright/test';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
import {readFileSync,existsSync} from 'node:fs';
import {parse} from 'dotenv';
import signature from 'cookie-signature';
const origin=process.env.WEB_TEST_URL||'http://localhost:3000';
const env=existsSync('apps/api/.env')?parse(readFileSync('apps/api/.env')):process.env;const userId=randomUUID(),otherId=randomUUID();let pool:pg.Pool;
let adminId:string,adminVersion:number;const sessionIds:string[]=[];let ticketId='';
async function session(context:any,id:string,admin=false){const sid=randomUUID(),csrf=randomUUID();sessionIds.push(sid);await pool.query("INSERT INTO session (sid,sess,expire) VALUES ($1,$2,NOW()+INTERVAL '1 hour')",[sid,JSON.stringify({cookie:{originalMaxAge:3600000,httpOnly:true,secure:false,sameSite:'lax',path:'/'},passport:{user:id},csrf,...(admin?{adminUserId:id,adminVersion}: {})})]);await context.addCookies([{name:'ledger.sid',value:'s:'+signature.sign(sid,process.env.TEST_SESSION_SECRET||env.SESSION_SECRET),domain:'localhost',path:'/',httpOnly:true,sameSite:'Lax'}]);return csrf;}
test.beforeAll(async()=>{test.skip(!process.env.TEST_DATABASE_URL,'Local test database required');pool=new pg.Pool({connectionString:process.env.TEST_DATABASE_URL});const admin=(await pool.query('SELECT "userId",version FROM "AdminAccess" WHERE id=1 AND active=true')).rows[0];test.skip(!admin,'Selected administrator required');adminId=admin.userId;adminVersion=admin.version;await pool.query('INSERT INTO "User" (id,email,name,"onboardingCompletedAt") VALUES ($1,$2,$3,NOW()),($4,$5,$6,NOW())',[userId,`support-${userId}@example.com`,'Support Test',otherId,`support-${otherId}@example.com`,'Other Test']);});
test.afterAll(async()=>{if(!pool)return;if(ticketId)await pool.query('DELETE FROM "AdminAudit" WHERE target=$1',[ticketId]);await pool.query('DELETE FROM "AdminAudit" WHERE target=$1 AND reason=$2',[userId,'Support test manual assignment']);await pool.query('DELETE FROM session WHERE sid=ANY($1)',[sessionIds]);await pool.query('DELETE FROM "User" WHERE id=ANY($1)',[[userId,otherId]]);await pool.end();});
test('real customer ticket reaches admin, replies persist, ownership and plan assignments are protected',async({page,browser})=>{
 const csrf=await session(page.context(),userId);await page.goto('/help');await page.getByRole('button',{name:'Continue with Free',exact:true}).click();await expect(page.getByRole('heading',{name:'A little help. A clearer day.'})).toBeVisible();await page.getByRole('button',{name:'New ticket',exact:true}).click();await page.getByLabel('Subject',{exact:true}).fill('Budget currency dropdown issue');await page.getByLabel('What happened?',{exact:true}).fill('The currency dropdown was white on my laptop. Please help me find the right setting.');await page.getByRole('button',{name:'Send ticket',exact:true}).click();await expect(page.getByText('Ticket sent. You can follow the conversation here.')).toBeVisible();await expect(page.locator('.support-thread h3')).toHaveText('Budget currency dropdown issue');ticketId=(await page.request.get('/backend/api/support').then(r=>r.json())).tickets[0].id;
 expect((await page.request.patch('/backend/api/admin/support/'+ticketId,{headers:{Origin:origin,'X-CSRF-Token':csrf},data:{status:'resolved',version:1}})).status()).toBe(403);
 expect((await page.request.post('/backend/api/support/'+ticketId+'/messages',{data:{body:'A missing CSRF request.',version:1}})).status()).toBe(403);
 const other=await browser.newContext();await session(other,otherId);expect((await other.request.get(origin+'/backend/api/support/'+ticketId)).status()).toBe(404);expect((await other.request.get(origin+'/backend/api/support').then(r=>r.json())).tickets).toHaveLength(0);await other.close();
 const adminContext=await browser.newContext();const adminCsrf=await session(adminContext,adminId,true);const adminPage=await adminContext.newPage();await adminPage.goto('/admin/support');await adminPage.getByRole('button',{name:/Budget currency dropdown issue/}).click();await expect(adminPage.locator('.support-thread h3')).toHaveText('Budget currency dropdown issue');await adminPage.getByLabel('Reply message').fill('We have updated the selector. Please open Settings and choose your currency.');await adminPage.getByRole('button',{name:'Send reply',exact:true}).click();await expect(adminPage.locator('.support-message.admin')).toContainText('We have updated the selector.');await adminPage.getByLabel('Update ticket status').selectOption('resolved');await expect(adminPage.locator('.support-thread-heading .support-status')).toHaveText('Resolved');await page.getByRole('button',{name:'Refresh conversation'}).click();await expect(page.locator('.support-message.admin')).toContainText('We have updated the selector.');await expect(page.locator('.support-thread-heading .support-status')).toHaveText('Resolved');
 await page.getByLabel('Reply message').fill('Thank you. I have one more question about my currency.');await page.getByRole('button',{name:'Send reply',exact:true}).click();await expect(page.locator('.support-thread-heading .support-status')).toHaveText('Open');
 expect((await page.request.post('/backend/api/support/'+ticketId+'/messages',{headers:{Origin:origin,'X-CSRF-Token':csrf},data:{body:'A stale version should be rejected.',version:1}})).status()).toBe(409);
 for(const plan of ['Pro','Lifetime','Free']){const r=await adminPage.request.post('/backend/api/admin/users/'+userId+'/action',{headers:{Origin:origin,'X-CSRF-Token':adminCsrf},data:{action:'set-plan',plan,reason:'Support test manual assignment'}});expect(r.status()).toBe(200);expect((await page.request.get('/backend/api/snapshot').then(r=>r.json())).profile.plan).toBe(plan);}
 await pool.query('DELETE FROM "AdminAudit" WHERE target=$1 AND reason=$2',[userId,'Support test manual assignment']);
 for(const width of [360,390,768,1024,1440,1920]){await page.setViewportSize({width,height:900});await page.evaluate(()=>window.scrollTo(0,0));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),String(width)).toBe(true);await page.screenshot({path:`artifacts/support-${width}.png`,fullPage:true});await adminPage.setViewportSize({width,height:900});await adminPage.evaluate(()=>window.scrollTo(0,0));expect(await adminPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'admin '+width).toBe(true);await adminPage.screenshot({path:`artifacts/admin-support-${width}.png`,fullPage:true});}
 await adminPage.setViewportSize({width:1440,height:900});await adminPage.goto('/admin/users/'+userId);await adminPage.getByRole('button',{name:'Change plan',exact:true}).click();await adminPage.getByLabel('Grant plan').selectOption('Lifetime');await adminPage.getByLabel('Reason',{exact:true}).fill('Support test manual assignment');await adminPage.getByRole('button',{name:'Confirm action',exact:true}).click();await expect(adminPage.locator('.admin-notice')).toContainText('Changes saved.');expect((await page.request.get('/backend/api/snapshot').then(r=>r.json())).profile.plan).toBe('Lifetime');await adminPage.goto('/admin/plans');await expect(adminPage.getByText('Assign a plan to a customer',{exact:true})).toBeVisible();await expect(adminPage.getByText('Allowance configuration',{exact:true})).not.toBeVisible();await adminPage.getByText('Advanced allowance settings & history',{exact:true}).click();await expect(adminPage.getByText('Allowance configuration',{exact:true})).toBeVisible();await expect(adminPage.locator('select option:not(:checked)').first()).toHaveCSS('background-color','rgb(23, 23, 23)');await adminPage.screenshot({path:'artifacts/admin-plans-polished.png',fullPage:true});
 await adminContext.close();
});
test('worldwide currency picker saves preferences and remains dark in record forms',async({page})=>{
 await session(page.context(),userId);await page.goto('/settings');if((await pool.query('SELECT plan FROM "User" WHERE id=$1',[userId])).rows[0].plan==='Free')await page.getByRole('button',{name:'Continue with Free',exact:true}).click();await page.getByRole('button',{name:'Currency',exact:true}).click();await page.getByRole('textbox',{name:'Search currencies'}).fill('yen');await page.getByRole('button',{name:/JPY Japanese Yen/}).click();await page.getByRole('button',{name:'Save preferences',exact:true}).click();await expect(page.getByText('Preferences saved.',{exact:false})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'Currency',exact:true})).toContainText('JPY');await page.getByRole('button',{name:'Currency',exact:true}).click();await page.getByRole('textbox',{name:'Search currencies'}).fill('Kuwaiti');await page.getByRole('button',{name:/KWD Kuwaiti Dinar/}).click();await page.getByRole('button',{name:'Save preferences',exact:true}).click();await expect(page.getByText('Preferences saved.',{exact:false})).toBeVisible();await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Currency',exact:true}).click();await page.getByRole('textbox',{name:'Search currencies'}).fill('PKR');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/currency-picker-mobile.png',fullPage:true});await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Currency',exact:true})).toBeFocused();
 await page.goto('/finance/budgets');await page.getByRole('button',{name:/New budget|Add budget/i}).first().click();await page.getByRole('button',{name:'Currency',exact:true}).click();await expect(page.getByRole('textbox',{name:'Search currencies'})).toBeVisible();expect(await page.locator('.currency-list button').count()).toBeGreaterThan(150);await page.keyboard.press('Escape');await page.keyboard.press('Escape');
});
