import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {randomUUID} from 'node:crypto';
import {createRequire} from 'node:module';
import pg from 'pg';
import {hashPassword} from '../apps/api/src/passwords.js';
const sign=createRequire(import.meta.url)('cookie-signature').sign;
const url=process.env.TEST_DATABASE_URL;
test('singleton admin, explicit admin login, isolation, suspension, overrides, planning and AI limits',{skip:!url,timeout:120000},async()=>{
 const pool=new pg.Pool({connectionString:url});assert.equal((await pool.query('SELECT count(*) FROM "AdminAccess"')).rows[0].count,'0','Use a disposable DB with no selected real administrator.');const users=[randomUUID(),randomUUID(),randomUUID()];const csrf='b'.repeat(64);const secret='admin-integration-test-secret-at-least-32-characters';const origin='http://localhost:3000';const password='Fixture-only-test!2026';const modelRequests:any[]=[];
 const provider=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;modelRequests.push(JSON.parse(body));res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'Test fixture response, not a production AI answer.'}}],usage:{prompt_tokens:100,completion_tokens:20}}));});await new Promise<void>(resolve=>provider.listen(0,'127.0.0.1',resolve));const providerPort=(provider.address() as any).port;const base='http://localhost:4012';
 const oldSettings=(await pool.query('SELECT * FROM "PlatformConfig" WHERE id=1')).rows[0];const processApi=spawn(process.execPath,['--import','tsx','apps/api/src/server.ts'],{env:{...process.env,DATABASE_URL:url,SESSION_SECRET:secret,FRONTEND_ORIGIN:origin,PORT:'4012',NODE_ENV:'development',AI_PROVIDER:'openai-compatible',AI_BASE_URL:`http://127.0.0.1:${providerPort}/v1`,AI_MODEL:'fixture-model',AI_API_KEY:'fixture-key',RESEND_API_KEY:'',EMAIL_FROM:''},windowsHide:true,stdio:'pipe'});let logs='';processApi.stdout.on('data',d=>logs+=d);processApi.stderr.on('data',d=>logs+=d);
 type Client={cookie:string;csrf:string};async function call(c:Client,path:string,method='GET',body?:unknown){const response=await fetch(base+path,{method,headers:{Cookie:c.cookie,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':c.csrf},...(body?{body:JSON.stringify(body)}:{})});const next=response.headers.getSetCookie().find(v=>v.startsWith('ledger.sid='));if(next)c.cookie=next.split(';')[0];return {status:response.status,data:await response.json().catch(()=>null)};}
 async function ordinary(userId:string){const sid=randomUUID();await pool.query('INSERT INTO session (sid,sess,expire) VALUES ($1,$2,NOW()+INTERVAL \'1 hour\')',[sid,JSON.stringify({cookie:{originalMaxAge:3600000,expires:new Date(Date.now()+3600000).toISOString(),httpOnly:true,path:'/',sameSite:'lax'},passport:{user:userId},csrf})]);return {cookie:'ledger.sid='+encodeURIComponent('s:'+sign(sid,secret)),csrf};}
 async function adminLogin(index:number){const c={cookie:'',csrf:''};const boot=await call(c,'/auth/csrf');c.csrf=boot.data.csrf;const result=await call(c,'/auth/admin/login','POST',{email:`admin-fixture-${users[index]}@example.com`,password});assert.equal(result.status,200);const me=await call(c,'/api/admin/me');assert.equal(me.status,200);c.csrf=me.data.csrf;return c;}
 try{
  const hash=await hashPassword(password);for(const id of users){await pool.query('INSERT INTO "User" (id,email,name,role) VALUES ($1,$2,$3,$4)',[id,`admin-fixture-${id}@example.com`,'Admin test account','admin']);await pool.query('INSERT INTO "PasswordCredential" (id,"userId",email,"passwordHash","updatedAt") VALUES ($1,$2,$3,$4,NOW())',[randomUUID(),id,`admin-fixture-${id}@example.com`,hash]);}
  await pool.query('INSERT INTO "AdminAccess" (id,"userId","updatedAt") VALUES (1,$1,NOW())',[users[0]]);await assert.rejects(pool.query('INSERT INTO "AdminAccess" (id,"userId","updatedAt") VALUES (2,$1,NOW())',[users[1]]));
  let ready=false;for(let i=0;i<400;i++){try{if((await fetch(base+'/health')).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(ready,logs);
  const normal=await ordinary(users[0]);for(const route of ['overview','users','plans','announcements','automations','reports','ai','settings','audit'])assert.equal((await call(normal,'/api/admin/'+route)).status,403,route);
  const bad={cookie:'',csrf:''};bad.csrf=(await call(bad,'/auth/csrf')).data.csrf;assert.equal((await call(bad,'/auth/admin/login','POST',{email:`admin-fixture-${users[1]}@example.com`,password})).status,401);
  let admin=await adminLogin(0);const user=await ordinary(users[2]);const other=await ordinary(users[1]);assert.equal((await call(admin,'/api/admin/overview')).data.totalUsers>=3,true);
  const setup={name:'Admin test account',currency:'USD',timezone:'UTC',persona:'Developer',focusAreas:['finance','tasks'],referralSource:'Fixture'};assert.equal((await call({...user,csrf:''},'/api/onboarding','POST',setup)).status,403);assert.equal((await call(user,'/api/onboarding','POST',{...setup,persona:'admin'})).status,400);const completed=await call(user,'/api/onboarding','POST',{...setup,userId:users[1],role:'admin'});assert.equal(completed.status,200);const again=await call(user,'/api/onboarding','POST',{...setup,persona:'Designer'});assert.equal(again.data.completedAt,completed.data.completedAt);assert.equal((await call(user,'/api/snapshot')).data.profile.persona,'Developer');assert.equal((await call(other,'/api/snapshot')).data.profile.onboardingCompletedAt,null);
  await call(user,'/api/records','POST',{kind:'transaction',data:{title:'PRIVATE_OWN_ENTRY',date:new Date().toISOString().slice(0,10),type:'expense',amount:12345,currency:'USD',category:'Food',account:'Cash',notes:'PRIVATE_OWN_NOTE'}});await call(other,'/api/records','POST',{kind:'transaction',data:{title:'OTHER_USER_SECRET',date:new Date().toISOString().slice(0,10),type:'expense',amount:999888,currency:'USD',category:'OTHER_CATEGORY_SECRET',account:'Cash',notes:''}});
  const detail=await call(admin,'/api/admin/users/'+users[2]);assert.equal(detail.status,200);assert.ok(!JSON.stringify(detail.data).includes('PRIVATE_OWN_ENTRY'));assert.equal(detail.data.usage.transactions,1);
  assert.equal((await call(admin,'/api/admin/users/'+users[2]+'/action','POST',{action:'grant',plan:'Pro',expiresAt:new Date(Date.now()+86400000).toISOString(),reason:'Fixture entitlement for verification'})).status,200);assert.equal((await call(user,'/api/snapshot')).data.profile.plan,'Pro');assert.deepEqual((await call(admin,'/api/admin/overview')).data.revenue,{});
  const month=new Date().toISOString().slice(0,7);const plan=await call(user,'/api/records','POST',{kind:'cashPlan',data:{title:'Fixture salary',amount:250000,currency:'USD',type:'income',category:'Salary',account:'Checking',day:31,active:true,notes:''}});assert.equal(plan.status,201);const payments=await Promise.all([1,2].map(()=>call(user,`/api/finance/plans/${plan.data.id}/settle`,'POST',{month,date:new Date().toISOString().slice(0,10),version:1})));assert.equal(payments[0].status,200);assert.equal(payments[0].data.id,payments[1].data.id);assert.equal((await call(other,`/api/finance/plans/${plan.data.id}/settle`,'POST',{month,date:new Date().toISOString().slice(0,10),version:1})).status,404);
  assert.equal((await call(user,'/api/ai/chat','POST',{requestId:randomUUID(),month,intent:'summary',question:'Summarize'})).status,503);
  const settings=(await call(admin,'/api/admin/settings')).data;settings.settings.aiEnabled=true;settings.settings.aiAllowances.Pro={requests:1,tokens:20000};assert.equal((await call(admin,'/api/admin/settings','PATCH',{settings:settings.settings,version:settings.version,reason:'Enable loopback fixture provider'})).status,200);
  const replies=await Promise.all([1,2,3].map(()=>call(user,'/api/ai/chat','POST',{requestId:randomUUID(),month,intent:'spending',question:'Summarize my categories'})));assert.equal(replies.filter(r=>r.status===200).length,1);assert.equal(replies.filter(r=>r.status===429).length,2);assert.equal(modelRequests.length,1);const sent=JSON.stringify(modelRequests[0]);assert.ok(sent.includes('12345'));assert.ok(!sent.includes('OTHER_CATEGORY_SECRET'));assert.ok(!sent.includes('PRIVATE_OWN_NOTE'));assert.ok(!sent.includes(password));assert.equal((await call(other,'/api/ai/history')).data.messages.length,0);assert.equal((await call(user,'/api/ai/history')).data.messages.length,1);assert.equal((await call(user,'/api/ai/history','DELETE')).status,204);assert.equal((await call(user,'/api/ai/history')).data.messages.length,0);assert.equal((await call(user,'/api/ai/chat','POST',{requestId:randomUUID(),month,intent:'summary',question:'Again'})).status,429);
  const savedDraft=await call(admin,'/api/admin/announcements','POST',{status:'draft',reason:'Local draft verification only',data:{title:'Fixture draft',description:'Never published',audience:'Everyone',priority:1,version:1,publishAt:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString(),followup:false}});assert.equal(savedDraft.status,200);assert.ok(!(await call(user,'/api/snapshot')).data.records.some((r:any)=>r.id===savedDraft.data.id));assert.equal((await call(admin,'/api/admin/test-email','POST',{reason:'Test unavailable provider state'})).status,503);
  assert.equal((await call(admin,'/api/admin/users/'+users[2]+'/action','POST',{action:'suspend',reason:'Fixture suspension check'})).status,200);assert.equal((await call(user,'/api/snapshot')).status,403);assert.equal((await call(user,'/auth/me')).data.user.status,'suspended');const suspended=await ordinary(users[2]);assert.equal((await call(suspended,'/api/snapshot')).status,403);assert.equal((await call(suspended,'/api/records','POST',{kind:'task',data:{}})).status,403);assert.equal((await call(admin,'/api/admin/users/'+users[2]+'/action','POST',{action:'reactivate',reason:'Restore fixture account'})).status,200);
  assert.equal((await call(admin,'/api/admin/users/'+users[2]+'/action','POST',{action:'remove-override',reason:'Verify base entitlement restored'})).status,200);assert.equal((await call(suspended,'/api/snapshot')).data.profile.plan,'Free');
  const input={plan:'Free',allowances:{tasks:0,habits:3,goals:3,transactions:100,automations:0,emails:0},scope:'all-accounts',effectiveAt:new Date().toISOString(),reason:'Fixture allowance enforcement'};const preview=await call(admin,'/api/admin/plans/preview','POST',input);assert.equal(preview.status,200);assert.equal((await call(admin,'/api/admin/plans','POST',{...input,digest:preview.data.digest})).status,200);assert.equal((await call(suspended,'/api/records','POST',{kind:'task',data:{title:'Cannot create',due:new Date().toISOString(),priority:'medium',done:false,reminder:false,recurrence:'none'}})).status,403);
  const transfer=spawn(process.execPath,['--import','tsx','apps/api/src/admin-cli.ts','select',users[1],'Transfer fixture administrator'],{env:{...process.env,DATABASE_URL:url,SESSION_SECRET:secret},windowsHide:true,stdio:'pipe'});await new Promise<void>((resolve,reject)=>transfer.once('exit',code=>code===0?resolve():reject(new Error('Transfer command failed'))));assert.equal((await call(admin,'/api/admin/me')).status,401);admin=await adminLogin(1);assert.equal((await call(admin,'/api/admin/me')).data.user.id,users[1]);const audit=await call(admin,'/api/admin/audit');assert.ok(!JSON.stringify(audit.data).includes(password));assert.ok(!JSON.stringify(audit.data).includes('passwordHash'));
  let limited;for(let i=0;i<6;i++)limited=await call(bad,'/auth/admin/login','POST',{email:`admin-fixture-${users[0]}@example.com`,password:'Wrong-fixture-password!'});assert.equal(limited!.status,429);assert.match(limited!.data.error,/Too many failed sign-in attempts/);
  await pool.query('DELETE FROM "Announcement" WHERE id=$1',[savedDraft.data.id]);
 }finally{processApi.kill();await new Promise<void>(resolve=>{if(processApi.exitCode!==null)resolve();else{processApi.once('exit',()=>resolve());setTimeout(resolve,3000);}});await pool.query('DELETE FROM "AdminAccess" WHERE "userId"=ANY($1)',[users]);await pool.query('DELETE FROM "PolicyVersion" WHERE "actorId"=ANY($1)',[users]);await pool.query('DELETE FROM "AdminAudit" WHERE "actorId"=ANY($1) OR target=ANY($1)',[users]);await pool.query('DELETE FROM "Announcement" WHERE data->>\'title\'=\'Fixture draft\'');await pool.query('DELETE FROM "User" WHERE id=ANY($1)',[users]);await pool.query('DELETE FROM session WHERE sess->\'passport\'->>\'user\'=ANY($1)',[users]);if(oldSettings)await pool.query('UPDATE "PlatformConfig" SET data=$1,version=$2,"updatedAt"=$3 WHERE id=1',[oldSettings.data,oldSettings.version,oldSettings.updatedAt]);else await pool.query('DELETE FROM "PlatformConfig" WHERE id=1');await pool.end();await new Promise<void>(resolve=>provider.close(()=>resolve()));}
});

