export const muscleGroups=['Full body','Chest','Back','Shoulders','Biceps','Triceps','Forearms','Core','Glutes','Quads','Hamstrings','Calves'] as const;
export type MuscleGroup=typeof muscleGroups[number];
export const exerciseSource='https://www.acefitness.org/resources/everyone/exercise-library/';
const exercises=[
 {name:'Incline push-up',muscle:'Chest',secondary:'Triceps · Shoulders',equipment:'Bodyweight',tips:['Use a stable raised surface.','Keep your body aligned.'],reps:'8–12'},
 {name:'Dumbbell chest press',muscle:'Chest',secondary:'Triceps · Shoulders',equipment:'Dumbbells',tips:['Use a stable bench.','Lower the weights slowly.'],reps:'8–12'},
 {name:'One-arm dumbbell row',muscle:'Back',secondary:'Biceps',equipment:'Dumbbells',tips:['Support your torso.','Pull without twisting.'],reps:'8–12 / side'},
 {name:'Lat pulldown',muscle:'Back',secondary:'Biceps',equipment:'Machine',tips:['Pull in front of you.','Avoid leaning far back.'],reps:'8–12'},
 {name:'Dumbbell shoulder press',muscle:'Shoulders',secondary:'Triceps',equipment:'Dumbbells',tips:['Brace your torso.','Avoid arching your back.'],reps:'8–12'},
 {name:'Dumbbell lateral raise',muscle:'Shoulders',secondary:'Upper back',equipment:'Dumbbells',tips:['Use light weights.','Avoid swinging.'],reps:'8–12'},
 {name:'Biceps curl',muscle:'Biceps',secondary:'Forearms',equipment:'Dumbbells',tips:['Keep elbows near your sides.','Lower with control.'],reps:'8–12'},
 {name:'Cable triceps pushdown',muscle:'Triceps',secondary:'Forearms',equipment:'Machine',tips:['Keep elbows steady.','Control the return.'],reps:'8–12'},
 {name:'Farmer carry',muscle:'Forearms',secondary:'Core · Upper back',equipment:'Dumbbells',tips:['Walk tall.','Use manageable weights.'],reps:'20–30 seconds'},
 {name:'Forearm plank',muscle:'Core',secondary:'Shoulders',equipment:'Bodyweight',tips:['Keep hips aligned.','Breathe throughout.'],reps:'15–30 seconds'},
 {name:'Glute bridge',muscle:'Glutes',secondary:'Hamstrings',equipment:'Bodyweight',tips:['Press through your feet.','Avoid overextending your back.'],reps:'8–12'},
 {name:'Bodyweight squat',muscle:'Quads',secondary:'Glutes · Core',equipment:'Bodyweight',tips:['Keep knees tracking over feet.','Use a comfortable depth.'],reps:'8–12'},
 {name:'Dumbbell Romanian deadlift',muscle:'Hamstrings',secondary:'Glutes · Back',equipment:'Dumbbells',tips:['Hinge at the hips.','Keep your back neutral.'],reps:'8–12'},
 {name:'Seated leg curl',muscle:'Hamstrings',secondary:'Calves',equipment:'Machine',tips:['Adjust the machine first.','Avoid jerking the weight.'],reps:'8–12'},
 {name:'Standing calf raise',muscle:'Calves',secondary:'Lower legs',equipment:'Bodyweight',tips:['Use support for balance.','Lift and lower slowly.'],reps:'8–12'},
] as const;
// Original summaries of the cited exercise guidance; illustrations show approximate regions.
const details=[
 {source:'https://www.acefitness.org/resources/pros/expert-articles/8972/be-a-chest-day-champion-an-evidence-based-approach-to-training-the-chest/',setup:'Place your hands on a fixed bench or wall, slightly wider than your shoulders. Step back into a straight line.',steps:['Brace your abdomen and bend your elbows to bring your chest toward the support.','Keep your head, hips and heels aligned as you lower.','Press the surface away and return with control, breathing out.'],mistakes:['Using a surface that can slide.','Letting the hips sag or shoulders shrug.'],easier:'Use a higher stable surface, such as a wall. Lower the incline only when you can control each repetition.'},
 {source:exerciseSource+'19/chest-press/',setup:'Lie on a stable bench with feet supported. Hold a manageable dumbbell in each hand above the chest, with wrists straight.',steps:['Set your shoulders against the bench and keep your head and hips supported.','Lower both weights slowly toward chest level within a comfortable range.','Breathe out and press upward without bouncing or over-arching your lower back.'],mistakes:['Bending wrists backward.','Bouncing the weights or lifting the hips.'],easier:'Use lighter weights or a floor press to limit the lowering range. Ask a trainer for help positioning weights.'},
 {source:exerciseSource+'126/single-arm-row/',setup:'Support one hand and knee on a stable bench. Place the other foot firmly on the floor and hold a dumbbell below the shoulder.',steps:['Keep your spine neutral and torso steady.','Pull the elbow toward your hip without turning your chest.','Lower the weight smoothly and repeat before changing sides.'],mistakes:['Rotating the torso to lift more weight.','Shrugging or jerking the dumbbell upward.'],easier:'Choose a lighter weight and shorten the range while keeping your trunk still.'},
 {source:exerciseSource+'158/seated-lat-pulldown/',setup:'Adjust the thigh pad so you sit securely. Grip the bar comfortably wider than shoulder width, with your chest upright.',steps:['Draw your shoulders down and pull the bar in front toward your upper chest.','Keep the torso mostly still and avoid pulling behind the neck.','Let the bar rise under control as your arms extend.'],mistakes:['Swinging the torso backward.','Pulling behind the head or yanking the stack.'],easier:'Reduce the load and use a comfortable grip; ask a trainer to adjust the machine.'},
 {source:exerciseSource+'45/seated-overhead-press/',setup:'Sit on a stable supported bench with feet grounded. Hold dumbbells near shoulder height and keep your wrists aligned.',steps:['Brace your abdomen without leaning backward.','Press overhead through a comfortable shoulder range.','Lower slowly to the starting position while maintaining support.'],mistakes:['Arching the back to finish the press.','Choosing weights that force an uneven movement.'],easier:'Use lighter weights and a comfortable range; avoid overhead work that causes pain.'},
 {source:exerciseSource+'26/lateral-raise/',setup:'Stand tall with light dumbbells at your sides and a small bend in the elbows.',steps:['Raise the arms out to the sides in a controlled arc.','Stop around shoulder height or earlier if needed for comfort.','Lower gently without swinging your body.'],mistakes:['Swinging heavy weights.','Shrugging the shoulders or raising beyond a comfortable range.'],easier:'Start without weights, then add a light load once movement stays controlled.'},
 {source:exerciseSource+'44/seated-biceps-curl/',setup:'Sit or stand tall with dumbbells at your sides, palms forward and elbows close to your torso.',steps:['Bend the elbows to bring the weights toward your shoulders.','Keep the upper arms still and wrists neutral.','Lower slowly without letting the weights drop.'],mistakes:['Rocking backward to lift.','Moving the elbows forward for every repetition.'],easier:'Use lighter weights or alternate arms while keeping your posture steady.'},
 {source:exerciseSource+'185/triceps-pushdowns/',setup:'Use a high cable attachment. Stand with knees soft and elbows tucked beside your ribs.',steps:['Brace your torso and straighten the elbows to press the attachment down.','Keep the shoulders and upper arms still.','Return slowly to bent elbows without letting the stack slam.'],mistakes:['Leaning your body weight onto the handle.','Letting the elbows flare or move with each repetition.'],easier:'Reduce the load and ask a trainer to check attachment height and grip.'},
 {source:exerciseSource+'359/farmer-s-carry/',setup:'Choose two manageable dumbbells and a clear walking path. Pick them up with a controlled hip and knee bend.',steps:['Stand tall with the weights beside your body.','Walk in small steady steps, keeping the torso upright and breathing.','Stop before grip or posture fails and put the weights down carefully.'],mistakes:['Shrugging or leaning to one side.','Walking too quickly or holding your breath.'],easier:'Carry lighter weights for a shorter distance, or begin with a stationary hold.'},
 {source:exerciseSource+'32/front-plank/',setup:'Place forearms on a mat with elbows under shoulders. Extend the legs, or keep knees down for an easier version.',steps:['Brace your abdomen and align shoulders, hips and legs.','Hold the position while breathing normally.','End the hold when you can no longer maintain alignment.'],mistakes:['Sagging the hips or lifting them too high.','Holding the breath or extending despite lost form.'],easier:'Keep your knees supported and use shorter holds with rest between them.'},
 {source:exerciseSource+'49/glute-bridge/',setup:'Lie on your back with knees bent and feet flat, about hip width apart. Let your arms rest by your sides.',steps:['Brace gently and push through your feet to raise your hips.','Stop when shoulders, hips and knees form a comfortable line.','Lower slowly rather than arching through the lower back.'],mistakes:['Lifting by overextending the spine.','Letting the knees collapse inward.'],easier:'Use a smaller comfortable lift and pause to reset between repetitions.'},
 {source:exerciseSource+'135/bodyweight-squat/',setup:'Stand with feet around shoulder width and toes turned out slightly as comfortable. Use a chair behind you if helpful.',steps:['Bend at the hips and knees as if sitting back.','Keep feet grounded and knees tracking in the direction of your toes.','Push through the feet to stand, using only a comfortable depth.'],mistakes:['Letting heels lift or knees cave inward.','Forcing depth that changes your posture.'],easier:'Squat to a stable chair or hold a support for balance.'},
 {source:'https://contentcdn.eacefitness.com/February2018/ACE_HamstringsStudy.pdf',setup:'Stand with dumbbells in front of your thighs, knees slightly bent and feet firmly grounded.',steps:['Move your hips backward while keeping the weights close to your legs.','Lower only as far as you can keep your back neutral and the movement controlled.','Drive the hips forward to stand without leaning back at the top.'],mistakes:['Rounding the back to reach the floor.','Turning the movement into a deep squat.'],easier:'Practice the hip hinge without weights or use a shorter lowering range.'},
 {source:'https://contentcdn.eacefitness.com/February2018/ACE_HamstringsStudy.pdf',setup:'Adjust the seat and pads to the machine instructions. Align the knee joint with the pivot and secure the thigh pad.',steps:['Bend the knees to curl the lower legs down through a comfortable range.','Keep the hips against the seat and avoid lifting the torso.','Return the weight slowly without locking or slamming the stack.'],mistakes:['Incorrect pad position or knee alignment.','Jerking the weight or lifting off the seat.'],easier:'Reduce the load and range; have a trainer confirm the machine setup.'},
 {source:exerciseSource+'73/standing-calf-raises-wall/',setup:'Stand upright with feet hip width apart and a stable support within reach.',steps:['Rise onto the balls of your feet while keeping the ankles aligned.','Pause briefly at a comfortable height.','Lower both heels slowly to the floor and repeat.'],mistakes:['Bouncing through the movement.','Rolling the ankles outward or losing balance.'],easier:'Use both feet, hold a support and start with a smaller range.'},
] as const;
export const exerciseGuides=exercises.map((exercise,index)=>({...exercise,...details[index],slug:exercise.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'')}));
export const workoutTemplates=[
 {name:'Full body foundations',duration:30,description:'A balanced strength session. Leave recovery time between sessions.',exercises:[0,2,10,11,9]},
 {name:'Upper body at the gym',duration:35,description:'Push, pull and arms with adjustable weights.',exercises:[1,3,4,6,7]},
 {name:'Lower body & core',duration:30,description:'Legs, hips and trunk strength.',exercises:[11,12,10,14,9]},
 {name:'No equipment essentials',duration:20,description:'A simple bodyweight session for home.',exercises:[0,11,10,9,14]},
] as const;
