import {recordsOf,localDate,monthDates,metrics,type LedgerRecord} from './index';
export function activityTrends(records:LedgerRecord[],month:string,timezone:string,asOf:Date){
 const end=metrics(records,month,'USD',timezone,asOf).end,dates=monthDates(month).filter(d=>d<=end),tasks=recordsOf(records,'task'),cohort=tasks.filter(t=>localDate(t.data.due,timezone).startsWith(month));
 const habits=recordsOf(records,'habit').filter(h=>h.data.active),completions=new Set(recordsOf(records,'completion').map(c=>`${c.data.habitId}:${c.data.date}`)),workouts=recordsOf(records,'workout'),meals=recordsOf(records,'meal');
 const daily=dates.map(date=>{const scheduled=habits.filter(h=>date>=h.data.startDate&&h.data.days.includes(new Date(`${date}T12:00:00Z`).getUTCDay()));const done=scheduled.filter(h=>completions.has(`${h.id}:${date}`)).length;return {date,habits:scheduled.length?Math.round(done/scheduled.length*100):null,scheduled:scheduled.length,completed:done,minutes:workouts.filter(w=>w.data.date===date).reduce((n,w)=>n+w.data.duration,0),meals:meals.filter(m=>m.data.date===date).length};});
 const weeks=Array.from({length:4},(_,i)=>{const finish=new Date(`${end}T12:00:00Z`);finish.setUTCDate(finish.getUTCDate()-(3-i)*7);const start=new Date(finish);start.setUTCDate(start.getUTCDate()-6);const from=start.toISOString().slice(0,10),to=finish.toISOString().slice(0,10);return {label:['3 weeks ago','2 weeks ago','Last week','This week'][i],from,to,due:tasks.filter(t=>localDate(t.data.due,timezone)>=from&&localDate(t.data.due,timezone)<=to).length,completed:tasks.filter(t=>t.data.done&&t.data.completedAt&&localDate(t.data.completedAt,timezone)>=from&&localDate(t.data.completedAt,timezone)<=to).length};});
 const completed=cohort.filter(t=>t.data.done).length,overdue=cohort.filter(t=>!t.data.done&&new Date(t.data.due)<asOf).length;
 return {daily,weeks,taskStatus:[{name:'Open',value:cohort.length-completed-overdue,color:'#a894ff'},{name:'Overdue',value:overdue,color:'#f08b9c'},{name:'Completed',value:completed,color:'#80e4bd'}],taskTotal:cohort.length,undated:cohort.filter(t=>t.data.done&&!t.data.completedAt).length,dated:tasks.filter(t=>t.data.done&&t.data.completedAt).length,hasHabits:habits.length>0,hasWorkouts:workouts.some(w=>w.data.date.startsWith(month)&&w.data.date<=end),hasMeals:meals.some(m=>m.data.date.startsWith(month)&&m.data.date<=end)};
}
