import {Router,type RequestHandler,type Request} from 'express';
import {z} from 'zod';
import rateLimit from 'express-rate-limit';
import {randomBytes,createHash} from 'node:crypto';
import type {Prisma,User} from '@prisma/client';
import {plans,schemas,localDate,reminderEligible,csv,type LedgerRecord} from '@ledger/shared';
import {db} from './db.js';
import {verifyPassword} from './passwords.js';
import {HttpError,dto} from './service.js';
import {policy,platformSettings,settingsSchema,allowanceSchema,publicLimits,revokeSessions} from './platform.js';
declare module 'express-session'{interface SessionData{adminUserId?:string;adminVersion?:number}}
const reasonSchema=z.string().trim().min(5).max(400);
const pageSchema=z.coerce.number().int().min(1).default(1);
const dateSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
function period(req:Request){const from=dateSchema.parse(req.query.from||new Date(Date.now()-29*86400000).toISOString().slice(0,10));const to=dateSchema.parse(req.query.to||new Date().toISOString().slice(0,10));if(from>to)throw new HttpError(400,'The start date must precede the end date.');return {from,to,start:new Date(from+'T00:00:00Z'),end:new Date(new Date(to+'T00:00:00Z').getTime()+86400000)};}
async function selected(req:Request,client:Prisma.TransactionClient|typeof db=db){const a=await client.adminAccess.findUnique({where:{id:1},include:{user:true}});if(!a?.active||a.user.status!=='active'||!req.isAuthenticated()||req.session.adminUserId!==a.userId||req.user!.id!==a.userId||req.session.adminVersion!==a.version)throw new HttpError(403,'Administrator authentication is required.');return a;}
export const requireAdmin:RequestHandler=async(req,_res,next)=>{try{await selected(req);next();}catch(e){next(e);}};
async function write<T>(req:Request,action:string,target:string,reason:string|undefined,run:(tx:Prisma.TransactionClient)=>Promise<{result:T;changes:object}>){return db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "AdminAccess" WHERE id=1 FOR UPDATE`;const a=await selected(req,tx);const value=await run(tx);await tx.adminAudit.create({data:{actorId:a.userId,action,target,reason,changes:value.changes as Prisma.InputJsonValue}});return value.result;});}
export function adminAuthentication(csrf:RequestHandler){const router=Router();router.post('/login',rateLimit({windowMs:15*60000,limit:10,standardHeaders:true,legacyHeaders:false}),csrf,async(req,res,next)=>{const input=z.object({email:z.string().trim().email().max(254).transform(v=>v.toLowerCase()),password:z.string().min(1).max(128)}).parse(req.body);const credential=await db.passwordCredential.findUnique({where:{email:input.email},include:{user:true}});const valid=await verifyPassword(input.password,credential?.passwordHash);const a=await db.adminAccess.findUnique({where:{id:1}});if(!valid||!credential||!a?.active||a.userId!==credential.userId||credential.user.status!=='active')throw new HttpError(401,'Unable to sign in with these credentials.');req.session.regenerate(error=>{if(error)return next(error);req.logIn(credential.user,e=>{if(e)return next(e);req.session.csrf=randomBytes(32).toString('hex');req.session.adminUserId=a.userId;req.session.adminVersion=a.version;req.session.save(err=>err?next(err):res.json({ok:true,returnTo:'/admin'}));});});});return router;}
async function usage(userId:string,client:Prisma.TransactionClient|typeof db=db){const user=await client.user.findUniqueOrThrow({where:{id:userId}});const rows=await client.record.findMany({where:{userId},select:{kind:true,status:true,recordDate:true}});const month=localDate(new Date(),user.timezone).slice(0,7);return {tasks:rows.filter(r=>r.kind==='task'&&r.status==='active').length,habits:rows.filter(r=>r.kind==='habit'&&r.status==='active').length,goals:rows.filter(r=>r.kind==='goal'&&r.status==='active').length,transactions:rows.filter(r=>r.kind==='transaction'&&r.recordDate?.startsWith(month)).length,automations:rows.filter(r=>r.kind==='automation'&&r.status==='active').length};}
async function account(user:User,detail=false){const p=await policy(user);return {id:user.id,name:user.name,email:user.email,createdAt:user.createdAt,status:user.status,lastActiveAt:user.lastActiveAt,basePlan:user.plan,plan:p.plan,source:p.source,override:p.override?{plan:p.override.plan,reason:p.override.reason,expiresAt:p.override.expiresAt}:null,allowances:publicLimits(p.limits),usage:await usage(user.id),...(detail?{billing:(await db.billingRecord.findMany({where:{userId:user.id},orderBy:{createdAt:'desc'}})).map(b=>({...b,amount:Number(b.amount)}))}:{})};}
async function summary(req:Request){const p=period(req);const [users,jobs,deliveries,billing,ai]=await Promise.all([db.user.findMany(),db.job.groupBy({by:['status'],_count:true}),db.deliveryAttempt.groupBy({by:['status'],_count:true}),db.billingRecord.findMany({where:{verified:true,status:'paid',createdAt:{gte:p.start,lt:p.end}}}),db.aiUsage.groupBy({by:['status'],where:{createdAt:{gte:p.start,lt:p.end}},_count:true})]);const accounts=await Promise.all(users.map(async u=>({user:u,plan:(await policy(u)).plan})));const byPlan=Object.fromEntries(['Free','Pro','Lifetime'].map(plan=>[plan,accounts.filter(a=>a.plan===plan).length]));const revenue:Record<string,{recurring:number;lifetime:number}>={};for(const b of billing){const bucket=revenue[b.currency]||={recurring:0,lifetime:0};if(b.kind==='recurring')bucket.recurring+=Number(b.amount);if(b.kind==='lifetime')bucket.lifetime+=Number(b.amount);}return {period:{from:p.from,to:p.to},totalUsers:users.length,newUsers:users.filter(u=>u.createdAt>=p.start&&u.createdAt<p.end).length,activeUsers:users.filter(u=>u.status==='active'&&u.lastActiveAt&&u.lastActiveAt>=p.start&&u.lastActiveAt<p.end).length,activityDefinition:'Active account with at least one authenticated protected request during the selected UTC period.',byPlan,suspended:users.filter(u=>u.status==='suspended').length,jobs,deliveries,ai,revenue,subscriptionStatuses:await db.billingRecord.groupBy({by:['status'],_count:true}),billingConfigured:false};}
export function adminRoutes(){const router=Router();router.use(requireAdmin);
 router.get('/me',async(req,res)=>{const a=await selected(req);res.json({user:{id:a.userId,name:a.user.name,email:a.user.email},csrf:req.session.csrf});});
 router.get('/overview',async(req,res)=>res.json(await summary(req)));
 router.get('/users',async(req,res)=>{const page=pageSchema.parse(req.query.page);const limit=20;const q=z.string().max(160).parse(req.query.q||'');const where=q?{OR:[{email:{contains:q,mode:'insensitive' as const}},{name:{contains:q,mode:'insensitive' as const}}]}:{};const [total,users]=await Promise.all([db.user.count({where}),db.user.findMany({where,orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit})]);res.json({total,page,limit,users:await Promise.all(users.map(u=>account(u)))});});
 router.get('/users/:id',async(req,res)=>{const u=await db.user.findUnique({where:{id:String(req.params.id)}});if(!u)throw new HttpError(404,'Account not found.');res.json(await account(u,true));});
 router.post('/users/:id/action',async(req,res)=>{const id=String(req.params.id);const data=z.object({action:z.enum(['suspend','reactivate','revoke-sessions','grant','remove-override']),reason:reasonSchema,plan:z.enum(['Free','Pro','Lifetime']).optional(),expiresAt:z.iso.datetime().optional()}).parse(req.body);if(id===req.user!.id&&data.action==='suspend')throw new HttpError(400,'Transfer admin access before suspending this account.');res.json(await write(req,data.action,id,data.reason,async tx=>{const before=await tx.user.findUniqueOrThrow({where:{id}});await tx.$queryRaw`SELECT id FROM "User" WHERE id=${id} FOR UPDATE`;if(data.action==='suspend'||data.action==='reactivate'){await tx.user.update({where:{id},data:{status:data.action==='suspend'?'suspended':'active'}});if(data.action==='suspend')await tx.job.updateMany({where:{userId:id,status:{in:['pending','leased']},type:{not:'password-reset'}},data:{status:'cancelled',leaseUntil:null}});}if(['suspend','revoke-sessions'].includes(data.action))await revokeSessions(id,tx);if(data.action==='grant'){if(!data.plan||!data.expiresAt||new Date(data.expiresAt)<=new Date())throw new HttpError(400,'Choose a plan and a future expiry.');await tx.entitlementOverride.upsert({where:{userId:id},create:{userId:id,plan:data.plan,reason:data.reason,expiresAt:new Date(data.expiresAt),grantedBy:req.user!.id},update:{plan:data.plan,reason:data.reason,expiresAt:new Date(data.expiresAt),grantedBy:req.user!.id}});}if(data.action==='remove-override')await tx.entitlementOverride.deleteMany({where:{userId:id}});return {result:{ok:true},changes:{before:{status:before.status,basePlan:before.plan},after:{action:data.action,plan:data.plan,expiresAt:data.expiresAt}}};}));});
 const configInput=z.object({plan:z.enum(['Free','Pro','Lifetime']),allowances:allowanceSchema,scope:z.enum(['new-accounts','all-accounts']),effectiveAt:z.iso.datetime(),reason:reasonSchema});
 async function configPreview(input:z.infer<typeof configInput>){if(new Date(input.effectiveAt).getTime()<Date.now()-60000)throw new HttpError(400,'Choose an effective date now or in the future.');const candidates=await db.user.findMany({where:{entitlementSource:{not:'provider'}}});let affected=0;for(const u of candidates)if((await policy(u)).plan===input.plan&&(input.scope==='all-accounts'||u.createdAt>=new Date(input.effectiveAt)))affected++;return {affected,excludedProviderAccounts:await db.user.count({where:{entitlementSource:'provider'}}),digest:createHash('sha256').update(JSON.stringify({input,affected})).digest('hex')};}
 router.get('/plans',async(_req,res)=>res.json({defaults:Object.fromEntries(Object.entries(plans).map(([name,p])=>[name,{...p,...publicLimits(p)}])),versions:await db.policyVersion.findMany({orderBy:{createdAt:'desc'},take:30}),billingConfigured:false,billingStatus:'Production billing is not configured. Manual grants are not payments.'}));
 router.post('/plans/preview',async(req,res)=>res.json(await configPreview(configInput.parse(req.body))));
 router.post('/plans',async(req,res)=>{const input=configInput.parse(req.body);const preview=await configPreview(input);if(req.body.digest!==preview.digest)throw new HttpError(409,'Affected accounts changed. Preview the change again.');res.json(await write(req,'plan-allowances',input.plan,input.reason,async tx=>({result:await tx.policyVersion.create({data:{plan:input.plan,data:input.allowances,scope:input.scope,effectiveAt:new Date(input.effectiveAt),actorId:req.user!.id}}),changes:{allowances:input.allowances,scope:input.scope,effectiveAt:input.effectiveAt,affected:preview.affected}})));});
 router.get('/announcements',async(_req,res)=>{const rows=await db.announcement.findMany({orderBy:{publishAt:'desc'},take:100});res.json({announcements:await Promise.all(rows.map(async a=>({...a,reads:await db.announcementRead.count({where:{announcementId:a.id,version:a.version}}),dismissals:await db.announcementDismissal.count({where:{announcementId:a.id,version:a.version}})})))});});
 router.post('/announcements',async(req,res)=>{const data=schemas.announcement.parse(req.body.data);const status=z.enum(['draft','published']).parse(req.body.status||'draft');const reason=reasonSchema.parse(req.body.reason);const id=z.string().optional().parse(req.body.id);const expected=z.number().int().optional().parse(req.body.version);if(data.expiresAt<=data.publishAt)throw new HttpError(400,'Expiry must follow publication.');res.json(await write(req,'announcement-save',id||'new',reason,async tx=>{const old=id?await tx.announcement.findUnique({where:{id}}):null;if(id&&(!old||old.version!==expected))throw new HttpError(409,'Announcement changed. Reload and retry.');const version=(old?.version||0)+1;const fields={data:{...data,version},version,status,publishAt:new Date(data.publishAt),expiresAt:new Date(data.expiresAt),priority:data.priority,audience:data.audience};const result=old?await tx.announcement.update({where:{id:old.id},data:fields}):await tx.announcement.create({data:fields});if(old)await tx.job.updateMany({where:{recordId:old.id,type:'announcement-followup',status:{in:['pending','leased']}},data:{status:'cancelled'}});return {result,changes:{status,audience:data.audience,version,followup:data.followup,publishAt:data.publishAt,expiresAt:data.expiresAt}};}));});
 router.get('/automations',async(_req,res)=>{const jobs=await db.job.findMany({orderBy:{createdAt:'desc'},take:100,select:{id:true,userId:true,type:true,status:true,attempts:true,maxAttempts:true,dueAt:true,leaseUntil:true,deliveredAt:true,createdAt:true,deliveries:{select:{status:true,attempt:true,providerId:true}}}});const month=new Date();month.setUTCDate(1);month.setUTCHours(0,0,0,0);res.json({jobs,enabledRules:await db.record.count({where:{kind:'automation',status:'active'}}),resendConfigured:!!(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM),bounceStatus:'Webhook delivery/bounce reporting is not configured.',monthlySent:await db.job.count({where:{type:{not:'password-reset'},deliveredAt:{gte:month}}})});});
 router.post('/automations/:id/action',async(req,res)=>{const id=String(req.params.id);const {action,reason}=z.object({action:z.enum(['retry','cancel']),reason:reasonSchema}).parse(req.body);res.json(await write(req,`job-${action}`,id,reason,async tx=>{const job=await tx.job.findUniqueOrThrow({where:{id},include:{user:true,deliveries:true}});if(action==='cancel'){if(job.status!=='pending')throw new HttpError(409,'Only pending jobs can be cancelled.');await tx.job.update({where:{id},data:{status:'cancelled'}});}else{if(job.status!=='failed'||job.deliveredAt||job.deliveries.some(d=>d.status==='sent')||job.maxAttempts>=10||!['task-overdue','announcement-followup'].includes(job.type)||job.user.status!=='active')throw new HttpError(409,'This job is not eligible for retry.');const first=job.deliveries[0];if(first&&first.createdAt.getTime()<Date.now()-23*3600000)throw new HttpError(409,'Provider idempotency window expired; do not resend this job.');const p=await policy(job.user,tx);if(!p.limits.emails||!process.env.RESEND_API_KEY)throw new HttpError(409,'Email delivery or plan allowance is unavailable.');const sent=await tx.job.findMany({where:{userId:job.userId,deliveredAt:{not:null},type:{not:'password-reset'}}});if(sent.filter(j=>localDate(j.deliveredAt!,job.user.timezone).startsWith(localDate(new Date(),job.user.timezone).slice(0,7))).length>=p.limits.emails)throw new HttpError(409,'Monthly email allowance is reached.');const rules=await tx.record.findMany({where:{userId:job.userId,kind:'automation'}});const matching=rules.filter(r=>(r.data as any).type===job.type);if(matching.length&&!matching.some(r=>(r.data as any).enabled))throw new HttpError(409,'The relevant rule is disabled.');if(job.type==='task-overdue'){const task=await tx.record.findFirst({where:{id:job.recordId,userId:job.userId,kind:'task'}});if(!job.user.optionalEmails||!task||task.version!==job.expectedVersion||!reminderEligible(dto(task) as LedgerRecord<'task'>,new Date()))throw new HttpError(409,'The task or preferences no longer permit this reminder.');}else{const a=await tx.announcement.findUnique({where:{id:job.recordId}});if(!job.user.productUpdates||!a||a.status!=='published'||a.version!==job.expectedVersion||a.expiresAt<=new Date()||a.publishAt>new Date()||!(a.data as any).followup||(a.audience!=='Everyone'&&a.audience!==p.plan)||await tx.announcementDismissal.findUnique({where:{userId_announcementId_version:{userId:job.userId,announcementId:a.id,version:a.version}}}))throw new HttpError(409,'Announcement or preferences no longer permit delivery.');}await tx.job.update({where:{id},data:{status:'pending',maxAttempts:job.maxAttempts+1,dueAt:new Date(),leaseUntil:null}});}return {result:{ok:true},changes:{before:job.status,after:action==='cancel'?'cancelled':'pending'}};}));});
 router.post('/test-email',async(req,res)=>{const reason=reasonSchema.parse(req.body.reason);if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)throw new HttpError(503,'Resend is not configured.');res.json(await write(req,'test-email',req.user!.id,reason,async tx=>{if(await tx.job.findFirst({where:{userId:req.user!.id,type:'admin-test',createdAt:{gt:new Date(Date.now()-300000)}}}))throw new HttpError(429,'Wait five minutes before another test email.');const job=await tx.job.create({data:{userId:req.user!.id,type:'admin-test',recordId:req.user!.id,expectedVersion:req.session.adminVersion!,key:`admin-test:${req.user!.id}:${randomBytes(12).toString('hex')}`,dueAt:new Date()}});return {result:{ok:true,message:'Test email queued for the selected administrator only.',jobId:job.id},changes:{queued:true}};}));});
 router.get('/reports',async(req,res)=>{const result=await summary(req);if(req.query.format==='csv'){const rows:(string|number)[][]=[['Metric','Value'],['Period start',result.period.from],['Period end',result.period.to],['Registered users',result.totalUsers],['New users',result.newUsers],['Active users',result.activeUsers],...Object.entries(result.byPlan).map(([k,v])=>[k,v]),...Object.entries(result.revenue).flatMap(([currency,v])=>[[`Recurring paid revenue (${currency})`,v.recurring/100],[`Lifetime paid revenue (${currency})`,v.lifetime/100]])];res.setHeader('Content-Disposition','attachment; filename="daily-ledger-platform-report.csv"');return res.type('text/csv').send(csv(rows));}res.json(result);});
 router.get('/settings',async(_req,res)=>res.json(await platformSettings()));
 router.patch('/settings',async(req,res)=>{const settings=settingsSchema.parse(req.body.settings);const version=z.number().int().min(0).parse(req.body.version);const reason=reasonSchema.parse(req.body.reason);res.json(await write(req,'platform-settings','platform',reason,async tx=>{const before=await platformSettings(tx);if(version!==before.version)throw new HttpError(409,'Settings changed. Reload and retry.');const result=await tx.platformConfig.upsert({where:{id:1},create:{id:1,data:settings},update:{data:settings,version:{increment:1}}});return {result:{settings,version:result.version},changes:{before:before.settings,after:settings}};}));});
 router.get('/ai',async(req,res)=>{const {settings,version}=await platformSettings();res.json({enabled:settings.aiEnabled,version,allowances:settings.aiAllowances,instructions:settings.assistantInstructions,provider:process.env.AI_PROVIDER||null,model:process.env.AI_MODEL||null,configured:!!(process.env.AI_PROVIDER==='openai-compatible'&&process.env.AI_BASE_URL&&process.env.AI_API_KEY&&process.env.AI_MODEL),usage:await db.aiUsage.groupBy({by:['status'],where:{createdAt:{gte:period(req).start,lt:period(req).end}},_count:true,_sum:{inputTokens:true,outputTokens:true,estimatedCost:true}}),instructionHistory:await db.adminAudit.findMany({where:{action:'platform-settings'},select:{id:true,createdAt:true,changes:true},orderBy:{createdAt:'desc'},take:20}),rateLimit:'20 requests per user per minute; per-plan monthly request and token limits are enforced.'});});
 router.get('/audit',async(req,res)=>{const page=pageSchema.parse(req.query.page);res.json({page,total:await db.adminAudit.count(),records:await db.adminAudit.findMany({orderBy:{createdAt:'desc'},skip:(page-1)*30,take:30})});});
 return router;
}

