import 'dotenv/config';
import {emitKeypressEvents} from 'node:readline';
import {passwordChecks} from '@ledger/shared';
import {db,pool} from './db.js';
import {hashPassword} from './passwords.js';
import {revokeSessions} from './platform.js';
async function password(prompt:string):Promise<string>{if(!process.stdin.isTTY)throw new Error('Password setup requires an interactive terminal.');process.stdout.write(prompt);emitKeypressEvents(process.stdin);process.stdin.setRawMode(true);process.stdin.resume();return new Promise((resolve,reject)=>{let value='';function stop(){process.stdin.off('keypress',handler);process.stdin.setRawMode(false);process.stdin.pause();process.stdout.write('\n');}function handler(char:string,key:{name?:string;ctrl?:boolean}){if(key.ctrl&&key.name==='c'){stop();reject(new Error('Cancelled'));}else if(key.name==='return'){stop();resolve(value);}else if(key.name==='backspace')value=value.slice(0,-1);else if(char&&!key.ctrl&&char.length===1&&char>=' ')value+=char;}process.stdin.on('keypress',handler);});}
async function run(){const [action,userId,...rest]=process.argv.slice(2);const reason=rest.join(' ').trim();if(!['select','password'].includes(action)||!userId||reason.length<5)throw new Error('Usage: npm run admin -- select|password USER_ID "Reason for change"');const user=await db.user.findUnique({where:{id:userId}});if(!user||user.status!=='active')throw new Error('Select an existing active user ID.');if(action==='select'){await db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(9021001)::text`;await tx.$queryRaw`SELECT id FROM "AdminAccess" WHERE id=1 FOR UPDATE`;const old=await tx.adminAccess.findUnique({where:{id:1}});await tx.adminAccess.upsert({where:{id:1},create:{id:1,userId},update:{userId,active:true,version:{increment:1}}});if(old){await revokeSessions(old.userId,tx);await tx.job.updateMany({where:{userId:old.userId,type:'admin-test',status:{in:['pending','leased']}},data:{status:'cancelled'}});}await revokeSessions(userId,tx);await tx.adminAudit.create({data:{actorId:'server-cli',action:'admin-transfer',target:userId,reason,changes:{before:old?.userId||null,after:userId}}});});console.log('Admin selection updated. Previous and selected account sessions revoked.');return;}
const first=await password('New admin password (input hidden): ');const check=passwordChecks(first);if(!check.length||!check.mix)throw new Error('Use 12–128 characters with letters, numbers and symbols.');const confirm=await password('Confirm password (input hidden): ');if(first!==confirm)throw new Error('Passwords do not match.');const hash=await hashPassword(first);await db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "AdminAccess" WHERE id=1 FOR UPDATE`;const selected=await tx.adminAccess.findUnique({where:{id:1}});if(!selected?.active||selected.userId!==userId)throw new Error('Select this account as admin before setting its admin password.');await tx.passwordCredential.upsert({where:{userId},create:{userId,email:user.email.toLowerCase(),passwordHash:hash},update:{passwordHash:hash}});await tx.passwordReset.updateMany({where:{userId,usedAt:null},data:{usedAt:new Date()}});await revokeSessions(userId,tx);await tx.adminAccess.update({where:{id:1},data:{version:{increment:1}}});await tx.adminAudit.create({data:{actorId:'server-cli',action:'admin-password-reset',target:userId,reason,changes:{passwordChanged:true,sessionsRevoked:true}}});});console.log('Admin password set securely. Existing sessions and reset links revoked.');}
run().catch(()=>{console.error('Admin setup failed. Verify the active user ID, selection, password requirements, unique email, and database connection.');process.exitCode=1;}).finally(async()=>{await db.$disconnect();await pool.end();});

