import { Router, type Request, type Response, type NextFunction, type RequestHandler } from 'express';
import { randomBytes,randomUUID } from 'node:crypto';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { safeReturnTo,passwordChecks } from '@ledger/shared';
import { db } from './db.js';
import {platformSettings} from './platform.js';
import { hashPassword,verifyPassword,resetToken,tokenHash,matchesReset } from './passwords.js';
import { HttpError } from './service.js';
import {loginLimit} from './login-limit.js';
const emailSchema=z.string().trim().email().max(254).transform(v=>v.toLowerCase());
const passwordSchema=z.string().min(12,'Use at least 12 characters').max(128,'Use at most 128 characters').refine(v=>passwordChecks(v).mix,'Use a mix of letters, numbers, and symbols');
const loginSchema=z.object({email:emailSchema,password:z.string().min(1).max(128),returnTo:z.string().optional()});
const signupSchema=z.object({name:z.string().trim().min(1).max(160),email:emailSchema,password:passwordSchema,returnTo:z.string().optional()});
function login(req:Request,res:Response,next:NextFunction,user:{id:string},returnTo:unknown){req.session.regenerate(err=>{if(err)return next(err);req.logIn(user,error=>{if(error)return next(error);req.session.csrf=randomBytes(32).toString('hex');req.session.save(e=>e?next(e):res.json({ok:true,returnTo:safeReturnTo(returnTo)}));});});}
export function passwordAuth(csrf:RequestHandler){const router=Router();const limiter=rateLimit({windowMs:15*60000,limit:20,message:{error:"Too many authentication attempts. Please try again in 15 minutes."},standardHeaders:true,legacyHeaders:false});router.get('/csrf',(req,res)=>{req.session.csrf ||= randomBytes(32).toString('hex');res.json({csrf:req.session.csrf});});
 router.post('/signup',limiter,csrf,async(req,res,next)=>{const data=signupSchema.parse(req.body);const existing=await db.user.findFirst({where:{email:data.email}});if(existing)throw new HttpError(409,'An account already uses this email. Use your original sign-in method.');const passwordHash=await hashPassword(data.password);const settings=(await platformSettings()).settings;const user=await db.user.create({data:{email:data.email,name:data.name,currency:settings.currency,timezone:settings.timezone,optionalEmails:settings.optionalEmailsDefault,credential:{create:{email:data.email,passwordHash}}}});login(req,res,next,user,data.returnTo);});
 router.post('/login',csrf,loginLimit,async(req,res,next)=>{const data=loginSchema.parse(req.body);const credential=await db.passwordCredential.findUnique({where:{email:data.email},include:{user:true}});const valid=await verifyPassword(data.password,credential?.passwordHash);if(!valid||!credential)throw new HttpError(401,'Email or password is incorrect.');login(req,res,next,credential.user,data.returnTo);});
 router.post('/forgot-password',limiter,csrf,async(req,res)=>{const email=emailSchema.parse(req.body.email);if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)throw new HttpError(503,'Password reset email is not configured. Please contact your workspace operator or use Google account recovery.');const credential=await db.passwordCredential.findUnique({where:{email}});if(credential){const id=randomUUID();const token=resetToken(id,credential.userId);await db.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "User" WHERE id=${credential.userId} FOR UPDATE`;const recent=await tx.passwordReset.findFirst({where:{userId:credential.userId,createdAt:{gt:new Date(Date.now()-5*60000)}}});if(recent)return;await tx.passwordReset.create({data:{id,userId:credential.userId,tokenHash:tokenHash(token),expiresAt:new Date(Date.now()+3600000)}});await tx.job.create({data:{userId:credential.userId,key:`password-reset:${id}`,type:'password-reset',recordId:id,expectedVersion:1,dueAt:new Date()}});});}res.json({message:'If an email/password account exists, a reset link will arrive shortly. It expires in one hour. Check your spam folder too.'});});
 router.post('/reset-password',limiter,csrf,async(req,res)=>{const {id,token,password}=z.object({id:z.uuid(),token:z.string().regex(/^[a-f0-9]{64}$/),password:passwordSchema}).parse(req.body);const hash=await hashPassword(password);await db.$transaction(async tx=>{const first=await tx.passwordReset.findUnique({where:{id}});if(!first)throw new HttpError(400,'This reset link is invalid or expired.');await tx.$queryRaw`SELECT id FROM "User" WHERE id=${first.userId} FOR UPDATE`;const reset=await tx.passwordReset.findUniqueOrThrow({where:{id}});if(reset.usedAt||reset.expiresAt<=new Date()||!matchesReset(token,reset.tokenHash))throw new HttpError(400,'This reset link is invalid or expired.');await tx.passwordCredential.update({where:{userId:reset.userId},data:{passwordHash:hash}});await tx.passwordReset.updateMany({where:{userId:reset.userId,usedAt:null},data:{usedAt:new Date()}});await tx.job.updateMany({where:{userId:reset.userId,type:'password-reset',status:{in:['pending','leased']}},data:{status:'cancelled'}});await tx.$executeRaw`DELETE FROM session WHERE sess->'passport'->>'user'=${reset.userId}`;});res.json({message:'Your password has been reset. Sign in with your new password.'});});
 return router;
}

