import {z} from 'zod';
import {currencySchema,plans,quotaAllowed,type Plan,type Kind,type RecordData,type LedgerRecord} from '@ledger/shared';
import type {User,Prisma} from '@prisma/client';
import {db} from './db.js';
const cap=z.number().int().min(0).max(1_000_000).nullable();
export const allowanceSchema=z.object({tasks:cap,habits:cap,goals:cap,transactions:cap,automations:cap,emails:cap});
export const aiAllowanceSchema=z.object({requests:z.number().int().min(0).max(10000),tokens:z.number().int().min(0).max(100_000_000)});
export const settingsSchema=z.object({productName:z.string().trim().min(1).max(80),supportContact:z.union([z.string().email(),z.literal('')]),timezone:z.string().refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true;}catch{return false;}}),currency:currencySchema,optionalEmailsDefault:z.boolean(),publicAnnouncements:z.boolean(),aiEnabled:z.boolean(),assistantInstructions:z.string().max(4000),aiAllowances:z.object({Free:aiAllowanceSchema,Pro:aiAllowanceSchema,Lifetime:aiAllowanceSchema})});
export const defaults={productName:'Daily Ledger',supportContact:'',timezone:'UTC',currency:'USD',optionalEmailsDefault:false,publicAnnouncements:true,aiEnabled:false,assistantInstructions:'Be concise and helpful. Explain calculations without giving investment, tax or legal recommendations.',aiAllowances:{Free:{requests:10,tokens:10000},Pro:{requests:100,tokens:100000},Lifetime:{requests:60,tokens:60000}}};
export async function platformSettings(client:Prisma.TransactionClient|typeof db=db){const value=await client.platformConfig.findUnique({where:{id:1}});return {settings:settingsSchema.parse(value?.data||defaults),version:value?.version||0};}
export async function policy(user:User,client:Prisma.TransactionClient|typeof db=db){const override=await client.entitlementOverride.findUnique({where:{userId:user.id}});const valid=override&&override.expiresAt>new Date();const plan=(valid?override.plan:user.plan) as Plan;const versions=await client.policyVersion.findMany({where:{plan,effectiveAt:{lte:new Date()}},orderBy:{createdAt:'desc'}});const applicable=user.entitlementSource==='provider'&&!valid?undefined:versions.find(v=>v.scope==='all-accounts'||user.createdAt>=v.effectiveAt);const custom=applicable?allowanceSchema.parse(applicable.data):null;const limits={...plans[plan],...(custom?Object.fromEntries(Object.entries(custom).map(([k,v])=>[k,v===null?Infinity:v])):{})};return {plan,limits,source:valid?'manual override':user.entitlementSource,override:valid?override:null};}
export async function allowed(user:User,kind:Kind,data:RecordData[Kind],records:LedgerRecord[],client:Prisma.TransactionClient|typeof db=db){const p=await policy(user,client);return quotaAllowed(p.plan,kind,data,records,user.timezone,p.limits);}
// The built-in no-card trial. Set TRIAL_MODE=off when a card-required provider trial (e.g. Whop) replaces it.
export const internalTrialEnabled=()=>process.env.TRIAL_MODE!=='off';
export async function revokeSessions(userId:string,client:Prisma.TransactionClient|typeof db=db){await client.$executeRaw`DELETE FROM session WHERE sess->'passport'->>'user'=${userId}`;}
export function publicLimits(limits:typeof plans[Plan]){return Object.fromEntries(Object.entries(limits).filter(([key])=>['tasks','habits','goals','transactions','automations','emails'].includes(key)).map(([key,value])=>[key,value===Infinity?null:Number(value)]));}

