'use client';
import {useEffect,useState} from 'react';
import {Sparkles,Send,Trash2,RefreshCw,LockKeyhole} from 'lucide-react';
import Link from 'next/link';
import {ApiError} from '../lib/data';
import {bootUser,platformRequest} from '../lib/platform-api';
import {Entrance} from './animation';
import {TableSkeleton} from './skeleton';
import {Button} from './ui/button';
import {Dialog} from './ui/dialog';
type Message={id:string;question:string;answer:string;createdAt:string;month:string};
const suggestions=[{intent:'summary',text:'Summarize my month'},{intent:'spending',text:'Where did my money go?'},{intent:'tasks',text:'What needs my attention?'},{intent:'weekly',text:'Help me plan my week'},{intent:'goals',text:'How are my goals doing?'}];
export function AiAssistant({month}:{month:string}){const [status,setStatus]=useState<any>(null);const [messages,setMessages]=useState<Message[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [question,setQuestion]=useState('');const [intent,setIntent]=useState('summary');const [pending,setPending]=useState(false);const [clear,setClear]=useState(false);const [retry,setRetry]=useState('');
 async function load(){setLoading(true);setError('');try{await bootUser();const [s,h]=await Promise.all([platformRequest('/api/ai/status'),platformRequest('/api/ai/history')]);setStatus(s);setMessages(h.messages);}catch(e){if(e instanceof ApiError&&e.status===401){setStatus({enabled:false,configured:false,signIn:true,usage:null});}else setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function send(text=question,scope=intent){if(!text.trim()||pending||!status?.enabled||!status?.configured)return;setPending(true);setError('');setRetry('');try{const result=await platformRequest('/api/ai/chat',{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID(),month,intent:scope,question:text.trim()})});setMessages(prev=>[...prev,result.message]);setQuestion('');setStatus(await platformRequest('/api/ai/status'));}catch(e){setError((e as Error).message);setRetry(text);}finally{setPending(false);}}
 if(loading)return <TableSkeleton/>;
 if(!status)return <Entrance className="panel ai-panel"><p className="error" role="alert">{error}</p><Button onClick={load}><RefreshCw size={15}/>Retry connection</Button></Entrance>;
 return <Entrance className="panel ai-panel"><div className="panel-heading"><div><h2><Sparkles size={18}/>Let’s make things clearer</h2><p>Your money, tasks and goals · {month}</p></div>{messages.length>0&&<Button disabled={pending} onClick={()=>setClear(true)}><Trash2 size={14}/>Clear history</Button>}</div>{(!status.enabled||!status.configured)&&<div className="ai-unconfigured" role="status"><LockKeyhole size={22}/><div><strong>{status.signIn?'Sign in to start a conversation':'Your assistant is getting ready'}</strong><p>{status.signIn?'Ask about your own money, tasks and goals.':'AI replies are currently unavailable. You can keep using your workspace.'}</p></div>{status.signIn?<Link className="button" href="/login?returnTo=%2Fassistant">Sign in</Link>:<Button onClick={load}><RefreshCw size={14}/>Check again</Button>}</div>}
 {status.enabled&&status.configured&&<><div className="ai-chat" aria-label="Your AI conversation">{!messages.length?<div className="ai-intro"><span className="finance-option-icon"><Sparkles size={24}/></span><h2>What can I help with?</h2><p>Choose a question below or write your own.</p><div className="ai-suggestions">{suggestions.map(s=><button disabled={!status.enabled||!status.configured||pending} key={s.intent} onClick={()=>{setIntent(s.intent);setQuestion(s.text);}}>{s.text}</button>)}</div></div>:messages.map(m=><div className="ai-exchange" key={m.id}><div className="ai-user-message"><span>You · {m.month}</span><p>{m.question}</p></div><div className="ai-answer"><span><Sparkles size={13}/>AI-generated response</span><p>{m.answer}</p></div></div>)}{pending&&<div className="ai-answer" role="status"><span>Thinking…</span><div className="skeleton skeleton-row"/></div>}</div>{error&&<div className="error-banner" role="alert"><span>{error}</span>{retry&&<Button disabled={pending} onClick={()=>send(retry)}><RefreshCw size={14}/>Retry response</Button>}</div>}
 <form className="ai-composer" onSubmit={e=>{e.preventDefault();void send();}}><label><span className="sr-only">Assistant context</span><select aria-label="Assistant context" value={intent} onChange={e=>setIntent(e.target.value)}>{suggestions.map(s=><option key={s.intent} value={s.intent}>{s.intent==='weekly'?'Weekly plan':s.intent[0].toUpperCase()+s.intent.slice(1)}</option>)}</select></label><textarea aria-label="Ask the AI Assistant" placeholder="Ask anything about your workspace…" maxLength={1000} value={question} disabled={!status.enabled||!status.configured||pending} onChange={e=>setQuestion(e.target.value)}/><Button variant="primary" disabled={!status.enabled||!status.configured||pending||!question.trim()}><Send size={15}/>{pending?'Waiting…':'Send'}</Button></form><p className="ai-footnote">{status.usage&&`${status.usage.requests} / ${status.usage.allowance.requests} monthly requests · `} Suggestions don’t change your records. Check important figures.</p></>}
 <Dialog open={clear} onOpenChange={setClear} title="Clear your AI history?" description="This deletes your saved questions and replies. Usage counters remain for your allowance."><div className="dialog-actions"><Button onClick={()=>setClear(false)}>Keep history</Button><Button variant="danger" onClick={async()=>{try{await platformRequest('/api/ai/history',{method:'DELETE'});setMessages([]);setClear(false);}catch(e){setError((e as Error).message);}}}>Delete history</Button></div></Dialog></Entrance>;
}
