'use client';
import {useEffect,useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {Sparkles,Send,Trash2,RefreshCw,LockKeyhole,Check,ArrowRight} from 'lucide-react';
import Link from 'next/link';
import {ApiError,adapter} from '../lib/data';
import {bootUser,platformRequest} from '../lib/platform-api';
import {Entrance} from './animation';
import {TableSkeleton} from './skeleton';
import {Button} from './ui/button';
import {Dialog} from './ui/dialog';
type Action={type:'create';kind:'task'|'transaction'|'habit'|'workout'|'goal'|'meal'|'grocery';data:Record<string,unknown>;label:string}|{type:'link';path:string;label:string};
type Message={id:string;question:string;answer:string;createdAt:string;month:string;actions?:Action[]|null};
const suggestions=[{intent:'general',text:'Add a task: call the bank tomorrow at 5pm'},{intent:'general',text:'Log a $12 lunch expense today'},{intent:'general',text:'How do I import my bank statement?'},{intent:'summary',text:'Summarize my month'},{intent:'spending',text:'Where did my money go?'},{intent:'tasks',text:'What needs my attention?'},{intent:'weekly',text:'Help me plan my week'},{intent:'goals',text:'How are my goals doing?'}];
const intents=['general','summary','spending','tasks','weekly','goals'];
const intentLabel=(intent:string)=>intent==='general'?'General (help & commands)':intent==='weekly'?'Weekly plan':intent[0].toUpperCase()+intent.slice(1);
// The assistant only proposes. Each create action runs through the normal validated save when the user confirms it.
function ActionList({message}:{message:Message}){
 const client=useQueryClient();const [done,setDone]=useState<Record<number,boolean>>({}),[errors,setErrors]=useState<Record<number,string>>({}),[busy,setBusy]=useState<number|null>(null);
 const storeKey='ai-actions:'+message.id;
 useEffect(()=>{try{setDone(JSON.parse(localStorage.getItem(storeKey)||'{}'));}catch{/* progress marks are a convenience only */}},[storeKey]);
 async function run(index:number,action:Extract<Action,{type:'create'}>){setBusy(index);setErrors(e=>({...e,[index]:''}));try{await adapter.save({kind:action.kind,data:action.data});const next={...done,[index]:true};setDone(next);try{localStorage.setItem(storeKey,JSON.stringify(next));}catch{/* ignore */}await client.invalidateQueries({queryKey:['snapshot']});}catch(e){setErrors(prev=>({...prev,[index]:(e as Error).message}));}finally{setBusy(null);}}
 if(!message.actions?.length)return null;
 return <div className="ai-actions" aria-label="Suggested actions">{message.actions.map((action,index)=>action.type==='link'?<Link key={index} className="button" href={action.path}>{action.label}<ArrowRight size={14}/></Link>:<div className="ai-action" key={index}><span>{action.label}</span><Button variant="primary" disabled={!!done[index]||busy!==null} onClick={()=>void run(index,action)}>{done[index]?<><Check size={14}/>Added</>:busy===index?'Adding…':'Confirm'}</Button>{errors[index]&&<small role="alert" className="error">{errors[index]}</small>}</div>)}</div>;
}
export function AiAssistant({month}:{month:string}){const client=useQueryClient();const [status,setStatus]=useState<any>(null);const [messages,setMessages]=useState<Message[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [question,setQuestion]=useState('');const [intent,setIntent]=useState('general');const [pending,setPending]=useState(false);const [clear,setClear]=useState(false);const [retry,setRetry]=useState('');
 async function load(){setLoading(true);setError('');try{await bootUser();const [s,h]=await Promise.all([platformRequest('/api/ai/status'),platformRequest('/api/ai/history')]);setStatus(s);setMessages(h.messages);}catch(e){if(e instanceof ApiError&&e.status===401){setStatus({enabled:false,configured:false,signIn:true,usage:null});}else setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function send(text=question,scope=intent){if(!text.trim()||pending||!status?.enabled||!status?.configured)return;setPending(true);setError('');setRetry('');try{const result=await platformRequest('/api/ai/chat',{method:'POST',body:JSON.stringify({requestId:crypto.randomUUID(),month,intent:scope,question:text.trim()})});setMessages(prev=>[...prev,result.message]);setQuestion('');setStatus(await platformRequest('/api/ai/status'));await client.invalidateQueries({queryKey:['snapshot']});}catch(e){setError((e as Error).message);setRetry(text);}finally{setPending(false);}}
 if(loading)return <TableSkeleton/>;
 if(!status)return <Entrance className="panel ai-panel"><p className="error" role="alert">{error}</p><Button onClick={load}><RefreshCw size={15}/>Retry connection</Button></Entrance>;
 return <Entrance className="panel ai-panel"><div className="panel-heading"><div><h2><Sparkles size={18}/>Let’s make things clearer</h2><p>Your money, tasks and goals · {month}</p></div>{messages.length>0&&<Button disabled={pending} onClick={()=>setClear(true)}><Trash2 size={14}/>Clear history</Button>}</div>{(!status.enabled||!status.configured)&&<div className="ai-unconfigured" role="status"><LockKeyhole size={22}/><div><strong>{status.signIn?'Sign in to start a conversation':'Your assistant is getting ready'}</strong><p>{status.signIn?'Ask about your own money, tasks and goals.':'AI replies are currently unavailable. You can keep using your workspace.'}</p></div>{status.signIn?<Link className="button" href="/login?returnTo=%2Fassistant">Sign in</Link>:<Button onClick={load}><RefreshCw size={14}/>Check again</Button>}</div>}
 {status.enabled&&status.configured&&<><div className="ai-chat" aria-label="Your AI conversation">{!messages.length?<div className="ai-intro"><span className="finance-option-icon"><Sparkles size={24}/></span><h2>What can I help with?</h2><p>Choose a question below or write your own.</p><div className="ai-suggestions">{suggestions.map(s=><button disabled={!status.enabled||!status.configured||pending} key={s.text} onClick={()=>{setIntent(s.intent);setQuestion(s.text);}}>{s.text}</button>)}</div></div>:messages.map(m=><div className="ai-exchange" key={m.id}><div className="ai-user-message"><span>You · {m.month}</span><p>{m.question}</p></div><div className="ai-answer"><span><Sparkles size={13}/>AI-generated response</span><p>{m.answer}</p><ActionList message={m}/></div></div>)}{pending&&<div className="ai-answer" role="status"><span>Thinking…</span><div className="skeleton skeleton-row"/></div>}</div>{error&&<div className="error-banner" role="alert"><span>{error}</span>{retry&&<Button disabled={pending} onClick={()=>send(retry)}><RefreshCw size={14}/>Retry response</Button>}</div>}
 <form className="ai-composer" onSubmit={e=>{e.preventDefault();void send();}}><label><span className="sr-only">Assistant context</span><select aria-label="Assistant context" value={intent} onChange={e=>setIntent(e.target.value)}>{intents.map(i=><option key={i} value={i}>{intentLabel(i)}</option>)}</select></label><textarea aria-label="Ask the AI Assistant" placeholder="Ask anything about your workspace…" maxLength={1000} value={question} disabled={!status.enabled||!status.configured||pending} onChange={e=>setQuestion(e.target.value)}/><Button variant="primary" disabled={!status.enabled||!status.configured||pending||!question.trim()}><Send size={15}/>{pending?'Waiting…':'Send'}</Button></form><p className="ai-footnote">{status.usage&&`${status.usage.requests} / ${status.usage.allowance.requests} monthly requests · `} Nothing changes until you confirm an action. Check important figures.</p></>}
 <Dialog open={clear} onOpenChange={setClear} title="Clear your AI history?" description="This deletes your saved questions and replies. Usage counters remain for your allowance."><div className="dialog-actions"><Button onClick={()=>setClear(false)}>Keep history</Button><Button variant="danger" onClick={async()=>{try{await platformRequest('/api/ai/history',{method:'DELETE'});setMessages([]);setClear(false);}catch(e){setError((e as Error).message);}}}>Delete history</Button></div></Dialog></Entrance>;
}

