'use client';
import { useRef, useEffect, useState, type ReactNode } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
gsap.registerPlugin(useGSAP);
export function useRecordMotion(records:unknown,route:string){
 const root=useRef<HTMLElement>(null);const previous=useRef(new Map<string,{top:number;left:number;width:number;height:number;clone:HTMLElement;parent:HTMLElement;state:string}>());const previousRoute=useRef(route);
 useGSAP(()=>{
  if(!root.current)return;const next=new Map<string,{top:number;left:number;width:number;height:number;clone:HTMLElement;parent:HTMLElement;state:string}>();
  const animate=!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&previousRoute.current===route&&previous.current.size>0;
  root.current.querySelectorAll<HTMLElement>('[data-record-id]').forEach(el=>{const id=el.dataset.recordId!;const rect=el.getBoundingClientRect();if(!rect.width||!rect.height)return;const state=el.dataset.motionState||'';next.set(id,{top:rect.top+window.scrollY,left:rect.left+window.scrollX,width:rect.width,height:rect.height,clone:el.cloneNode(true) as HTMLElement,parent:el.parentElement!,state});if(!animate)return;const old=previous.current.get(id);
   if(!old){if(!el.classList.contains('panel'))gsap.from(el,{opacity:0,y:8,duration:.28,ease:'power2.out'});}
   else {const x=old.left-(rect.left+window.scrollX),y=old.top-(rect.top+window.scrollY);if(Math.abs(x)>1||Math.abs(y)>1)gsap.from(el,{x,y,duration:.3,ease:'power2.out'});}
  });
  const ghosts:HTMLElement[]=[];if(animate)previous.current.forEach((old,id)=>{if(next.has(id)||old.top-window.scrollY>innerHeight||old.top+old.height<window.scrollY)return;const ghost=old.clone;ghost.setAttribute('aria-hidden','true');ghost.inert=true;Object.assign(ghost.style,{position:'fixed',top:`${old.top-window.scrollY}px`,left:`${old.left-window.scrollX}px`,width:`${old.width}px`,height:`${old.height}px`,margin:'0',pointerEvents:'none',zIndex:'35'});(old.parent.isConnected?old.parent:root.current!).appendChild(ghost);ghosts.push(ghost);gsap.to(ghost,{opacity:0,y:-5,duration:.2,ease:'power2.in',onComplete:()=>ghost.remove()});});
  previous.current=next;previousRoute.current=route;return ()=>ghosts.forEach(el=>el.remove());
 },{scope:root,dependencies:[records,route],revertOnUpdate:true});return root;
}
export function Entrance({children,className='',...props}:{children:ReactNode;className?:string;[key:string]:unknown}){const ref=useRef<HTMLElement>(null);useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const siblings=ref.current?.parentElement?.children;const index=siblings?Array.from(siblings).indexOf(ref.current!):0;gsap.from(ref.current,{opacity:0,y:9,duration:className.includes('cash')||className.includes('spending')?.7:.3,delay:Math.min(index,3)*.055,ease:'power2.out'});});return ()=>mm.revert();},{scope:ref});return <section ref={ref} className={className} {...props}>{children}</section>;}
export function useReducedMotion(){const [reduced,setReduced]=useState(true);useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);update();media.addEventListener('change',update);return ()=>media.removeEventListener('change',update);},[]);return reduced;}
export function AnimatedProgress({value}:{value:number}){const ref=useRef<HTMLDivElement>(null),current=useRef(0);const target=Math.min(100,Math.max(0,value));useGSAP(()=>{const mm=gsap.matchMedia();const paint=(next:number)=>{current.current=next;if(ref.current)ref.current.style.width=`${next}%`;};mm.add('(prefers-reduced-motion: no-preference)',context=>{const state={value:current.current};let tween:gsap.core.Tween;context.ignore(()=>{tween=gsap.to(state,{value:target,duration:.5,ease:'power2.out',onUpdate:()=>paint(state.value)});});return ()=>tween.kill();});mm.add('(prefers-reduced-motion: reduce)',()=>paint(target));return ()=>mm.revert();},{scope:ref,dependencies:[target],revertOnUpdate:true});return <div className="progress" role="progressbar" aria-valuenow={Math.round(target)} aria-valuemin={0} aria-valuemax={100}><div ref={ref}/></div>;}
export function CountUp({value,format,className}:{value:number;format:(v:number)=>string;className?:string}){const ref=useRef<HTMLElement>(null),current=useRef(value*.97);useGSAP(()=>{if(!ref.current)return;const state={value:current.current};const mm=gsap.matchMedia();const paint=(next:number)=>{current.current=next;if(ref.current)ref.current.textContent=format(Math.round(next));};mm.add('(prefers-reduced-motion: no-preference)',context=>{let tween:gsap.core.Tween;context.ignore(()=>{tween=gsap.to(state,{value,duration:.4,ease:'power2.out',onUpdate:()=>paint(state.value),onComplete:()=>paint(value)});});return ()=>tween.kill();});mm.add('(prefers-reduced-motion: reduce)',()=>paint(value));return ()=>mm.revert();},{scope:ref,dependencies:[value],revertOnUpdate:true});return <strong ref={ref} className={className}>{format(value)}</strong>;}
export function AnimatedText({value,className}:{value:string;className?:string}){const match=value.match(/-?[\d,]+(?:\.\d+)?/);if(!match)return <strong className={className}>{value}</strong>;const token=match[0],prefix=value.slice(0,match.index),suffix=value.slice((match.index||0)+token.length);const digits=token.includes('.')?token.split('.')[1].length:0;const scale=10**digits,target=Math.round(Number(token.replaceAll(',',''))*scale);return <CountUp className={className} key={prefix+suffix} value={target} format={next=>next===target?value:prefix+new Intl.NumberFormat('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(next/scale)+suffix}/>;}
export function Ring({value,color='var(--mint)'}:{value:number;color?:string}){const ref=useRef<SVGCircleElement>(null),current=useRef(0);const target=Math.min(100,Math.max(0,value));useGSAP(()=>{const state={value:current.current};const paint=(next:number)=>{current.current=next;ref.current?.setAttribute('stroke-dashoffset',String(188.5*(1-next/100)));};const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',context=>{let tween:gsap.core.Tween;context.ignore(()=>{tween=gsap.to(state,{value:target,duration:.55,ease:'power2.out',onUpdate:()=>paint(state.value)});});return ()=>tween.kill();});mm.add('(prefers-reduced-motion: reduce)',()=>paint(target));return ()=>mm.revert();},{scope:ref,dependencies:[target],revertOnUpdate:true});return <div className="task-ring"><svg viewBox="0 0 70 70" aria-hidden="true"><circle cx="35" cy="35" r="30" fill="none" stroke="var(--border)" strokeWidth="7"/><circle ref={ref} cx="35" cy="35" r="30" fill="none" stroke={color} strokeWidth="7" strokeLinecap="round" strokeDasharray="188.5" strokeDashoffset="188.5" transform="rotate(-90 35 35)"/></svg><span><AnimatedText value={`${Math.round(target)}%`}/></span></div>;}
export function Floating({children,className}:{children:ReactNode;className:string}){const ref=useRef<HTMLDivElement>(null);useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.from(ref.current,{opacity:0,y:-5,duration:.18,ease:'power2.out'});});return ()=>mm.revert();},{scope:ref});return <div ref={ref} className={className}>{children}</div>;}
export function Interactions({children,route}:{children:ReactNode;route:string}){const ref=useRef<HTMLDivElement>(null);useGSAP((_context,contextSafe)=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const indicator=ref.current?.querySelector('.nav-link.active .selection-indicator');if(indicator)gsap.from(indicator,{scaleY:.35,opacity:.4,duration:.22});const click=contextSafe!((event:MouseEvent)=>{const summary=(event.target as HTMLElement).closest('summary');if(!summary)return;event.preventDefault();const details=summary.parentElement as HTMLDetailsElement;const opening=!details.open;const start=details.offsetHeight;details.open=true;const target=opening?details.scrollHeight:summary.offsetHeight+36;gsap.fromTo(details,{height:start,overflow:'hidden'},{height:target,duration:.22,ease:'power2.out',onComplete:()=>{details.open=opening;gsap.set(details,{clearProps:'height,overflow'});}});});ref.current?.addEventListener('click',click);return ()=>ref.current?.removeEventListener('click',click);});return ()=>mm.revert();},{scope:ref,dependencies:[route],revertOnUpdate:true});return <div ref={ref}>{children}</div>;}
export function useDrawer(open:boolean,close:()=>void,ready:boolean){const ref=useRef<HTMLElement>(null);const closeRef=useRef(close);closeRef.current=close;useEffect(()=>{if(!open||!ref.current)return;const previous=document.activeElement as HTMLElement;const first=ref.current.querySelector<HTMLElement>('a,button');first?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){closeRef.current();return;}if(e.key!=='Tab')return;const all=Array.from(ref.current!.querySelectorAll<HTMLElement>('a,button,input'));const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',handler);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return ()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=overflow;previous?.focus();};},[open]);useGSAP(()=>{if(!ref.current)return;const mm=gsap.matchMedia();mm.add('(max-width:800px)',()=>{const element=ref.current!;element.inert=!open;element.setAttribute('aria-hidden',String(!open));gsap.to(ref.current,{x:open?0:'-100%',duration:window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:.23,ease:'power2.out'});return ()=>{element.inert=false;element.removeAttribute('aria-hidden');};});return ()=>mm.revert();},{dependencies:[open,ready],revertOnUpdate:true});return ref;}



