'use client';
import { useRef, useEffect, type ReactNode } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
gsap.registerPlugin(useGSAP);
export function Entrance({children,className='',...props}:{children:ReactNode;className?:string;[key:string]:unknown}){const ref=useRef<HTMLElement>(null);useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const siblings=ref.current?.parentElement?.children;const index=siblings?Array.from(siblings).indexOf(ref.current!):0;gsap.from(ref.current,{opacity:0,y:9,duration:className.includes('cash')||className.includes('spending')?.7:.3,delay:Math.min(index,3)*.055,ease:'power2.out'});});return ()=>mm.revert();},{scope:ref});return <section ref={ref} className={className} {...props}>{children}</section>;}
export function AnimatedProgress({value}:{value:number}){const ref=useRef<HTMLDivElement>(null);useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.to(ref.current,{width:`${Math.min(100,Math.max(0,value))}%`,duration:.6,ease:'power2.out'});});mm.add('(prefers-reduced-motion: reduce)',()=>{gsap.set(ref.current,{width:`${Math.min(100,Math.max(0,value))}%`});});return ()=>mm.revert();},{scope:ref,dependencies:[value],revertOnUpdate:true});return <div className="progress" role="progressbar" aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100}><div ref={ref}/></div>;}
export function CountUp({value,format}:{value:number;format:(v:number)=>string}){const ref=useRef<HTMLElement>(null);const previous=useRef(value);const first=useRef(true);useGSAP(()=>{if(!ref.current)return;const state={value:first.current?value*.97:previous.current};first.current=false;previous.current=value;const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.to(state,{value,duration:.35,ease:'power2.out',onUpdate:()=>{if(ref.current)ref.current.textContent=format(Math.round(state.value));}});});mm.add('(prefers-reduced-motion: reduce)',()=>{if(ref.current)ref.current.textContent=format(value);});return ()=>mm.revert();},{scope:ref,dependencies:[value],revertOnUpdate:true});return <strong ref={ref}>{format(value)}</strong>;}
export function Ring({value}:{value:number}){const ref=useRef<SVGCircleElement>(null);useGSAP(()=>{gsap.to(ref.current,{strokeDashoffset:188.5*(1-value/100),duration:window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:.7,ease:'power2.out'});},{scope:ref,dependencies:[value],revertOnUpdate:true});return <div className="task-ring"><svg viewBox="0 0 70 70" aria-hidden="true"><circle cx="35" cy="35" r="30" fill="none" stroke="var(--border)" strokeWidth="7"/><circle ref={ref} cx="35" cy="35" r="30" fill="none" stroke="var(--mint)" strokeWidth="7" strokeLinecap="round" strokeDasharray="188.5" strokeDashoffset="188.5" transform="rotate(-90 35 35)"/></svg><span>{Math.round(value)}%</span></div>;}
export function Floating({children,className}:{children:ReactNode;className:string}){const ref=useRef<HTMLDivElement>(null);useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.from(ref.current,{opacity:0,y:-5,duration:.18,ease:'power2.out'});});return ()=>mm.revert();},{scope:ref});return <div ref={ref} className={className}>{children}</div>;}
export function Interactions({children,route}:{children:ReactNode;route:string}){const ref=useRef<HTMLDivElement>(null);useGSAP((_context,contextSafe)=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const indicator=ref.current?.querySelector('.nav-link.active .selection-indicator');if(indicator)gsap.from(indicator,{scaleY:.35,opacity:.4,duration:.22});const click=contextSafe!((event:MouseEvent)=>{const summary=(event.target as HTMLElement).closest('summary');if(!summary)return;event.preventDefault();const details=summary.parentElement as HTMLDetailsElement;const opening=!details.open;const start=details.offsetHeight;details.open=true;const target=opening?details.scrollHeight:summary.offsetHeight+36;gsap.fromTo(details,{height:start,overflow:'hidden'},{height:target,duration:.22,ease:'power2.out',onComplete:()=>{details.open=opening;gsap.set(details,{clearProps:'height,overflow'});}});});ref.current?.addEventListener('click',click);return ()=>ref.current?.removeEventListener('click',click);});return ()=>mm.revert();},{scope:ref,dependencies:[route],revertOnUpdate:true});return <div ref={ref}>{children}</div>;}
export function useDrawer(open:boolean,close:()=>void,ready:boolean){const ref=useRef<HTMLElement>(null);const closeRef=useRef(close);closeRef.current=close;useEffect(()=>{if(!open||!ref.current)return;const previous=document.activeElement as HTMLElement;const first=ref.current.querySelector<HTMLElement>('a,button');first?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){closeRef.current();return;}if(e.key!=='Tab')return;const all=Array.from(ref.current!.querySelectorAll<HTMLElement>('a,button,input'));const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',handler);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return ()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=overflow;previous?.focus();};},[open]);useGSAP(()=>{if(!ref.current)return;const mm=gsap.matchMedia();mm.add('(max-width:800px)',()=>{const element=ref.current!;element.inert=!open;element.setAttribute('aria-hidden',String(!open));gsap.to(ref.current,{x:open?0:'-100%',duration:window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:.23,ease:'power2.out'});return ()=>{element.inert=false;element.removeAttribute('aria-hidden');};});return ()=>mm.revert();},{dependencies:[open,ready],revertOnUpdate:true});return ref;}
