'use client';
import {useMemo,useState,type ReactNode} from 'react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {money,type metrics} from '@ledger/shared';
import {Entrance,useReducedMotion} from './animation';
import {EmptyState,type EmptyVariant} from './empty-state';
import {SpendingChart} from './spending-chart';

export const colors=['#80e4bd','#e3e7e9','#93999e','#9bd4f5','#bac7c9','#b4ddca'];
export type Metrics=ReturnType<typeof metrics>;
export function monthLabel(month:string){return new Date(`${month}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'});}
export function Panel({children,className='',...props}:{children:ReactNode;className?:string;[key:string]:unknown}){return <Entrance className={`panel ${className}`} {...props}>{children}</Entrance>;}
export function Empty({text='Add your first record to get started.',title='No records yet',variant='generic',onAdd,label,compact=false}:{text?:string;title?:string;variant?:EmptyVariant;onAdd?:()=>void;label?:string;compact?:boolean}){return <EmptyState title={title} description={text} variant={variant} onAdd={onAdd} label={label} compact={compact}/>;}
export function ChartTooltip({active,payload,label,currency,month}:{active?:boolean;payload?:readonly any[];label?:any;currency:string;month?:string}){if(!active||!payload?.length)return null;return <div className="dark-tooltip"><strong>{month?label+' '+monthLabel(month):payload[0].name}</strong>{payload.map((p,i)=><div key={i}><i style={{background:p.color||p.payload.fill||colors[i]}}/><span>{p.name==='income'?'Income':p.name==='expenses'?'Expenses':p.name}</span><b>{money(Number(p.value)*(month?100:1),currency)}</b></div>)}</div>;}
export function CashFlow({m,onAdd}:{m:Metrics;onAdd:()=>void}){const reduced=useReducedMotion();const [group,setGroup]=useState<'Week'|'Month'>('Month');const data=useMemo(()=>group==='Month'?m.cash:m.cash.filter((_,i)=>i%7===6||i===m.cash.length-1),[m.cash,group]);return <Panel className="cash-panel"><div className="panel-heading"><div><h2>Cash flow</h2><p>Cumulative income vs expenses — {monthLabel(m.month)}{m.partial?' · month to date':''}</p></div><div className="segmented">{(['Week','Month'] as const).map(g=><button key={g} className={g===group?'selected':''} onClick={()=>setGroup(g)} aria-pressed={g===group}>{g}</button>)}</div></div>{m.income||m.expenses?<><div className="cash-chart" aria-label={`Cumulative income ${money(m.income,m.currency)}, expenses ${money(m.expenses,m.currency)}.`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:12,right:6,left:-20,bottom:2}}><defs><linearGradient id="income-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor={colors[3]} stopOpacity={.27}/><stop offset="1" stopColor={colors[3]} stopOpacity={.02}/></linearGradient><linearGradient id="expense-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor={colors[0]} stopOpacity={.16}/><stop offset="1" stopColor={colors[0]} stopOpacity={.02}/></linearGradient></defs><CartesianGrid stroke="#303030" strokeDasharray="3 4"/><XAxis dataKey="day" minTickGap={65} tickFormatter={day=>`${day} ${new Date(`${m.month}-01`).toLocaleString('en-US',{month:'short'})}`} tick={{fill:'#aaaeb5',fontSize:12}} stroke="#4a4a4a"/><YAxis tickFormatter={n=>money(n*100,m.currency).replace(/,000/, 'k')} tick={{fill:'#aaaeb5',fontSize:12}} stroke="#4a4a4a"/><Tooltip cursor={{stroke:"#8a9298",strokeDasharray:"3 3"}} content={<ChartTooltip currency={m.currency} month={m.month}/>}/><Area type="monotone" dataKey="income" stroke={colors[3]} strokeWidth={2.7} fill="url(#income-fill)" isAnimationActive={!reduced} animationDuration={450} animationEasing="ease-out"/><Area type="monotone" dataKey="expenses" stroke={colors[0]} strokeWidth={2.7} fill="url(#expense-fill)" isAnimationActive={!reduced} animationDuration={450} animationEasing="ease-out"/></AreaChart></ResponsiveContainer></div><div className="chart-legend"><span><i style={{background:colors[3]}}/>Income (cumulative)</span><span><i style={{background:colors[0]}}/>Expenses (cumulative)</span></div></>:<Empty title="Your cash flow starts here" text="Add income or an expense to see how your money moves." variant="chart" label="Add transaction" onAdd={onAdd}/>}</Panel>;}
export function Spending({m,onCategory,onAdd}:{m:Metrics;onCategory:(name:string)=>void;onAdd:()=>void}){return <Panel className="spending-panel"><div className="spending-heading"><h2>Spending breakdown</h2><span>{m.currency}</span></div>{m.expenses?<SpendingChart m={m} onCategory={onCategory}/>:<Empty title="No spending yet" text="Record an expense to see where your money goes." variant="money" label="Add expense" onAdd={onAdd}/>}</Panel>;}
