'use client';
import {useRef,useState} from 'react';
import gsap from 'gsap';
import {useGSAP} from '@gsap/react';
import {Check,LoaderCircle,RefreshCw} from 'lucide-react';
import {BrandMark} from './brand-mark';
import {Button} from './ui/button';
export const DASHBOARD_BUILD_DURATION_MS=5000;
export function DashboardBuilding({persona,ready,error,onRetry,onComplete}:{persona:string|null;ready:boolean;error:string;onRetry:()=>void;onComplete:()=>void}){
 const root=useRef<HTMLDivElement>(null),bar=useRef<HTMLDivElement>(null),finished=useRef(false),complete=useRef(onComplete);complete.current=onComplete;
 const [completed,setCompleted]=useState(0),[paced,setPaced]=useState(false),[reduced,setReduced]=useState(false),[success,setSuccess]=useState(false);
 const steps=['Setting up your workspace','Applying your preferences',persona?`Personalizing your dashboard for ${persona}`:'Applying your starting preferences','Almost there'];
 useGSAP(()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: reduce)',()=>{setReduced(true);setPaced(true);});mm.add('(prefers-reduced-motion: no-preference)',()=>{const duration=DASHBOARD_BUILD_DURATION_MS/1000-.9;const timeline=gsap.timeline();timeline.from('.building-brand,.building-heading,.building-step',{opacity:0,y:7,duration:.3,stagger:.07});timeline.fromTo(bar.current,{scaleX:0},{scaleX:.9,duration,ease:'none',onUpdate:()=>{bar.current?.parentElement?.setAttribute('aria-valuenow',String(Math.round(Number(gsap.getProperty(bar.current!,'scaleX'))*100)));}},0);[1,2,3].forEach(n=>timeline.call(()=>setCompleted(n),[],duration*n/4));timeline.call(()=>setPaced(true),[],duration);});return ()=>mm.revert();},{scope:root});
 useGSAP(()=>{if(reduced)return;gsap.from('.building-check',{opacity:0,scale:.8,duration:.18,ease:'power2.out'});const spinner=root.current?.querySelector('.building-spinner');if(spinner)gsap.to(spinner,{rotation:360,duration:.9,repeat:-1,ease:'none'});},{scope:root,dependencies:[completed,reduced],revertOnUpdate:true});
 useGSAP(()=>{if(!paced||!ready||finished.current)return;finished.current=true;setCompleted(4);const timeline=gsap.timeline();timeline.to(bar.current,{scaleX:1,duration:reduced?0:.4,ease:'power2.out',onComplete:()=>{bar.current?.parentElement?.setAttribute('aria-valuenow','100');setSuccess(true);}}).call(()=>complete.current(),[],reduced?.05:.9);},{scope:root,dependencies:[paced,ready,reduced],revertOnUpdate:true});
 return <div ref={root} className="onboarding-shell dashboard-building"><main className="building-column"><div className="building-brand"><BrandMark/></div><h1 className="building-heading">{success?'Your dashboard is ready':reduced?'Preparing your dashboard…':'Building your dashboard'}</h1><p className="onboarding-subtitle">{success?'Your preferences are saved. Let’s begin.':'Your workspace is saved. We’re preparing your starting view.'}</p>{!reduced&&<ol className="building-checklist">{steps.map((step,i)=><li className={`building-step ${completed>i?'done':completed===i?'current':''}`} key={step}><span className="building-status" aria-hidden="true">{completed>i?<Check className="building-check" size={15}/>:completed===i?<LoaderCircle className="building-spinner" size={15}/>:<i/>}</span><span>{step}</span><span className="sr-only">{completed>i?'Complete':completed===i?'In progress':'Pending'}</span></li>)}</ol>}<div className="building-progress" role="progressbar" aria-label="Dashboard preparation" aria-valuemin={0} aria-valuemax={100} aria-valuenow={0}><div ref={bar}/></div><p className="sr-only" role="status">{success?'Your dashboard is ready':ready?'Your saved dashboard has loaded':'Loading your saved dashboard'}</p>{error&&<div className="onboarding-error" role="alert"><p>Your preferences are saved, but the dashboard could not load. {error}</p><Button onClick={onRetry}><RefreshCw size={15}/>Retry loading dashboard</Button></div>}</main></div>;
}
