'use client';
import Link from 'next/link';
import {Dumbbell,ArrowRight,Check} from 'lucide-react';
import {habitStats,recordsOf} from '@ledger/shared';
import {exerciseGuides,type MuscleGroup} from '../lib/exercise-guides';
import {BodyMap,ExerciseTracking,type ExerciseTrackingProps} from './workout-guide';
import {Entrance} from './animation';
import {Button} from './ui/button';

export function ExerciseDetail({exercise,onLog,tracking}:{exercise:typeof exerciseGuides[number];onLog:(initial:Record<string,unknown>)=>void;tracking:ExerciseTrackingProps}){
 return <div className="exercise-detail"><Entrance className="panel exercise-overview"><BodyMap selected={exercise.muscle as MuscleGroup} streak={Math.max(0,...recordsOf(tracking.s.records,'habit').filter(h=>h.data.exerciseSlug===exercise.slug).map(h=>habitStats(h,tracking.s.records,tracking.today).current))}/><div><span className="eyebrow">MOVEMENT GUIDE</span><h2>Know what you’re training</h2><div className="exercise-facts"><div><small>Primary target</small><strong>{exercise.muscle}</strong></div><div><small>Also works</small><strong>{exercise.secondary}</strong></div><div><small>Equipment</small><strong>{exercise.equipment}</strong></div><div><small>Starting range</small><strong>{exercise.reps}</strong></div></div><p>Start with a comfortable load and a controlled range. Repetitions are a starting suggestion, not a personal prescription.</p><Button variant="primary" onClick={()=>onLog({title:exercise.name,type:'Strength',duration:15,notes:`${exercise.name}: 2 sets × ${exercise.reps}\nPrimary: ${exercise.muscle}. Also works: ${exercise.secondary}.\n${exercise.tips.join(' ')}`})}><Dumbbell size={16}/>Log this exercise</Button></div></Entrance><ExerciseTracking {...tracking} slug={exercise.slug}/><div className="exercise-instructions"><Entrance className="panel"><span className="eyebrow">01 · SET UP</span><h2>Get into position</h2><p>{exercise.setup}</p><h3>Move with control</h3><ol>{exercise.steps.map((step,i)=><li key={step}><span>{i+1}</span><p>{step}</p></li>)}</ol></Entrance><div><Entrance className="panel"><h2>Keep these in mind</h2><ul>{exercise.mistakes.map(m=><li key={m}><Check size={15}/><span>Avoid {m[0].toLowerCase()+m.slice(1)}</span></li>)}</ul><h3>Make it easier</h3><p>{exercise.easier}</p></Entrance><Entrance className="panel exercise-source"><h3>About this guide</h3><p>Our summary explains common muscle targets and technique. It does not guarantee growth. Adjust to your ability; stop if a movement hurts and seek qualified advice about injuries or form.</p><a href={exercise.source} target="_blank" rel="noreferrer">Reference: ACE exercise guidance</a><p>Body illustration shows approximate regions, not a diagnostic anatomy map.</p></Entrance></div></div><Entrance className="panel related-exercises"><h2>Explore another movement</h2><div>{exerciseGuides.filter(e=>e.slug!==exercise.slug&&e.muscle===exercise.muscle).slice(0,3).map(e=><Link key={e.slug} href={`/fitness/exercises/${e.slug}`}><span>{e.name}</span><ArrowRight size={16}/></Link>)}<Link href="/fitness"><span>All exercises & workout templates</span><ArrowRight size={16}/></Link></div></Entrance></div>;
}
