'use client';
import {useState,type ReactNode} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,ArrowUpRight,ArrowDownLeft,ArrowRight,Wallet,Receipt,SlidersHorizontal,PiggyBank,Calculator,Repeat2,Plus,Pencil,Trash2,Check,Pause,Play,ChevronRight,Target} from 'lucide-react';
import {money,recordsOf,metrics,monthBudgets,planDate,settledTransaction,budgetSpending,parseMoneyInput,loanEstimate,savingsEstimate,debtEstimate,type Snapshot,type Kind,type LedgerRecord} from '@ledger/shared';
import {adapter} from '../lib/data';
import {Entrance,AnimatedProgress} from './animation';
import {Button} from './ui/button';
import {Dialog} from './ui/dialog';
import {EmptyState} from './empty-state';

type Tools={add:(kind:Kind,initial?:Record<string,unknown>)=>void;edit:(r:LedgerRecord)=>void;toggle:(r:LedgerRecord,key?:string)=>void;remove:(r:LedgerRecord)=>void};
export const financePages=[{slug:'income',title:'Income sources',description:'Know what is expected. Record it when it arrives.',icon:Wallet},{slug:'bills',title:'Bills & payments',description:'Keep due dates and paid bills in one place.',icon:Receipt},{slug:'budgets',title:'Budgets & categories',description:'Give each category a practical monthly limit.',icon:SlidersHorizontal},{slug:'savings',title:'Savings goals',description:'Build your cushion, one contribution at a time.',icon:PiggyBank},{slug:'transactions',title:'Transactions',description:'Find, edit and export your money history.',icon:ArrowUpRight},{slug:'calculators',title:'Finance calculators',description:'Work out repayments, savings and profit.',icon:Calculator},{slug:'recurring',title:'Automatic recurring entries',description:'Manage your existing weekly and monthly schedules.',icon:Repeat2}];
const calculators=[{slug:'loan',title:'Loan & EMI',description:'Monthly repayment and total interest.',icon:Receipt},{slug:'growth',title:'Savings growth',description:'Starting savings plus monthly deposits.',icon:ArrowUpRight},{slug:'goal',title:'Savings goal',description:'How much to put aside each month.',icon:Target},{slug:'percentage',title:'Quick percentage',description:'Discounts, markups, tips and percentages.',icon:Calculator},{slug:'debt',title:'Debt payoff',description:'Time to clear a balance with fixed payments.',icon:ArrowDownLeft},{slug:'profit',title:'Business profit',description:'Revenue, costs, margin and break-even.',icon:Wallet}];
export function FinanceNavigation({section,month}:{section:string;month:string}){const router=useRouter();return <div className="finance-page-nav">{section&&<Link className="finance-back" href={`/finance${section.startsWith('calculators/')?'/calculators':''}?month=${month}`}><ArrowLeft size={16}/>{section.startsWith('calculators/')?'Back to calculators':'Back to Finance'}</Link>}<label><span className="sr-only">Finance page</span><select aria-label="Finance page" value={section.split('/')[0]} onChange={e=>router.push(`/finance${e.target.value?'/'+e.target.value:''}?month=${month}`)}><option value="">Finance overview</option>{financePages.map(p=><option key={p.slug} value={p.slug}>{p.title}</option>)}</select></label></div>;}
function Card({children,className=''}:{children:ReactNode;className?:string}){return <Entrance className={`panel finance-card ${className}`}>{children}</Entrance>;}
function Blank({title,description,onAdd,label}:{title:string;description:string;onAdd?:()=>void;label?:string}){return <EmptyState title={title} description={description} variant="money" onAdd={onAdd} label={label}/>;}
function Actions({r,tools}:{r:LedgerRecord;tools:Tools}){const title='title' in r.data?r.data.title:'record';return <div className="finance-row-actions"><button className="icon-button" aria-label={`Edit ${title}`} onClick={()=>tools.edit(r)}><Pencil size={15}/></button><button className="icon-button" aria-label={`Delete ${title}`} onClick={()=>tools.remove(r)}><Trash2 size={15}/></button></div>;}

export function FinanceWorkspace({s,m,section,month,today,tools,charts,transactions}:{s:Snapshot;m:ReturnType<typeof metrics>;section:string;month:string;today:string;tools:Tools;charts:ReactNode;transactions:ReactNode}){
 const client=useQueryClient();const [payment,setPayment]=useState<LedgerRecord<'cashPlan'>|null>(null);const [paymentDate,setPaymentDate]=useState(today);const settle=useMutation({mutationFn:({plan,date}:{plan:LedgerRecord<'cashPlan'>;date:string})=>adapter.settle(plan,month,date),onSuccess:async()=>{await client.invalidateQueries({queryKey:['snapshot']});setPayment(null);}});
 const cashPlans=recordsOf(s.records,'cashPlan').filter(r=>r.data.currency===m.currency);const sources=cashPlans.filter(r=>r.data.type==='income');const bills=cashPlans.filter(r=>r.data.type==='expense');
 const budgets=monthBudgets(s.records,month,m.currency);
 function pay(r:LedgerRecord<'cashPlan'>){settle.reset();setPaymentDate(month===today.slice(0,7)?today:planDate(month,31));setPayment(r);}
 function PlanRows({plans,compact=false}:{plans:LedgerRecord<'cashPlan'>[];compact?:boolean}){return <div className="finance-plan-list">{plans.slice(0,compact?3:plans.length).map(r=>{const tx=settledTransaction(s.records,r.id,month);const due=planDate(month,r.data.day);const overdue=r.data.type==='expense'&&r.data.active&&!tx&&due<today;return <div className="finance-plan-row" key={r.id}><span className={`finance-row-icon ${r.data.type==='income'?'positive':'neutral'}`}>{r.data.type==='income'?<ArrowDownLeft size={18}/>:<Receipt size={18}/>}</span><div className="finance-row-description"><strong>{r.data.title}</strong><small>{tx?`${r.data.type==='income'?'Received':'Paid'} ${tx.data.date}`:!r.data.active?'Paused':`${r.data.type==='income'?'Expected':'Due'} ${due}`} · {r.data.category}</small></div><div className="finance-row-amount"><strong>{money(r.data.amount,r.data.currency)}</strong><span className={`finance-status ${tx?'positive':overdue?'negative':''}`}>{tx?<><Check size={11}/>{r.data.type==='income'?'Received':'Paid'}</>:overdue?'Overdue':r.data.active?'Pending':'Paused'}</span></div><div className="finance-plan-actions">{!tx&&<Button disabled={!r.data.active||month>today.slice(0,7)} onClick={()=>pay(r)}>{r.data.type==='income'?'Mark received':'Mark paid'}</Button>}{!compact&&<><button className="icon-button" aria-label={`${r.data.active?'Pause':'Resume'} ${r.data.title}`} onClick={()=>tools.toggle(r,'active')}>{r.data.active?<Pause size={15}/>:<Play size={15}/>}</button><Actions r={r} tools={tools}/></>}</div></div>;})}</div>;}
 function BudgetRows(){return <>{budgets.map(r=>{const spent=budgetSpending(r,s.records,month,m.end);const over=spent>r.data.amount;return <div className={`finance-budget-row ${over?'is-over':''}`} key={r.id}><div><strong>{r.data.category||r.data.title}</strong><span className={over?'negative':''}>{money(spent,m.currency)} <small>/ {money(r.data.amount,m.currency)}</small></span></div><AnimatedProgress value={r.data.amount?spent/r.data.amount*100:spent?100:0}/><p className={over?'negative':'muted'}>{over?`${money(spent-r.data.amount,m.currency)} over budget`:`${money(r.data.amount-spent,m.currency)} remaining`} · {r.data.repeats?'Repeats monthly':'This month'}<Actions r={r} tools={tools}/></p></div>;})}</>;}
 const expected=sources.filter(r=>r.data.active&&!settledTransaction(s.records,r.id,month)).reduce((n,r)=>n+r.data.amount,0);const pending=bills.filter(r=>r.data.active&&!settledTransaction(s.records,r.id,month));const reserved=pending.reduce((n,r)=>n+r.data.amount,0);const afterBills=m.saved-reserved;
 const addSource=()=>tools.add('cashPlan',{type:'income',category:'Salary'});const addBill=()=>tools.add('cashPlan',{type:'expense',category:'Housing'});
 return <div className="finance-workspace">
 {section===''&&<><Card className="finance-hero"><div><span className="finance-kicker">YOUR MONTH, AT A GLANCE</span><p>Net cash flow</p><strong className={m.saved>=0?'positive':'negative'}>{money(m.saved,m.currency)}</strong><small>{money(m.income,m.currency)} received · {money(m.expenses,m.currency)} spent</small></div><div className="finance-hero-action"><div><span>After your unpaid bills</span><strong className={afterBills>=0?'positive':'negative'}>{money(afterBills,m.currency)}</strong></div><p>{pending.length?`${pending.length} unpaid bill${pending.length===1?'':'s'} · ${money(reserved,m.currency)} reserved`:'No unpaid bills planned. Add bills for a clearer picture.'}</p><div className="inline-actions"><Button variant="primary" onClick={()=>tools.add('transaction',{type:'income',category:'Salary'})}><Plus size={15}/>Add income</Button><Button onClick={()=>tools.add('transaction',{type:'expense'})}><Plus size={15}/>Add expense</Button></div></div></Card>
 <div className="finance-options">{financePages.slice(0,6).map(p=><Link href={`/finance/${p.slug}?month=${month}`} key={p.slug}><span className="finance-option-icon"><p.icon size={20}/></span><div><strong>{p.title}</strong><p>{p.description}</p></div><ChevronRight size={16}/></Link>)}</div>
 <div className="finance-summary-strip"><div><span>Income received</span><strong className="positive">{money(m.income,m.currency)}</strong><small>{money(expected,m.currency)} still expected from active sources</small></div><div><span>Spent so far</span><strong>{money(m.expenses,m.currency)}</strong><small>{m.categories.length} spending categories</small></div><div><span>Savings rate</span><strong className={m.saved<0?'negative':'positive'}>{m.savingsRate===null?'—':`${Math.round(m.savingsRate)}%`}</strong><small>{m.income?'Of actual income retained':'Add income to calculate this'}</small></div></div>
 <div className="finance-overview-grid"><Card><div className="panel-heading"><div><h2>Money coming in</h2><p>Expected income stays separate from your actual totals.</p></div><Link href={`/finance/income?month=${month}`} aria-label="Manage income sources"><ArrowRight size={17}/></Link></div>{sources.length?<PlanRows plans={sources} compact/>:<Blank title="Plan your next income" description="Add salary, freelance work or regular business income." onAdd={addSource} label="Add income source"/>}</Card><Card><div className="panel-heading"><div><h2>Bills to keep in view</h2><p>{money(reserved,m.currency)} still to pay this month</p></div><Link href={`/finance/bills?month=${month}`} aria-label="Manage bills"><ArrowRight size={17}/></Link></div>{bills.length?<PlanRows plans={bills} compact/>:<Blank title="No bills planned" description="Add rent, internet and other regular payments." onAdd={addBill} label="Add bill"/>}</Card></div>
 <div className="chart-grid">{charts}</div><Card><div className="panel-heading"><div><h2>Spending limits</h2><p>Progress comes from actual transactions in the selected month.</p></div><Link href={`/finance/budgets?month=${month}`} className="button">Manage budgets <ArrowRight size={14}/></Link></div>{budgets.length?<BudgetRows/>:<Blank title="Give your spending a limit" description="Set an overall plan or budgets for individual categories." onAdd={()=>tools.add('budget',{month})} label="Set budget"/>}</Card>
 <Link href={`/finance/recurring?month=${month}`} className="finance-schedule-link"><Repeat2 size={17}/>Automatic recurring entries<span>Manage schedules <ArrowRight size={15}/></span></Link></>}
 {(section==='income'||section==='bills')&&<Card><div className="panel-heading"><div><h2>{section==='income'?'Your regular income':'Your monthly bills'}</h2><p>{section==='income'?'Add each source once. Mark received on the day it actually arrives.':'Add regular bills once. Mark paid when you make the payment.'} Plans repeat each month; payments require your confirmation.</p></div><Button variant="primary" onClick={section==='income'?addSource:addBill}><Plus size={16}/>{section==='income'?'Add income source':'Add bill'}</Button></div>{(section==='income'?sources:bills).length?<PlanRows plans={section==='income'?sources:bills}/>:<Blank title={section==='income'?'No income sources yet':'No bills yet'} description="Create a plan and keep your actual transactions accurate." label={section==='income'?'Add income source':'Add bill'} onAdd={section==='income'?addSource:addBill}/>}</Card>}
 {section==='budgets'&&<><Card><div className="panel-heading"><div><h2>Monthly budgets</h2><p>Category limits or one overall limit. Repeating limits carry into future months.</p></div><Button variant="primary" onClick={()=>tools.add('budget',{month,repeats:true})}><Plus size={16}/>Add budget</Button></div>{budgets.length?<BudgetRows/>:<Blank title="No budgets set" description="Choose a category and an amount that fits your month." label="Set budget" onAdd={()=>tools.add('budget',{month,repeats:true})}/>}</Card><Card><div className="panel-heading"><div><h2>Custom categories</h2><p>Make categories fit your life. Removing a choice keeps existing transaction history.</p></div><Button onClick={()=>tools.add('financeCategory')}><Plus size={15}/>Add category</Button></div>{recordsOf(s.records,'financeCategory').map(r=><div className="finance-category-row" key={r.id}><strong>{r.data.title}</strong><small>{r.data.type}</small><Actions r={r} tools={tools}/></div>)}{!recordsOf(s.records,'financeCategory').length&&<p className="muted">You can also type a category when adding a transaction or plan.</p>}</Card></>}
 {section==='transactions'&&transactions}
 {section==='savings'&&<Savings s={s} tools={tools} currency={m.currency}/>}
 {section==='recurring'&&<Card><div className="panel-heading"><div><h2>Automatic recurring entries</h2><p>These schedules create transactions automatically when due. Manual bills and income sources use confirmation instead.</p></div><Button onClick={()=>tools.add('recurring')}><Plus size={16}/>Add schedule</Button></div>{recordsOf(s.records,'recurring').filter(r=>r.data.currency===m.currency).map(r=><div className="finance-category-row" key={r.id}><div><strong>{r.data.title}</strong><small>{r.data.frequency} · next {r.data.nextDate} · {r.data.enabled?'Active':'Paused'}</small></div><strong>{money(r.data.amount,r.data.currency)}</strong><button className="icon-button" aria-label={`${r.data.enabled?'Pause':'Resume'} ${r.data.title}`} onClick={()=>tools.toggle(r,'enabled')}>{r.data.enabled?<Pause size={15}/>:<Play size={15}/>}</button><Actions r={r} tools={tools}/></div>)}{!recordsOf(s.records,'recurring').some(r=>r.data.currency===m.currency)&&<Blank title="No automatic schedules" description="Keep regular entries on schedule. Use Bills for manually confirmed payments." label="Create schedule" onAdd={()=>tools.add('recurring')}/>}</Card>}
 {section==='calculators'&&<><Card className="finance-tool-intro"><span className="finance-kicker">YOUR FINANCE TOOLKIT</span><h2>Six practical calculators</h2><p>Choose a tool. Adjust the inputs and see a clear estimate without changing your ledger.</p></Card><div className="finance-options calculator-options">{calculators.map(p=><Link key={p.slug} href={`/finance/calculators/${p.slug}?month=${month}`}><span className="finance-option-icon"><p.icon size={22}/></span><div><strong>{p.title}</strong><p>{p.description}</p></div><ChevronRight size={16}/></Link>)}</div></>}
 {section.startsWith('calculators/')&&<FinanceCalculator name={section.split('/')[1]} currency={m.currency}/>}
 {section&&!financePages.some(p=>p.slug===section)&&!section.startsWith('calculators/')&&<Blank title="Finance page not found" description="Choose a page from the Finance menu above."/>}
 <Dialog open={!!payment} onOpenChange={open=>{if(!open&&!settle.isPending)setPayment(null);}} title={payment?.data.type==='income'?'Record received income':'Record paid bill'} description="Confirm the actual date. This creates one linked transaction for this month.">{payment&&<form className="finance-confirm" onSubmit={e=>{e.preventDefault();settle.mutate({plan:payment,date:paymentDate});}}><div className="finance-payment-summary"><span>{payment.data.title}</span><strong>{money(payment.data.amount,payment.data.currency)}</strong></div><label>Payment date<input type="date" aria-label="Payment date" value={paymentDate} min={`${month}-01`} max={month===today.slice(0,7)?today:planDate(month,31)} required onChange={e=>setPaymentDate(e.target.value)}/></label>{settle.isError&&<p role="alert" className="error">{settle.error.message}</p>}<Button variant="primary" disabled={settle.isPending}>{settle.isPending?'Recording…':payment.data.type==='income'?'Confirm received':'Confirm paid'}</Button></form>}</Dialog>
 </div>;
}

function Savings({s,tools,currency}:{s:Snapshot;tools:Tools;currency:string}){const goals=recordsOf(s.records,'goal').filter(r=>r.data.unit===currency);const [selected,setSelected]=useState<LedgerRecord<'goal'>|null>(null);const [amount,setAmount]=useState('');const client=useQueryClient();const mutation=useMutation({mutationFn:()=>{const deposit=parseMoneyInput(amount);if(!Number.isFinite(deposit)||deposit<=0)throw new Error('Enter an amount above zero with up to two decimals.');return adapter.save({...selected!,data:{...selected!.data,current:(Math.round(selected!.data.current*100)+deposit)/100}});},onSuccess:async()=>{await client.invalidateQueries({queryKey:['snapshot']});setSelected(null);}});return <><div className="section-toolbar"><span className="muted">Track money set aside; contributions do not create income.</span><Button variant="primary" onClick={()=>tools.add('goal',{unit:currency,current:0,target:5000})}><Plus size={16}/>New savings goal</Button></div><div className="finance-overview-grid">{goals.map(r=><Card key={r.id}><div className="panel-heading"><span className="finance-option-icon"><PiggyBank size={23}/></span><Actions r={r} tools={tools}/></div><h2>{r.data.title}</h2><p className="muted">{r.data.description}</p><div className="finance-savings-value"><strong className="positive">{money(Math.round(r.data.current*100),currency)}</strong><span>of {money(Math.round(r.data.target*100),currency)}</span></div><AnimatedProgress value={r.data.current/r.data.target*100}/><p className="finance-savings-remaining">{money(Math.max(0,Math.round((r.data.target-r.data.current)*100)),currency)} to go · Target {r.data.deadline}</p><Button disabled={!r.data.active} onClick={()=>{mutation.reset();setAmount('');setSelected(r);}}><Plus size={15}/>Add contribution</Button></Card>)}</div>{!goals.length&&<Card><Blank title="Start a savings goal" description="Give your emergency fund, holiday or next big purchase a target." label="Create savings goal" onAdd={()=>tools.add('goal',{unit:currency,current:0,target:5000})}/></Card>}<Dialog open={!!selected} onOpenChange={open=>{if(!open&&!mutation.isPending)setSelected(null);}} title="Add savings contribution" description="Update money set aside toward this goal. Your income and expense totals stay unchanged."><form className="finance-confirm" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><label>Contribution ({currency})<input aria-label="Contribution" inputMode="decimal" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>{mutation.isError&&<p className="error" role="alert">{mutation.error.message}</p>}<Button variant="primary" disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Save contribution'}</Button></form></Dialog></>;}

function FinanceCalculator({name,currency}:{name:string;currency:string}){
 const info=calculators.find(c=>c.slug===name);const [inputs,setInputs]=useState<Record<string,string>>({principal:'100000',rate:'8',years:'5',start:'10000',deposit:'1000',goal:'50000',saved:'5000',months:'12',base:'10000',percentage:'15',balance:'10000',payment:'500',revenue:'10000',costs:'6000',price:'100',variable:'40',fixed:'1000'});const [operation,setOperation]=useState('add');
 const n=(key:string)=>inputs[key]?.trim()===''?NaN:Number(inputs[key]);const field=(key:string,label:string,suffix='',integer=false)=><label key={key}><span>{label}{suffix&&<small>{suffix}</small>}</span><input aria-label={label} type="number" min="0" step={integer?'1':'any'} value={inputs[key]} onChange={e=>setInputs({...inputs,[key]:e.target.value})}/></label>;const format=(v:number)=>money(Math.round(v*100),currency);let result:ReactNode;let form:ReactNode;let note='';const output=(label:string,value:string,positive?:boolean)=><div><span>{label}</span><strong className={positive===undefined?'':positive?'positive':'negative'}>{value}</strong></div>;
 if(name==='loan'){const estimate=loanEstimate(n('principal'),n('rate'),n('years')*12);form=<>{field('principal','Loan amount',currency)}{field('rate','Annual interest rate','%')}{field('years','Term','years')}</>;result=estimate?<>{output('Monthly payment',format(estimate.payment))}{output('Total interest',format(estimate.interest))}{output('Total repaid',format(estimate.total))}</>:null;note='Fixed annual interest, monthly payments. Excludes fees, taxes and insurance.';}
 else if(name==='growth'){const estimate=savingsEstimate(n('start'),n('deposit'),n('rate'),n('years')*12);form=<>{field('start','Starting amount',currency)}{field('deposit','Monthly deposit',currency)}{field('rate','Annual return','%')}{field('years','Years')}</>;result=estimate?<>{output('Projected value',format(estimate.total),true)}{output('Your contributions',format(estimate.contributed))}{output('Estimated growth',format(estimate.interest),true)}</>:null;note='Assumes a constant return compounded monthly and deposits at month end. Returns are estimates, not guaranteed.';}
 else if(name==='goal'){const remaining=n('goal')-n('saved');const valid=Number.isFinite(remaining+n('months'))&&Math.min(n('goal'),n('saved'))>=0&&Number.isInteger(n('months'))&&n('months')>0&&n('months')<=1200;form=<>{field('goal','Goal amount',currency)}{field('saved','Already saved',currency)}{field('months','Months available','months',true)}</>;result=valid?<>{output('Save each month',format(Math.max(0,remaining)/n('months')),true)}{output('Still to save',format(Math.max(0,remaining)))}</>:null;note='A simple savings plan with no assumed interest or investment return.';}
 else if(name==='percentage'){const part=n('base')*n('percentage')/100;const valid=Number.isFinite(part)&&Math.min(n('base'),n('percentage'))>=0&&(operation!=='subtract'||n('percentage')<=100);form=<>{field('base','Base amount',currency)}{field('percentage','Percentage','%')}<label><span>Operation</span><select aria-label="Operation" value={operation} onChange={e=>setOperation(e.target.value)}><option value="add">Add percentage</option><option value="subtract">Subtract percentage</option><option value="of">Percentage of amount</option></select></label></>;result=valid?<>{output('Percentage amount',format(part))}{output('Result',format(operation==='add'?n('base')+part:operation==='subtract'?n('base')-part:part))}</>:null;note='Use for a discount, markup or a simple percentage calculation.';}
 else if(name==='debt'){const estimate=debtEstimate(n('balance'),n('rate'),n('payment'));form=<>{field('balance','Debt balance',currency)}{field('rate','Annual interest rate','%')}{field('payment','Monthly payment',currency)}</>;result=estimate?(estimate.unpayable?<p className="negative" role="status">This payment does not clear the balance within 100 years. Increase the monthly payment.</p>:<>{output('Time to clear',`${estimate.months} months`)}{output('Total interest',format(estimate.interest))}</>):null;note='Fixed monthly interest; payments at month end. Excludes fees and new borrowing.';}
 else if(name==='profit'){const profit=n('revenue')-n('costs');const margin=n('revenue')>0?profit/n('revenue')*100:null;const valid=Number.isFinite(profit+n('price')+n('variable')+n('fixed'))&&Math.min(n('revenue'),n('costs'),n('price'),n('variable'),n('fixed'))>=0;form=<>{field('revenue','Revenue',currency)}{field('costs','Total costs',currency)}{field('price','Price per unit',currency)}{field('variable','Variable cost per unit',currency)}{field('fixed','Fixed costs',currency)}</>;result=valid?<>{output(profit<0?'Loss':'Profit',format(profit),profit>=0)}{output('Profit margin',margin===null?'—':`${margin.toFixed(1)}%`,profit>=0)}{output('Break-even units',n('price')>n('variable')?String(Math.ceil(n('fixed')/(n('price')-n('variable')))):'Not achievable at this unit price')}</>:null;note='Profit uses revenue minus total costs. Break-even separately uses fixed costs and per-unit contribution. Excludes tax.';}
 if(!info)return <Card><Blank title="Calculator not found" description="Go back to the calculators and choose a tool."/></Card>;
 return <Card className="finance-calculator"><div className="panel-heading"><div><span className="finance-kicker">{currency} TOOLKIT</span><h2>{info.title}</h2><p>{info.description}</p></div><span className="finance-option-icon"><info.icon size={24}/></span></div><div className="finance-calculator-layout"><div className="finance-calculator-inputs">{form}</div><div className="finance-calculator-results" aria-live="polite">{result||<p className="muted">Enter valid non-negative values. Terms must be whole months between 1 and 1,200.</p>}</div></div><p className="finance-calculator-note">{note}</p></Card>;
}



