'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Target,Wallet,ListChecks,Flag,Plus,Pencil,Trash2,ArrowRight,CalendarDays} from 'lucide-react';
import {goalProgress,recordsOf,type Snapshot,type Kind,type LedgerRecord} from '@ledger/shared';
import {Entrance,AnimatedProgress,CountUp} from './animation';
import {HabitToggle} from './habit-checklist';
import {Button} from './ui/button';
import {EmptyState} from './empty-state';

export function GoalPlanner({s,today,goalId,onAdd,onEdit,onRemove,onToggle}:{s:Snapshot;today:string;goalId?:string;onAdd:(kind:Kind,initial?:Record<string,unknown>)=>void;onEdit:(r:LedgerRecord)=>void;onRemove:(r:LedgerRecord)=>void;onToggle:(r:LedgerRecord)=>void}){
 const [filter,setFilter]=useState('active');const goals=recordsOf(s.records,'goal').filter(g=>goalId?g.id===goalId:filter==='all'||(filter==='completed'?goalProgress(g,s.records).done:g.data.active&&!goalProgress(g,s.records).done));
 const deadline=new Date(today+'T12:00:00Z');deadline.setUTCDate(deadline.getUTCDate()+30);
 const start=(initial:Record<string,unknown>)=>onAdd('goal',{current:0,target:100,unit:'steps',tracking:'steps',deadline:deadline.toISOString().slice(0,10),...initial});
 return <>{!goalId&&<><Entrance className="panel goal-start"><div className="panel-heading"><div><span className="eyebrow">ONE SMALL STEP AT A TIME</span><h2>What do you want to make happen?</h2><p>Choose a starting point, then turn it into a plan you can act on.</p></div><Target size={24}/></div><div className="goal-presets">
 <button onClick={()=>start({title:'Save for something important',tracking:'manual',unit:s.profile.currency,target:1000,description:'Give your money a clear destination.'})}><Wallet/><strong>Save for something</strong><span>Set an amount and update money saved.</span><ArrowRight size={16}/></button>
 <button onClick={()=>start({title:'Finish my project',description:'Break the project into small, finishable steps.'})}><ListChecks/><strong>Finish a project</strong><span>Complete steps to grow your progress.</span><ArrowRight size={16}/></button>
 <button onClick={()=>start({title:'My personal milestone',description:'Make room for something that matters to you.'})}><Flag/><strong>A personal milestone</strong><span>Learning, life plans, or something new.</span><ArrowRight size={16}/></button>
 </div></Entrance><div className="section-toolbar"><div className="segmented" aria-label="Goal filter">{['active','completed','all'].map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{v}</button>)}</div><Button onClick={()=>start({})}><Plus size={16}/>New goal</Button></div></>}
 <div className={goalId?"goal-detail-layout":"two-grid"}>{goals.map(goal=>{const progress=goalProgress(goal,s.records),stepBased=goal.data.tracking==='steps';const days=Math.ceil((Date.parse(goal.data.deadline+'T12:00:00Z')-Date.parse(today+'T12:00:00Z'))/86400000);const next=progress.steps.find(r=>!r.data.done);return <Entrance className="panel actionable-goal" key={goal.id} data-record-id={`card-${goal.id}`} data-motion-state={String(goal.version)}><div className="panel-heading"><span className="goal-icon"><Target/></span><div className="row-actions"><button className="icon-button" aria-label={`Edit ${goal.data.title}`} onClick={()=>onEdit(goal)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${goal.data.title}`} onClick={()=>onRemove(goal)}><Trash2 size={16}/></button></div></div><span className="goal-mode">{stepBased?'Checklist progress':'Amount progress'} · {progress.done?'Achieved':goal.data.active?'In progress':'Archived'}</span><h2>{goalId?goal.data.title:<Link href={`/goals/${goal.id}`}>{goal.data.title} <ArrowRight size={16}/></Link>}</h2>{goal.data.description&&<p className="muted">{goal.data.description}</p>}<div className="goal-values"><div><CountUp value={Math.round(progress.current*100)} format={v=>(v/100).toLocaleString()}/><small> / {progress.target.toLocaleString()} {stepBased?'steps':goal.data.unit}</small></div><CountUp value={Math.round(progress.percentage)} format={v=>`${v}%`}/></div><AnimatedProgress value={progress.percentage}/><p className="goal-deadline"><CalendarDays size={14}/>{progress.done?'You reached this goal.':days<0?`${Math.abs(days)} days past target`:days===0?'Target is today':`${days} days left`}<time>{goal.data.deadline}</time></p>
 <div className="goal-next"><small>YOUR NEXT STEP</small><strong>{progress.done?'Take a moment to celebrate.':next?.data.title|| (stepBased?'Add your first actionable step.':`${Math.max(0,progress.target-progress.current).toLocaleString()} ${goal.data.unit} still to go.`)}</strong>{!stepBased&&!progress.done&&<Button onClick={()=>onEdit(goal)}>Update progress <ArrowRight size={14}/></Button>}</div>
 <div className="goal-step-list">{progress.steps.map(step=><div key={step.id} data-record-id={`milestone-${step.id}`} data-motion-state={String(step.version)}><HabitToggle checked={step.data.done} disabled={false} label={`Complete ${step.data.title}`} onChange={()=>onToggle(step)}/><span className={step.data.done?'completed':''}>{step.data.title}</span><div className="row-actions"><button className="icon-button" aria-label={`Edit ${step.data.title}`} onClick={()=>onEdit(step)}><Pencil size={14}/></button><button className="icon-button" aria-label={`Delete ${step.data.title}`} onClick={()=>onRemove(step)}><Trash2 size={14}/></button></div></div>)}</div><Button onClick={()=>onAdd('milestone',{goalId:goal.id})}><Plus size={15}/>Add step</Button>{!stepBased&&<small className="goal-explanation">Steps help you plan. Update the amount separately when you make progress.</small>}</Entrance>;})}</div>{!goals.length&&<Entrance className="panel"><EmptyState title={goalId?'This goal is no longer available':filter==='completed'?'Your next achievement is ahead':'Give your next goal a clear path'} description="Choose a template above or create a goal of your own." variant="goal" label="Create goal" onAdd={()=>start({})}/></Entrance>}</>;
}
