'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {Check,Minus,Flame,ChevronLeft,ChevronRight,Plus,Pencil,Trash2} from 'lucide-react';
import {calendarWeeks,habitStats,recordsOf,type Snapshot,type LedgerRecord} from '@ledger/shared';
import {Entrance,AnimatedProgress,CountUp} from './animation';
import {Button} from './ui/button';
import {EmptyState} from './empty-state';
type Habit=LedgerRecord<'habit'>;
function HabitMark({checked,missed,rest}:{checked:boolean;missed:boolean;rest:boolean}){
 return <i className="habit-check-mark" aria-hidden="true">{checked?<Check size={16}/>:rest?<Minus size={13}/>:missed?<span className="missed-dot"/>:null}</i>;
}
export function HabitToggle({checked,disabled,label,onChange}:{checked:boolean;disabled:boolean;label:string;onChange:()=>void}){return <label className={`habit-toggle ${checked?'checked':''}`}><input type="checkbox" checked={checked} disabled={disabled} aria-label={label} onChange={onChange}/><HabitMark checked={checked} missed={false} rest={false}/></label>;}
export function HabitChecklist({s,month,today,pending,onComplete,onAdd,onEdit,onRemove}:{s:Snapshot;month:string;today:string;pending:boolean;onComplete:(h:Habit,date:string)=>void;onAdd:()=>void;onEdit:(h:Habit)=>void;onRemove:(h:Habit)=>void}){
 const weeks=calendarWeeks(month),initial=Math.max(0,weeks.findIndex(w=>w.includes(today)));
 const [week,setWeek]=useState(initial);useEffect(()=>setWeek(Math.max(0,calendarWeeks(month).findIndex(w=>w.includes(today)))),[month,today]);
 const dates=weeks[Math.min(week,weeks.length-1)],habits=recordsOf(s.records,'habit'),done=new Set(recordsOf(s.records,'completion').map(c=>`${c.data.habitId}:${c.data.date}`));
 const dateLabel=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric'});
 return <Entrance className="panel weekly-habits" id="habits"><div className="panel-heading"><div><h2>Weekly habit checklist</h2><p>Check today’s scheduled habits. Past days keep your history; rest days protect your streak.</p></div><Button onClick={onAdd}><Plus size={15}/>New habit</Button></div><div className="habit-week-nav"><Button aria-label="Earlier habit week" disabled={week===0} onClick={()=>setWeek(v=>v-1)}><ChevronLeft size={15}/>Earlier</Button><span>{dates.includes(today)?'This week':`${dateLabel(dates[0])} – ${dateLabel(dates[6])}`}</span><Button aria-label="Later habit week" disabled={week>=weeks.length-1||dates[6]>=today} onClick={()=>setWeek(v=>v+1)}>Later<ChevronRight size={15}/></Button></div>
 {habits.map((h,index)=>{const stats=habitStats(h,s.records,today);const scheduled=dates.filter(d=>d>=h.data.startDate&&h.data.days.includes(new Date(d+'T12:00:00Z').getUTCDay()));const completed=scheduled.filter(d=>done.has(`${h.id}:${d}`)).length;
 return <article key={h.id} data-record-id={`habit-week-${h.id}`} data-motion-state={String(h.version)} className="weekly-habit" style={{'--habit-color':['#80e4bd','#a894ff','#83c8ff','#f3b08f'][index%4]} as CSSProperties}><div className="habit-card-heading"><div><h3>{h.data.title}</h3><p>{!h.data.active?'Paused':h.data.days.length===7?'Daily':`${h.data.days.length} days a week`}</p></div><div className="row-actions"><button className="icon-button" aria-label={`Edit ${h.data.title}`} onClick={()=>onEdit(h)}><Pencil size={16}/></button><button className="icon-button" aria-label={`Delete ${h.data.title}`} onClick={()=>onRemove(h)}><Trash2 size={16}/></button></div></div><div className="habit-day-grid">{dates.map(date=>{const isScheduled=scheduled.includes(date),checked=done.has(`${h.id}:${date}`),missed=isScheduled&&date<today&&!checked,editable=h.data.active&&isScheduled&&date===today&&!pending,status=checked?'Completed':!isScheduled?'Rest day':date>today?'Upcoming':missed?'Missed':'Due today';return <button key={date} className={`habit-day ${date===today?'today':''} ${checked?'checked':''} ${missed?'missed':''} ${!isScheduled?'rest':''}`} aria-label={`${h.data.title}, ${date}, ${status}`} aria-pressed={checked} disabled={!editable} onClick={()=>onComplete(h,date)}><span>{new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'short'})}</span><strong>{Number(date.slice(-2))}</strong><HabitMark checked={checked} missed={missed} rest={!isScheduled}/><small>{status}</small></button>;})}</div><div className="habit-card-footer"><div><span>{dateLabel(dates[0])} – {dateLabel(dates[6])} · {completed}/{scheduled.length} done</span><AnimatedProgress value={scheduled.length?completed/scheduled.length*100:0}/></div><div className="habit-streak"><Flame size={17}/><CountUp value={stats.current} format={v=>`${v} current`}/><span>·</span><CountUp value={stats.best} format={v=>`${v} best`}/></div></div></article>;
 })}{!habits.length&&<EmptyState title="Your first habit" description="Choose a routine and make a little progress each day." variant="task" label="Create habit" onAdd={onAdd}/>}
 </Entrance>;
}
