'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {Plus,ShoppingBasket,ArrowRight,Utensils} from 'lucide-react';
import {recordsOf,type Snapshot,type LedgerRecord} from '@ledger/shared';
import {adapter} from '../lib/data';
import {Entrance,CountUp,AnimatedProgress,Ring} from './animation';
import {HabitToggle} from './habit-checklist';
import {Button} from './ui/button';

export function MealHealth({s,dates}:{s:Snapshot;dates:string[]}){
 const meals=recordsOf(s.records,'meal').filter(m=>dates.includes(m.data.date)),eaten=meals.filter(m=>m.data.eaten),withNutrition=eaten.filter(m=>m.data.nutrition?.calories!==undefined);const total=(key:'calories'|'protein'|'carbs'|'fat')=>eaten.reduce((n,m)=>n+(m.data.nutrition?.[key]||0),0);
 return <Entrance className="panel meal-health"><div className="panel-heading"><div><h2>Your week, one meal at a time</h2><p>Check meals after eating. Totals count one serving per checked meal, using only nutrition values you entered.</p></div><Utensils size={22}/></div><div className="meal-health-stats"><div className="meal-check-progress"><CountUp value={eaten.length} format={v=>`${v} / ${meals.length}`}/><small>meals eaten</small><Ring value={meals.length?eaten.length/meals.length*100:0}/></div>{(['calories','protein','carbs','fat'] as const).map(key=><div key={key}><small>{key==='calories'?'Recorded energy':key[0].toUpperCase()+key.slice(1)}</small>{eaten.some(m=>m.data.nutrition?.[key]!==undefined)?<CountUp value={Math.round(total(key))} format={v=>`${v.toLocaleString()} ${key==='calories'?'kcal':'g'}`}/>:<strong>—</strong>}</div>)}</div><AnimatedProgress value={meals.length?eaten.length/meals.length*100:0}/><p className="guide-note">{withNutrition.length} of {eaten.length} eaten meals have energy values. Missing values are not treated as measured zero intake.</p><div className="healthy-meal-tips"><article><strong>Breakfast</strong><p>Pair a protein food with whole grains and fruit. Oats, yogurt and fruit are one editable starting idea.</p></article><article><strong>Lunch & dinner</strong><p>Build around vegetables, a protein food and a whole-grain option. Choose portions that suit your appetite.</p></article><article><strong>Snacks & hydration</strong><p>Try fruit, plain yogurt or a small portion of nuts if suitable. Keep water accessible; check allergy labels.</p></article><article><strong>Prep & shopping</strong><p>Check your kitchen first, plan leftovers and buy ingredients you can use across meals.</p></article></div><p className="guide-note">General food-planning ideas, not medical treatment. <a href="https://www.myplate.gov/eathealthy/budget/budget-weekly-meals" target="_blank" rel="noreferrer">MyPlate planning reference</a> · <a href="https://www.cdc.gov/healthy-weight-growth/healthy-eating/meals-snacks.html" target="_blank" rel="noreferrer">CDC meals & snacks</a></p></Entrance>;
}

export function MealGroceries({s,dates}:{s:Snapshot;dates:string[]}){
 const client=useQueryClient(),[pending,setPending]=useState(false),[message,setMessage]=useState('');const meals=recordsOf(s.records,'meal').filter(m=>dates.includes(m.data.date));
 async function add(){setPending(true);setMessage('');let count=0;const existing=new Set(recordsOf(s.records,'grocery').map(g=>g.data.title.toLowerCase().trim()));try{for(const meal of meals){for(const ingredient of (meal.data.ingredients||'').split(',').map(v=>v.trim()).filter(Boolean)){const key=ingredient.toLowerCase();if(existing.has(key))continue;if(ingredient.length>160)throw new Error('Keep each ingredient name under 160 characters.');const result=await adapter.save({kind:'grocery',data:{title:ingredient,quantity:`For ${meal.data.servings||1} serving(s) · set shopping quantity`,cost:0,currency:s.profile.currency,done:false,mealId:meal.id}});existing.add(key);client.setQueryData<Snapshot>(['snapshot'],snapshot=>snapshot?{...snapshot,records:[...snapshot.records.filter(r=>r.id!==result.id),result]}:snapshot);count++;}}setMessage(count?`${count} ingredients added. Review quantities and estimated costs below.`:'Your list already includes these ingredients.');}catch(e){setMessage(`${count} ingredients saved. ${(e as Error).message} Retry to add the remaining items.`);}finally{await client.invalidateQueries({queryKey:['snapshot']});setPending(false);}}
 return <div className="meal-grocery-connect"><div><strong>Shop from your meal plan</strong><p>Add comma-separated ingredients to each meal. Existing grocery items are kept.</p></div><Button disabled={pending||!meals.some(m=>m.data.ingredients?.trim())} onClick={()=>void add()}><ShoppingBasket size={15}/>{pending?'Adding ingredients…':'Add missing groceries'}</Button>{message&&<p role="status">{message}</p>}</div>;
}

export function MealDetail({meal,onEdit,onToggle,pending}:{meal:LedgerRecord<'meal'>;onEdit:()=>void;onToggle:()=>void;pending:boolean}){
 return <Entrance className="panel meal-detail"><div className="panel-heading"><div><span className="eyebrow">{meal.data.slot} · {meal.data.date}</span><h2>Your meal, your way</h2><p>{meal.data.servings||1} serving(s) · edit ingredients and portions to suit your week.</p></div><Button onClick={onEdit}><Plus size={14}/>Edit meal</Button></div><div className="meal-eaten-toggle"><HabitToggle checked={meal.data.eaten||false} disabled={pending} label={`Eaten ${meal.data.title}`} onChange={onToggle}/><span>{meal.data.eaten?'Meal eaten':'Mark after eating'}</span></div><div className="two-grid"><div><h3>Ingredients to shop for</h3><ul>{(meal.data.ingredients||'').split(',').filter(v=>v.trim()).map((item,i)=><li key={i}>{item.trim()}</li>)}</ul>{!meal.data.ingredients&&<p>Add ingredients to connect this meal to your grocery list.</p>}<h3>Portion & preparation notes</h3><p className="meal-prep-notes">{meal.data.notes||'Add your preparation steps, portion notes and substitutions.'}</p></div><div><h3>Nutrition per serving</h3><p>Optional values from the package label or a recipe source you trust.</p><div className="meal-nutrition-values">{(['calories','protein','carbs','fat'] as const).map(key=><div key={key}><span>{key}</span><strong>{meal.data.nutrition?.[key]===undefined?'Not entered':`${meal.data.nutrition[key]} ${key==='calories'?'kcal':'g'}`}</strong></div>)}</div><p>Review ingredients for allergies. Substitute foods to suit your needs; weight alone does not determine your diet.</p></div></div><Link href="/meals" className="button">Back to your meal plan <ArrowRight size={14}/></Link></Entrance>;
}
