'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,LoaderCircle,LockKeyhole,Mail,ShieldCheck} from 'lucide-react';
import {BrandMark} from './brand-mark';
import {apiBase} from '../lib/data';
type Challenge={id:string;email:string;purpose:'signup'|'reset';expiresAt:string;resendAt:string};
export function OtpVerification(){
 const [challenge,setChallenge]=useState<Challenge|null>(null),[csrf,setCsrf]=useState(''),[digits,setDigits]=useState<string[]>(Array(6).fill('')),[message,setMessage]=useState(''),[pending,setPending]=useState(false),[now,setNow]=useState(Date.now());
 const inputs=useRef<(HTMLInputElement|null)[]>([]);
 useEffect(()=>{const controller=new AbortController();async function load(){try{const [session,response]=await Promise.all([fetch(`${apiBase}/auth/csrf`,{credentials:'include',signal:controller.signal}),fetch(`${apiBase}/auth/otp`,{credentials:'include',signal:controller.signal})]);const data=await response.json();if(!response.ok)throw new Error(data.error);if(!session.ok)throw new Error('The authentication service could not be reached.');setCsrf((await session.json()).csrf);setChallenge(data);}catch(e){if(!controller.signal.aborted)setMessage((e as Error).message);}}void load();const timer=setInterval(()=>setNow(Date.now()),1000);return()=>{controller.abort();clearInterval(timer);};},[]);
 const reset=challenge?.purpose==='reset',wait=challenge?Math.max(0,Math.ceil((Date.parse(challenge.resendAt)-now)/1000)):0,expired=!!challenge&&Date.parse(challenge.expiresAt)<=now;
 async function post(path:string,body:object){const response=await fetch(`${apiBase}/auth/otp/${path}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Verification could not be completed.');return data;}
 async function verify(e:React.FormEvent){e.preventDefault();if(pending)return;setPending(true);setMessage('');try{const data=await post('verify',{code:digits.join('')});if(reset){sessionStorage.setItem('daily-ledger-reset-proof',JSON.stringify({id:data.id,token:data.token}));window.location.assign('/reset-password');}else window.location.assign('/');}catch(e){setMessage((e as Error).message);setPending(false);}}
 async function resend(){if(pending||wait)return;setPending(true);setMessage('');try{setChallenge(await post('resend',{}));setDigits(Array(6).fill(''));setNow(Date.now());setMessage(reset?'If an email/password account exists, a new code will arrive shortly.':'A new code has been sent. Check your inbox and spam folder.');inputs.current[0]?.focus();}catch(e){setMessage((e as Error).message);}finally{setPending(false);}}
 function change(index:number,value:string){const clean=value.replace(/\D/g,'').slice(0,6-index);setDigits(current=>{const next=[...current];if(!clean)next[index]='';else clean.split('').forEach((digit,offset)=>next[index+offset]=digit);return next;});if(clean)inputs.current[Math.min(index+clean.length,5)]?.focus();}
 return <div className="auth-column otp-column"><Link className="otp-back" href={reset?'/forgot-password':'/signup'}><ArrowLeft size={15}/>{reset?'Change email':'Back to signup'}</Link><div className="otp-progress"><span><Check size={14}/>{reset?'Account email':'Account details'}</span><i/><strong><b>2</b>Verify email</strong></div><Link href="/" className="auth-brand" aria-label="Daily Ledger home"><BrandMark/></Link><p className="otp-brand-name">Daily Ledger</p><div className="otp-symbol"><Mail size={29}/><ShieldCheck size={18}/></div><h1>{reset?'Verify your reset code':'Verify your email'}</h1><p className="auth-subtitle">Enter the 6-digit code sent to<br/><strong>{challenge?.email||'your email address'}</strong></p><form onSubmit={verify} className="otp-form"><div className="otp-digits" role="group" aria-label="Six-digit verification code">{digits.map((digit,index)=><input key={index} ref={element=>{inputs.current[index]=element;}} aria-label={`Code digit ${index+1}`} inputMode="numeric" pattern="[0-9]*" autoComplete={index===0?'one-time-code':'off'} value={digit} maxLength={6} disabled={pending||!challenge} onChange={e=>change(index,e.target.value)} onPaste={e=>{e.preventDefault();change(index,e.clipboardData.getData('text'));}} onKeyDown={e=>{if(e.key==='Backspace'&&!digit&&index>0)inputs.current[index-1]?.focus();if(e.key==='ArrowLeft'&&index>0)inputs.current[index-1]?.focus();if(e.key==='ArrowRight'&&index<5)inputs.current[index+1]?.focus();}}/>)}</div><button className="auth-submit" disabled={pending||!csrf||!challenge||expired||digits.join('').length!==6}>{pending?<><LoaderCircle size={17} className="spin"/>Working…</>:<>{reset?'Verify code':'Verify email'}<ArrowRight size={17}/></>}</button></form><div className="otp-resend"><button type="button" disabled={pending||!challenge||wait>0} onClick={resend}>{wait?`Resend code in 00:${String(wait).padStart(2,'0')}`:'Resend code'}</button><Link href={reset?'/forgot-password':'/signup'}>Change email</Link></div><div className="auth-message" role="status">{message&&<p>{message}</p>}{expired&&<p>Your code has expired. Request a new code.</p>}{!challenge&&!message&&<p>Loading verification…</p>}</div><p className="otp-expiry"><LockKeyhole size={14}/>Your code expires in 10 minutes</p></div>;
}
