'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Check,Copy,LockKeyhole,Trophy,Users} from 'lucide-react';
import {Button} from './ui/button';
import {Entrance,CountUp} from './animation';
export type ReferralSummary={code:string;link:string;total:number;paid:boolean;rankingActive:boolean;rank:number|null;leaders:{name:string;total:number;rank:number;you:boolean}[]};
export function ReferralSettings({data,demo,error,onRetry}:{data?:ReferralSummary;demo:boolean;error:boolean;onRetry:()=>void}){
 const [message,setMessage]=useState('');
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setMessage(`${label} copied.`);}catch{setMessage('Copy is unavailable. Select the text below and copy it manually.');}}
 return <Entrance className="panel referral-settings"><div className="panel-heading"><div><span className="eyebrow">GROW YOUR CIRCLE</span><h2>Invite a friend</h2></div><Users size={21}/></div><p className="muted">Share your personal link. A referral counts after your friend verifies a new account.</p>{data?<><label>Your referral link<input aria-label="Your referral link" readOnly value={data.link} onClick={e=>e.currentTarget.select()}/></label><div className="referral-copy-actions"><Button onClick={()=>copy(data.link,'Referral link')}><Copy size={14}/>Copy referral link</Button><Button onClick={()=>copy(data.code,'Referral code')}><Copy size={14}/>Copy referral code</Button></div><label className="referral-code">Referral code<input aria-label="Your referral code" readOnly value={data.code} onClick={e=>e.currentTarget.select()}/></label><div className="referral-own-total"><CountUp value={data.total} format={value=>String(Math.round(value))}/><span>Verified referrals</span></div><p className="muted">{data.paid?data.rankingActive?'Your ranking is active.':'Your ranking opens after your first verified referral.':'Referral ranking is included with Pro and Lifetime.'}</p>{data.rankingActive&&<Link className="button" href="/ranking">View your ranking<ArrowRight size={14}/></Link>}</>:<p className="muted">{demo?'Sign in to get your own referral link.':error?'Your referral link could not load.':'Preparing your referral link…'}</p>}{error&&!demo&&<Button onClick={onRetry}>Retry referral link</Button>}{message&&<p className="mint" role="status"><Check size={14}/>{message}</p>}</Entrance>;
}
export function ReferralOverview({data,paid}:{data?:ReferralSummary;paid:boolean}){if(!paid)return null;return <Entrance className={`panel referral-overview ${data?.rankingActive?'referral-active':''}`}><span className="referral-trophy"><Trophy size={23}/></span><div><span className="eyebrow">YOUR REFERRAL CIRCLE</span><h2>{data?.rankingActive?`Your ranking · #${data.rank}`:'Build your circle'}</h2><p>{data?.rankingActive?`${data.total} verified friend${data.total===1?'':'s'} joined through your link.`:'Invite your first friend to unlock your place in the ranking.'}</p></div><Link className="button" href={data?.rankingActive?'/ranking':'/settings'}>{data?.rankingActive?'View ranking':'Get your invite link'}<ArrowRight size={15}/></Link></Entrance>;}
export function ReferralRanking({data,paid,error,onRetry}:{data?:ReferralSummary;paid:boolean;error:boolean;onRetry:()=>void}){
 if(!paid||!data?.rankingActive)return <Entrance className="panel referral-ranking-lock"><LockKeyhole size={27}/><h2>{paid?'Your circle starts with one friend':'Referral ranking'}</h2><p className="muted">{paid?'Share your link from Settings. Your first verified referral activates this page and adds Ranking to your sidebar.':'Ranking is available with Pro and Lifetime. You can still share your referral link from Settings.'}</p><Link className="button primary" href={paid?'/settings':'/plans'}>{paid?'Get my referral link':'View plans'}<ArrowRight size={15}/></Link>{error&&<Button onClick={onRetry}>Retry ranking</Button>}</Entrance>;
 return <><div className="referral-ranking-hero"><span className="referral-trophy"><Trophy size={32}/></span><div><span className="eyebrow">A LITTLE MOMENTUM, TOGETHER</span><h2>Your circle. Your place.</h2><p>Verified referrals from active accounts. More friends, more shared momentum.</p></div><div className="referral-rank-stat"><strong>#{data.rank}</strong><span>Your rank</span></div><div className="referral-rank-stat"><CountUp value={data.total} format={value=>String(Math.round(value))}/><span>Verified referrals</span></div></div><Entrance className="panel referral-leaderboard"><div className="panel-heading"><h2>Referral ranking</h2><Link href="/settings">Invite a friend<ArrowRight size={14}/></Link></div><ol>{data.leaders.map(row=><li key={row.rank} className={row.you?'referral-you':''}><span className="referral-place">{row.rank<=3?<Trophy size={17}/>:row.rank}<small>{row.rank<=3?`#${row.rank}`:''}</small></span><span className="referral-avatar">{row.name.split(' ').slice(0,2).map(part=>part[0]).join('').toUpperCase()}</span><div className="referral-person"><strong>{row.name}{row.you&&<small>You</small>}</strong><div className="referral-score-track"><span style={{width:`${row.total/Math.max(1,data.leaders[0].total)*100}%`}}/></div></div><span className="referral-score">{row.total}<small>verified</small></span></li>)}</ol><p className="muted">Pro and Lifetime members appear after their first verified referral. Ties are ordered by account creation date. Names and referral totals are shown; personal records and emails stay private.</p></Entrance></>;
}
