import { BrandMark } from './brand-mark';
export function AccountLoading(){return <div className="account-loading" role="status" aria-label="Opening your workspace"><BrandMark/><p>Opening your workspace…</p><Skeleton className="account-loading-bar"/></div>;}
function InsightSkeleton(){return <div className="insight-grid">{[0,1,2,3].map(i=><div className="insight-card" key={i}><Skeleton className="skeleton-short"/><Skeleton className="skeleton-value"/><Skeleton className="skeleton-text"/></div>)}</div>;}
export function Skeleton({className=''}:{className?:string}){return <div className={`skeleton ${className}`} aria-hidden="true"/>;}
export function ProfileSkeleton(){return <div className="profile-skeleton"><Skeleton className="skeleton-avatar"/><div><Skeleton className="skeleton-text"/><Skeleton className="skeleton-short"/></div></div>;}
export function NotificationSkeleton(){return <div className="notification-skeleton"><Skeleton className="skeleton-text"/><Skeleton className="skeleton-short"/></div>;}
export function MetricSkeleton(){return <div className="panel metric-card skeleton-card"><Skeleton className="skeleton-icon"/><div><Skeleton className="skeleton-short"/><Skeleton className="skeleton-value"/><Skeleton className="skeleton-text"/></div></div>;}
export function ChartSkeleton({donut=false}:{donut?:boolean}){return <div className={`panel ${donut?'spending-panel':'cash-panel'}`}><Skeleton className="skeleton-title"/><div className={donut?'skeleton-donut':'skeleton-chart'}>{donut?<div className="skeleton-donut-hole"/>:<><Skeleton/><Skeleton/><Skeleton/></>}</div>{donut?<NotificationSkeleton/>:<Skeleton className="skeleton-text"/>}</div>;}
export function TaskSkeleton(){return <div className="panel task-skeleton"><Skeleton className="skeleton-title"/>{[0,1,2].map(i=><Skeleton key={i} className="skeleton-row"/>)}</div>;}
export function TableSkeleton(){return <div className="panel"><Skeleton className="skeleton-title"/>{[0,1,2,3,4].map(i=><Skeleton key={i} className="skeleton-row"/>)}</div>;}
export function GoalSkeleton(){return <div className="panel goal-skeleton"><Skeleton className="skeleton-title"/><Skeleton className="skeleton-row"/><Skeleton className="skeleton-short"/></div>;}
export function WorkspaceSkeleton({path=''}:{path?:string}){return <div className="app-shell" role="status" aria-label="Loading your workspace"><aside className="sidebar"><div className="brand"><span className="logo-mark"><BrandMark/></span>Daily Ledger</div><Skeleton className="skeleton-row"/>{Array.from({length:7},(_,i)=><Skeleton className="skeleton-row" key={i}/>)}<div className="sidebar-bottom"><ProfileSkeleton/></div></aside><div className="main-shell"><header className="topbar"><Skeleton className="skeleton-title"/><ProfileSkeleton/></header><main className={path?'feature-main':''}><div className="skeleton-heading"><Skeleton className="skeleton-title"/><Skeleton className="skeleton-text"/></div>{['finance','tasks','fitness','meals','goals'].includes(path)&&<InsightSkeleton/>}{path===''?<><div className="metrics-grid">{[0,1,2,3].map(i=><MetricSkeleton key={i}/>)}</div><div className="chart-grid"><ChartSkeleton/><ChartSkeleton donut/></div><div className="widgets-grid"><TaskSkeleton/><TaskSkeleton/><GoalSkeleton/></div></>:path==='finance'?<><div className="finance-guidance skeleton-guidance"><Skeleton className="skeleton-title"/><Skeleton className="skeleton-text"/><Skeleton className="skeleton-text"/></div><div className="chart-grid"><ChartSkeleton/><ChartSkeleton donut/></div><TableSkeleton/></>:path==='goals'?<div className="two-grid"><GoalSkeleton/><GoalSkeleton/></div>:path==='settings'?<div className="two-grid"><div className="panel"><ProfileSkeleton/><TableSkeleton/></div><TableSkeleton/></div>:<><TaskSkeleton/><TableSkeleton/></>}</main></div><span className="sr-only">Loading records…</span></div>;}
