'use client';
import Link from 'next/link';
import {useState,useEffect,type CSSProperties} from 'react';
import {habitStats,recordsOf,type Snapshot,type LedgerRecord} from '@ledger/shared';
import {HabitChecklist} from './habit-checklist';
import {Dumbbell,ArrowUpRight,Plus,Trash2,Search} from 'lucide-react';
import {muscleGroups,exerciseGuides,exerciseSource,workoutTemplates,type MuscleGroup} from '../lib/exercise-guides';
import {Entrance} from './animation';
import {Button} from './ui/button';

export type ExerciseTrackingProps={s:Snapshot;today:string;pending:boolean;onComplete:(h:LedgerRecord<'habit'>,date:string)=>void;onAdd:(initial:Record<string,unknown>)=>void;onEdit:(h:LedgerRecord<'habit'>)=>void;onRemove:(h:LedgerRecord<'habit'>)=>void};
export function ExerciseTracking({s,today,pending,onComplete,onAdd,onEdit,onRemove,slug}:ExerciseTrackingProps&{slug?:string}){
 const habits=recordsOf(s.records,'habit').filter(h=>h.data.exerciseSlug&&(!slug||h.data.exerciseSlug===slug||h.data.exerciseSlug.startsWith('custom-')));const exercise=exerciseGuides.find(e=>e.slug===slug);
 const start=()=>onAdd({title:exercise?.name||'My exercise routine',exerciseSlug:slug,exerciseMuscle:exercise?.muscle||'Full body',startDate:today,days:[0,1,2,3,4,5,6]});
 const custom=()=>onAdd({title:'',exerciseSlug:`custom-${crypto.randomUUID()}`,exerciseMuscle:exercise?.muscle||'Full body',startDate:today,days:[1,3,5]});
 return <div className="exercise-tracking"><div className="exercise-consistency-key"><strong>Exercise consistency</strong><Button onClick={custom}><Plus size={14}/>Add custom exercise</Button><span><i style={{background:'#f6cf70'}}/>0–2 days</span><span><i style={{background:'#80e4bd'}}/>3–6 days</span><span><i style={{background:'#fb7185'}}/>7+ days</span></div><p className="guide-note">Colour tracks consecutive scheduled check-ins, not muscle growth. A missed scheduled day resets the streak; planned rest days do not. Set a schedule that allows recovery.</p>{habits.length?<HabitChecklist s={{...s,records:s.records.filter(r=>r.kind!=='habit'||habits.some(h=>h.id===r.id))}} month={today.slice(0,7)} today={today} pending={pending} onComplete={onComplete} onAdd={start} onEdit={onEdit} onRemove={onRemove}/>:exercise?<Button onClick={start}><Plus size={14}/>Start {exercise.name} checklist</Button>:<p className="guide-note">Select an exercise to start its checklist.</p>}</div>;
}

export function BodyMap({selected,streak=0}:{selected:MuscleGroup;streak?:number}){
 const [back,setBack]=useState(['Back','Triceps','Glutes','Hamstrings','Calves'].includes(selected));
 useEffect(()=>setBack(['Back','Triceps','Glutes','Hamstrings','Calves'].includes(selected)),[selected]);
 const regions:Partial<Record<MuscleGroup,string>>=back?{
 Back:'M160 255Q255 220 353 255L386 380 348 572 270 610 180 572 138 380Z',Shoulders:'M153 248Q73 250 57 350L132 362 172 286ZM356 248Q436 250 451 350L376 362 336 286Z',Triceps:'M61 355 126 367 135 473 89 547 42 518ZM448 355 382 367 374 473 420 547 467 518Z',Forearms:'M43 528 90 550 81 674 22 701ZM465 528 419 550 428 674 487 701Z',Glutes:'M169 616Q253 576 338 616L362 735 282 774 253 718 223 774 145 735Z',Hamstrings:'M146 752 226 789 227 913 194 1018 124 992ZM363 752 283 789 282 913 315 1018 385 992Z',Calves:'M128 1018 194 1034 180 1198 163 1330 127 1287ZM381 1018 315 1034 329 1198 346 1330 382 1287Z'
 }:{Chest:'M151 291Q188 257 248 291L247 388Q183 427 130 375ZM359 291Q322 257 262 291L263 388Q327 427 380 375Z',Shoulders:'M142 257Q76 258 57 342L126 358 159 296ZM368 257Q434 258 453 342L384 358 351 296Z',Biceps:'M61 363 123 378 137 455 96 515 47 505ZM449 363 387 378 373 455 414 515 463 505Z',Forearms:'M46 523 92 535 84 653 24 702ZM464 523 418 535 426 653 486 702Z',Core:'M167 411 248 419 248 652 213 714 157 620ZM343 411 262 419 262 652 297 714 353 620Z',Quads:'M145 752 224 740 231 899 205 1024 126 1002ZM365 752 286 740 279 899 305 1024 384 1002Z',Calves:'M129 1060 201 1064 183 1218 166 1326 129 1294ZM381 1060 309 1064 327 1218 344 1326 381 1294Z'};
 return <div className="body-map"><div className="segmented"><button className={!back?'selected':''} onClick={()=>setBack(false)}>Front</button><button className={back?'selected':''} onClick={()=>setBack(true)}>Back</button></div><div className={`anatomy-view ${back?'anatomy-back':''}`} role="img" aria-label={`${back?'Back':'Front'} muscle map, selected ${selected}`}><div className="anatomy-render"/><svg className="anatomy-overlay" viewBox="0 0 512 1536" preserveAspectRatio="none" aria-hidden="true" style={{color:streak>=7?'#fb7185':streak>=3?'#80e4bd':'#f6cf70'}}>{Object.entries(regions).filter(([group])=>selected==='Full body'||group===selected).map(([group,d])=><path key={group} data-muscle={group} d={d}/>)}</svg><span className="anatomy-focus">{selected}</span></div><span className="body-map-caption">Illustrative anatomy · choose a target below</span></div>;
}
export function WorkoutGuide({onLog,tracking}:{onLog:(initial:Record<string,unknown>)=>void;tracking:ExerciseTrackingProps}){
 const [activeExercise,setActiveExercise]=useState<string>();
 const [muscle,setMuscle]=useState<MuscleGroup>('Full body'),[equipment,setEquipment]=useState('All equipment'),[search,setSearch]=useState(''),[showAll,setShowAll]=useState(false);const [routine,setRoutine]=useState<Array<{index:number;sets:number;reps:string}>>([]),[name,setName]=useState('My workout'),[duration,setDuration]=useState(30);
 const matching=exerciseGuides.map((exercise,index)=>({exercise,index})).filter(({exercise})=>(muscle==='Full body'||exercise.muscle===muscle)&&(equipment==='All equipment'||exercise.equipment===equipment)&&exercise.name.toLowerCase().includes(search.toLowerCase()));
 const selectedSlug=activeExercise||exerciseGuides.find(e=>e.muscle===muscle)?.slug;
 const add=(index:number)=>setRoutine(rows=>rows.some(r=>r.index===index)?rows:[...rows,{index,sets:2,reps:exerciseGuides[index].reps}]);
 return <Entrance className="panel workout-guide"><div className="panel-heading"><div><span className="eyebrow">UNDERSTAND YOUR TRAINING</span><h2>Train with a clear purpose</h2><p>Select a body part, learn the movement, then build your session.</p></div><Dumbbell size={22}/></div><div className="workout-guide-layout"><div className="muscle-selector"><BodyMap selected={muscle} streak={Math.max(0,...recordsOf(tracking.s.records,'habit').filter(h=>h.data.exerciseSlug===selectedSlug).map(h=>habitStats(h,tracking.s.records,tracking.today).current))}/><div className="muscle-buttons" aria-label="Choose body part">{muscleGroups.map(group=><button key={group} aria-pressed={muscle===group} className={muscle===group?'selected':''} onClick={()=>{setMuscle(group);setActiveExercise(undefined);}}>{group}</button>)}</div></div><div><div className="guide-filter"><label><Search size={15}/><input aria-label="Search exercises" placeholder="Find an exercise…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Exercise equipment" value={equipment} onChange={e=>setEquipment(e.target.value)}>{['All equipment','Bodyweight','Dumbbells','Machine'].map(v=><option key={v}>{v}</option>)}</select></div><div className="exercise-grid">{matching.slice(0,showAll?matching.length:4).map(({exercise,index})=><article className="exercise-card" key={exercise.name} style={{'--exercise-accent':['#80e4bd','#a894ff','#83c8ff'][index%3]} as CSSProperties}><span className="exercise-muscle">{exercise.muscle}</span><h3><button className="plain-button" onClick={()=>{setMuscle(exercise.muscle);setActiveExercise(exercise.slug);}}>{exercise.name}</button></h3><small>{exercise.equipment} · Also works {exercise.secondary}</small><ul>{exercise.tips.map(tip=><li key={tip}>{tip}</li>)}</ul><div><Button onClick={()=>{setMuscle(exercise.muscle);setActiveExercise(exercise.slug);add(index);}} disabled={routine.some(r=>r.index===index)}><Plus size={13}/>{routine.some(r=>r.index===index)?'Added':'Add to session'}</Button><Link href={`/fitness/exercises/${exercise.slug}`}>View guide <ArrowUpRight size={13}/></Link></div></article>)}</div>{matching.length>4&&<Button className="guide-show-more" onClick={()=>setShowAll(v=>!v)}>{showAll?'Show fewer exercises':`Show all ${matching.length} exercises`}</Button>}{!matching.length&&<p className="guide-note">No match. Try another body part or equipment filter.</p>}</div></div>
 <div className="custom-exercise-library">{recordsOf(tracking.s.records,'habit').filter(h=>h.data.exerciseSlug?.startsWith('custom-')).map(h=><button key={h.id} data-record-id={`custom-exercise-${h.id}`} data-motion-state={String(h.version)} className={activeExercise===h.data.exerciseSlug?'selected':''} onClick={()=>{setMuscle(h.data.exerciseMuscle||'Full body');setActiveExercise(h.data.exerciseSlug);}}><strong>{h.data.title}</strong><small>{h.data.exerciseMuscle||'Full body'} · Custom exercise</small>{h.data.notes&&<span>{h.data.notes}</span>}</button>)}</div><ExerciseTracking {...tracking} slug={selectedSlug}/><div className="routine-presets"><h3>Start from a workout template</h3><div>{workoutTemplates.map(template=><button key={template.name} onClick={()=>{setName(template.name);setDuration(template.duration);setRoutine(template.exercises.map(index=>({index,sets:2,reps:exerciseGuides[index].reps})));}}><strong>{template.name}</strong><span>{template.duration} min · {template.exercises.length} exercises</span><small>{template.description}</small></button>)}</div></div>
 {routine.length>0&&<div className="routine-editor"><div className="routine-title"><label>Session name<input value={name} maxLength={160} onChange={e=>setName(e.target.value)}/></label><label>Minutes<input type="number" min={1} max={1440} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label></div><div className="routine-labels"><span>Exercise / target</span><span>Sets</span><span>Reps / time</span><span/></div>{routine.map((row,i)=><div className="routine-row" key={row.index}><div><strong><button className="plain-button" onClick={()=>{setMuscle(exerciseGuides[row.index].muscle);setActiveExercise(exerciseGuides[row.index].slug);}}>{exerciseGuides[row.index].name}</button></strong><small>{exerciseGuides[row.index].muscle}</small></div><input aria-label={`Sets for ${exerciseGuides[row.index].name}`} type="number" min={1} max={10} value={row.sets} onChange={e=>setRoutine(rows=>rows.map((r,j)=>j===i?{...r,sets:Number(e.target.value)}:r))}/><input aria-label={`Reps for ${exerciseGuides[row.index].name}`} maxLength={40} value={row.reps} onChange={e=>setRoutine(rows=>rows.map((r,j)=>j===i?{...r,reps:e.target.value}:r))}/><button className="icon-button" aria-label={`Remove ${exerciseGuides[row.index].name} from session`} onClick={()=>setRoutine(rows=>rows.filter((_,j)=>j!==i))}><Trash2 size={14}/></button></div>)}<p className="guide-note">Warm up first. Suggested starting ranges are editable; choose loads you can control. Rest between sets and allow recovery between strength sessions.</p><Button variant="primary" disabled={!name.trim()||!Number.isInteger(duration)||duration<1||duration>1440||routine.some(r=>!Number.isInteger(r.sets)||r.sets<1||r.sets>10||!r.reps.trim())} onClick={()=>onLog({title:name,type:'Strength',duration,notes:routine.map(r=>`${exerciseGuides[r.index].name}: ${r.sets} sets × ${r.reps} (${exerciseGuides[r.index].muscle})`).join('\n')})}>Log this routine <ArrowUpRight size={15}/></Button></div>}
 <p className="guide-note exercise-disclaimer">Our analysis describes common muscle targets, not guaranteed growth. Adjust or skip movements to suit your ability and comfort. Stop if a movement hurts; ask a qualified trainer about form or a clinician about injuries. <a href={exerciseSource} target="_blank" rel="noreferrer">ACE exercise library</a> · <a href="https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/strength-training/art-20046031" target="_blank" rel="noreferrer">Mayo Clinic guidance</a></p></Entrance>;
}
